### ISSUE TITLE
Markers cover most of the map.

### ISSUE THREAD

**Issue by gknisely** [mapzen/eraser-map#100]
Device name: samsung Model: SM-G900V
Android Version: 5.0
App build number: master-420
What did you expected to happen?  I expected one result searching for lampeter strasburg high school.
What happened instead? A lot of markers showed up on the map.  Excessive results.    
Steps to reproduce: Search for lampeter strasburg high school

Note:  This could be a pelias issue, but I also feel that the markers are cluttering the map.  See screenshots.

![screenshot_2015-11-03-18-05-07](https://cloud.githubusercontent.com/assets/2676277/10944290/866b082e-82e6-11e5-91c1-6a4d28fbc7c2.png)
![screenshot_2015-11-03-18-07-24](https://cloud.githubusercontent.com/assets/2676277/10944289/8663288e-82e6-11e5-97b5-6dabe613b990.png)

**Comment by ecgreb** [comment]
This is a combination of two issues:

1. Sprite scaling issues with the Tangram stylesheet are causing pins to draw jumbo size. Fix is in progress.

2. Duplicate results from Pelias. From what I understand happens when more than one datasource contains the same POI. Perhaps @dianashk or @missinglink can shed some more light here.

**Comment by dianashk** [comment]
Duplicates are in fact a problem at this time. We don't have a short term fix in the works, so if this is a big concern it might need to be taken care of client-side. Sorry.

It is an issue we will reprioritize after the current sprint on WOF integration. Feel free to weigh in on that [here](https://github.com/pelias/api/issues/362).

**Comment by blair1618** [comment]
Sprite sizes have been corrected since that build - they should be much more reasonable now!

**Comment by mjcunningham** [comment]
@ecgreb Can we close this as it's being tracked in pelias now?
