### ISSUE TITLE
Map labels not rendering correctly in Japan

### ISSUE THREAD

**Issue by ecgreb** [mapzen/eraser-map#101]
![image](https://cloud.githubusercontent.com/assets/464123/10946128/98242cc8-82ee-11e5-82b3-f9c7b7fa68de.png)

**Comment by tallytalwar** [comment]
Better font file usage text shaping should resolve this. Have a card for this on tangram side.

**Comment by mjcunningham** [comment]
@blair1618 @tallytalwar did we end up tracking this on the rendering board?

**Comment by tallytalwar** [comment]
Yup, there are couple of cards for this issue. This is one of the big target items we have remaining on tangram-es end for eraser-map map launch.

**Comment by karimnaaji** [comment]
Adressed through https://github.com/tangrams/fontstash-es/pull/18 and https://github.com/tangrams/tangram-es/issues/508 ; available on next tangram-es build.

**Comment by tallytalwar** [comment]
Tangram updates here: https://github.com/tangrams/tangram-es/pull/561
