### ISSUE TITLE
Current route position icon closer to the bottom of the map display

### ISSUE THREAD

**Issue by dgearhart** [mapzen/eraser-map#105]
* **Device name:** samsung Model: SM-G900V
* **Android Version:** 5.0
* **App build number:** master-420
* **What did you expected to happen?** Have the current route position icon closer to the bottom of the map display so the user could see more of what is coming ahead
* **What happened instead?**  The icon was in the middle of the map display - see the screenshots.
* **Attach a screenshot**
![screenshot_2015-11-05-07-20-23](https://cloud.githubusercontent.com/assets/7515853/10970033/fc7b20f4-8399-11e5-8a12-634e76efa7ef.png)
![screenshot_2015-11-05-07-21-37](https://cloud.githubusercontent.com/assets/7515853/10970037/0ca035f0-839a-11e5-859c-2758507769cd.png)

**Comment by ecgreb** [comment]
Definitely on our list for v1.

**Comment by nvkelso** [comment]
+1
