### ISSUE TITLE
Splash screen animation cut off

### ISSUE THREAD

**Issue by ecgreb** [mapzen/eraser-map#107]
Samsung Galaxy S2
Android 4.0.4

![ezgif com-crop](https://cloud.githubusercontent.com/assets/464123/10998871/5f9e2ba0-8466-11e5-9078-da15416aefa8.gif)

**Comment by tallytalwar** [comment]
Wow... that's a bullet going through. :)

**Comment by msmollin** [comment]
I dunno. It reminds me of those anime cartoons where the character has the super sharp katana and slices through like a tree or a building or something and then it slowly falls over as they walk away. I'd call it a feature.

**Comment by blair1618** [comment]
I get the same effect on a Galaxy Nexus. Parts of the animation seems to be resolution-dependent; on some new devices the "bullet" doesn't go all the way across the screen. The Galaxy Nexus has a 720 x 1280 display. The display [density](https://developer.android.com/reference/android/util/DisplayMetrics.html#density) might also come into play.

**Comment by msmollin** [comment]
I hadn't noticed it on my nvidia shield, which is similar resolution though. I'll go check it again.

**Comment by nvkelso** [comment]
> @blair1618 says: on some new devices the "bullet" doesn't go all the way across the screen. 

I'm getting the "stuck" bullet on my Samsung Galaxy S6 edge (it never finishes going across the screen).

**Comment by souperneon** [comment]
same here. I know we wanted to do this the right way by animating inside of the app. Is there an easier way? I'd like to at least discuss that in event of not having enough time to fix it before release. I don't feel comfortable releasing as is.

**Comment by ecgreb** [comment]
It could take a considerable amount of effort to get this animation just right on all screen sizes and densities. That is one of the challenges of something like this on Android.

My hit is we should go with a static image for v1.

**Comment by mjcunningham** [comment]
:+1: for the easy thing here. It's super cool but theres a bunch of other cool we should get in there first.

**Comment by souperneon** [comment]
https://github.com/mapzen/eraser-map/pull/281
