### ISSUE TITLE
Multiple location markers displaying

### ISSUE THREAD

**Issue by msmollin** [mapzen/eraser-map#108]
Manufacturer: OnePlus
Model: A0001
Release: 5.1.1
Code name: REL
SDK: 22
Build number: master-442

What did you expect to happen?
As I was driving, I'd expect to only see 1 location marker

What happened instead?
Leftover location markers seem to got stuck on my origination location when I initially opened the map.

Steps to reproduce:

![screenshot_2015-11-06-11-13-32](https://cloud.githubusercontent.com/assets/1163880/11005114/09906286-848a-11e5-8f2a-4a86fdfa6441.png)

**Comment by ecgreb** [comment]
Its called quantum mechanics and its a feature :trollface:
