### ISSUE TITLE
Location marker should update regularly even when not routing

### ISSUE THREAD

**Issue by msmollin** [mapzen/eraser-map#109]
Manufacturer: OnePlus
Model: A0001
Release: 5.1.1
Code name: REL
SDK: 22
Build number: master-442

What did you expect to happen?
Tapping the location button should "lock" the marker to my location and continue to update as I drive around

What happened instead?
It stayed on the original location and didn't update

Steps to reproduce:
Seems to be "how it works" - but this doesn't match any of the other mapping tools available?

**Comment by ecgreb** [comment]
Indeed the app should update the position of the current location marker even while not in routing mode.
