### ISSUE TITLE
Start instruction not called out

### ISSUE THREAD

**Issue by dgearhart** [mapzen/eraser-map#111]
* **Device name:** samsung Model: SM-G900V
* **Android Version:** 5.0
* **App build number:** master-430
* **What did you expected to happen?** When starting navigation I expect to hear the "start maneuver instruction" if I have not started to drive yet.
* **What happened instead?** The app was silent when I selected the "START NAVIGATION" button
* **Steps to reproduce:** I have been having a hard time reproducing because it does not happen everytime. I thought it might because of running route from house then walking to car before starting nav - but, it also happened for me when sitting in the driver seat.

**Comment by ecgreb** [comment]
I think I know what this is and we should be able to fix it.

I am attempting to play the alert and post instruction for the first maneuver which do not exists and sometimes they override the actual pre instruction which is what we should be playing.
