### ISSUE TITLE
Use current heading on reroute

### ISSUE THREAD

**Issue by dgearhart** [mapzen/eraser-map#112]
* **Device name:** samsung Model: SM-G900V
* **Android Version:** 5.0
* **App build number:** master-430
* **What did you expected to happen?** When traveling south on Middletown Road and passing by the right turn onto Deer Run Drive - the reroute, based on the current heading, should have continued south on Middletown Road to take the next right onto Southpoint Drive.
* **What happened instead?** Reroute was heading north on Middletown Road - which user would have to make a u-turn in the middle of the street.
* **Steps to reproduce:** Use supplied origin/destination
* **Attach a screenshot**
Default route:
![screenshot from 2015-11-09 13 37 13](https://cloud.githubusercontent.com/assets/7515853/11042859/a2b9130e-86e7-11e5-8a14-e3a50911a3dd.png)

When passing Deer Run Drive - the reroute was:
![screenshot from 2015-11-09 13 46 58](https://cloud.githubusercontent.com/assets/7515853/11043016/94fbb572-86e8-11e5-98ea-b19c1cb9a404.png)

When passing Deer Run Drive - the reroute should have been:
![screenshot from 2015-11-09 13 47 39](https://cloud.githubusercontent.com/assets/7515853/11043026/a9e78e48-86e8-11e5-8ccb-8c760de4d4cf.png)

* **Where were you?** 
* **Routing from origin:** "lat":40.251389,"lon":-76.708580,"street":"Middletown Road"
* **Routing to destination:** "lat":40.244621,"lon":-76.721321

**Comment by ecgreb** [comment]
Fixed by https://github.com/mapzen/eraser-map/pull/110
