### ISSUE TITLE
Update zoom levels for home screen and routing view

### ISSUE THREAD

**Issue by souperneon** [mapzen/eraser-map#113]
DEFAULT_ZOOM : 16
ROUTING_ZOOM : 18

**Comment by nvkelso** [comment]
Let's carve off the dynamic zoom range change to a separate issue.

**Comment by souperneon** [comment]
@nvkelso let me know if you would like me to create that issue?

**Comment by nvkelso** [comment]
@souperneon sure!

**Comment by nvkelso** [comment]
Related: https://github.com/mapzen/eraser-map/issues/169
