### ISSUE TITLE
Missing attribution

### ISSUE THREAD

**Issue by zerebubuth** [mapzen/eraser-map#117]
* Device name: Samsung Galaxy Tab 4 8.0 16GB, Black
* Android version: 4.4.4
* App build number: master-442
* What did you expect to happen? I expected to see attribution, either prominently in the splash screen or visible on the map, explaining that some of the data comes from OpenStreetMap.
* What happened instead? There's no attribution.
* Steps to reproduce: Open the app.

When using OpenStreetMap data, the requirement to attribute is not optional. We should include [the required credit](http://www.openstreetmap.org/copyright) either on the map, or prominently in the splash screen.

**Comment by randymeech** [comment]
we should have this on the map, as with the Open app

**Comment by mjcunningham** [comment]
@souperneon is there a mock for this? I feel like we should get it in there soon to verify the screen seem crowded.

**Comment by souperneon** [comment]
Can we use the same one as Open? Does the language have to change at all?

**Comment by msmollin** [comment]
For reference sake, here's what it looked like in Open, courtesy of @ecgreb 

![pasted image at 2016_02_08 06_13 pm](https://cloud.githubusercontent.com/assets/1163880/12902516/b428deae-ce8f-11e5-9215-65f67b73d9c7.png)

**Comment by msmollin** [comment]
I have no problems with this ^^

**Comment by nvkelso** [comment]
Can this go into the about page (settings) instead of on the map?

**Comment by mjcunningham** [comment]
From my understanding the OSM terms of service say it needs to be on the map.

http://wiki.openstreetmap.org/wiki/Legal_FAQ#3a._I_would_like_to_use_OpenStreetMap_maps._How_should_I_credit_you.3F

@nvkelso do you think we should have some kind of mapzen standard implementation on it and do the same thing on web/ mobile?

**Comment by tallytalwar** [comment]
In that case, should tangram render it on the map by default?

**Comment by msmollin** [comment]
Tangram probably shouldn't just because I don't think tangram should care about the source of the data. Tangram (as far as I understand it) expects Android and iOS to load the data and then said data gets passed to Tangram for rendering, right? So I would expect that whoever is handling the loading to also handle attributing the source of the data.

**Comment by ecgreb** [comment]
Another reason to keep this client side is so we (or other developers) can control the position of the attribution for overall layout feng shui.

**Comment by blair1618** [comment]
The onus of attribution definitely falls on the user, it's not feasible for tangram to reliably determine the origin of map data. It may be conceivably useful for tangram to have a convenience function for drawing attribution text over a map, but honestly drawing text overlays is just as easy with native platform UI tools.

**Comment by zerebubuth** [comment]
One way to make this easier for users and less prone to problems might be something like [tilejson](https://github.com/mapbox/tilejson-spec/tree/master/2.1.0). That way, a tileset can be bundled with information about its format, available zoom ranges, required attribution and so on. (Even documentation! :open_mouth: We promise we'll update that soon...)

If we started providing that, would it make sense to provide an input method for that, something like?

```yaml
sources:
    osm:
        type: TileJSON
        url: '//vector.dev.mapzen.com/osm/tile.json?api_key=API_KEY_HERE'
```

That would display the attribution on the map in Tangram itself, and relieve the user from the requirement of implementing it themselves? Of course, there could be a flag to disable it where the user wants to customize display. Perhaps called `Tangram.setIWillDrawRequiredAttributionAndIUnderstandICantJustNotDisplayItBecauseIFeelLikeIt()` or something.

**Comment by msmollin** [comment]
Ha, that method definition is very Objective-C like. :+1: 

Architecturally speaking, I'm still leaning towards having the user implement it, even considering tilejson in the mix, because ultimately we'd be trying to enforce design decisions on implementing developers, which @ecgreb mentioned ultimately is up to them, not us.

**Comment by zerebubuth** [comment]
Oh, I thought I was being Java-like. Perhaps just being [Blub](http://www.paulgraham.com/avg.html)-like.

The user should definitely be encouraged to implement it, but it's nice to start from a sensible default. Given that attribution on the map is _mandatory_, then we can help anyone who uses Tangram (ES or JS) get something to production quicker by providing a sensible default. Along the way, we can help them avoid finding out that the attribution is mandatory when someone (for example) calls them out on Twitter for not having appropriate attribution.

**Comment by blair1618** [comment]
Tilejson would certainly make it easier for tangram to automatically display attribution. We could also do something very simple like add an `attribution` field to data sources in the stylesheet (cc @bcamper). Designing the syntax and UX for this deserves a bit of thought, so I think for eraser-map specifically it will be more expedient to simply implement a text overlay on the map view that provides the attribution we want.

**Comment by mjcunningham** [comment]
I'm w @blair1618 on this one. Let's split this into two issues and track one in tangram. 

Defaulting to @bcamper for thoughts on the Tangram issue.

**Comment by bcamper** [comment]
For now, for Eraser Map, I would like to leave this as a client app responsibility, as its the most expedient and allows us to defer some decisions on our approach. Future options in Tangram are:

- Do nothing, leave it as a client responsibility. I like the idea of adding a per-data-source `attribution` field to scene files regardless, so they they are a self-contained document of what's needed for their proper usage. But Tangram could simply provide these attribution strings (individually or concatenated for all sources) to the client.
- Implement attribution display at the platform SDK level, which avoids complicating the Tangram C++ core (think of wanting control over for your attribution font, etc.). The platform SDKs will be the primary way the library is publicly supported/distributed, and if you're using the underlying C++ API, you're probably doing something custom (such as Giflantro), and doing your own attribution display feels reasonable to me.
- Implement attribution display in the Tangram C++ core. I'd prefer to avoid this as it's a bit of a distraction and requires additional text rendering logic out of band from the label rendering process. It's doable though, just not something we want to take on now.

**Comment by zerebubuth** [comment]
:smile_cat:
