### ISSUE TITLE
Combine quick maneuver with previous pre transition instruction

### ISSUE THREAD

**Issue by dgearhart** [mapzen/eraser-map#118]
* **Device name:** samsung Model: SM-G900V
* **Android Version:** 5.0
* **App build number:** master-430
* **What did you expected to happen?** To have the left onto North Plum Street, and then the right onto East Fulton Street called out together
* **What happened instead?** The left onto North Plum Street then the post phrase (Continue for 300 feet) then the right onto East Fulton Street.
* **Steps to reproduce:** Run route with supplied origin and destination
* **Attach a screenshot**
![screenshot from 2015-11-09 14 48 13](https://cloud.githubusercontent.com/assets/7515853/11044613/f09fa016-86f0-11e5-92fb-f941c2032345.png)

* **Where were you?** Travelling west on East Walnut Street, Turn left onto North Plum Street, Turn right onto East Fulton Street.
* **Routing from origin:** "lat":40.043728,"lon":-76.296417,"street":"East Walnut Street"
* **Routing to destination:** "lat":40.042507,"lon":-76.299263,"street":"East Fulton Street"

Here is what is returned from service - which is correct, they are separate maneuvers:
2: Turn left onto North Plum Street. 
   VERBAL_ALERT: Turn left onto North Plum Street.
   VERBAL_PRE: Turn left onto North Plum Street.
   VERBAL_POST: Continue for 300 feet.

3: Turn right onto East Fulton Street. 
   VERBAL_ALERT: Turn right onto East Fulton Street.
   VERBAL_PRE: Turn right onto East Fulton Street.
   VERBAL_POST: Continue for 400 feet.

4: You have arrived at East Fulton Street. 
   VERBAL_ALERT: You will arrive at East Fulton Street.
   VERBAL_PRE: You have arrived at East Fulton Street.

* **Suggestion** Append the "VERBAL_ALERT: Turn right onto East Fulton Street. " instruction onto the "VERBAL_PRE: Turn left onto North Plum Street" instruction and do not callout the "VERBAL_POST: Continue for 300 feet" instruction - for example:
Turn left onto North Plum Street then Turn right onto East Fulton Street.

**Comment by ecgreb** [comment]
Is this something we would be able to change in the response format so it automatically appends verbal instructions when it makes sense to do so?

**Comment by dgearhart** [comment]
Here is another example where the app did not call out maneuver#3 - Turn left to take the US 322 West ramp toward Harrisburg.

* **Routing from origin:** "lat":40.256802,"lon":-76.709160,"street":"Middletown Road"
* **Routing to destination:** "lat":40.259254,"lon":-76.714989,"street":"US 322 West"

Current output:
1: Head north on Middletown Road.
VERBAL_PRE: Head north on Middletown Road for 1 tenth of a mile.

2: Continue on South Hanover Street.
VERBAL_ALERT: Continue on South Hanover Street.
VERBAL_PRE: Continue on South Hanover Street for 40 feet.

3: Turn left to take the US 322 West ramp toward Harrisburg.
VERBAL_ALERT: Turn left to take the U.S. 3 22 West ramp.
VERBAL_PRE: Turn left to take the U.S. 3 22 West ramp toward Harrisburg.

4: Merge onto US 322 West.
VERBAL_ALERT: Merge onto U.S. 3 22 West.
VERBAL_PRE: Merge onto U.S. 3 22 West.
VERBAL_POST: Continue for 2 tenths of a mile.

5: You have arrived at US 322 West.
VERBAL_ALERT: You will arrive at U.S. 3 22 West.
VERBAL_PRE: You have arrived at U.S. 3 22 West.

I submitted valhalla/odin#157 to help - but should still be able to handle

**Comment by dgearhart** [comment]
@ecgreb - I think we should keep the timing of the maneuver callouts on the app side. Could we discuss further next week?

**Comment by ecgreb** [comment]
Sounds like a plan
