### ISSUE TITLE
Eraser map crashes on routing on LGE LG-D802 (LG-G2)

### ISSUE THREAD

**Issue by tallytalwar** [mapzen/eraser-map#123]
Device: LG-D802

Android version: 4.4.2

App build number: master-465

Steps to reproduce:
- Seems to be specific to this device, not reproducible on other devices I tried.
- When I try to navigate to any location it crashes with the following `OpenGLRenderer` error:

```
11-16 13:26:45.255 30591-30591/com.mapzen.erasermap W/Adreno-ES20: <core_glMapBufferRange:1476>: GL_INVALID_VALUE
11-16 13:26:45.255 30591-30591/com.mapzen.erasermap E/OpenGLRenderer: Could not map GPU pixel buffer: 0x501
11-16 13:26:45.255 30591-30591/com.mapzen.erasermap A/libc: Fatal signal 11 (SIGSEGV) at 0x0008146c (code=1), thread 30591 (apzen.erasermap)
```

Graphics Card details:

```
11-16 13:27:13.665 32623-32623/com.mapzen.erasermap I/Adreno-EGL: <qeglDrvAPI_eglInitialize:385>: EGL 1.4 QUALCOMM build:  ()
11-16 13:27:13.665 32623-32623/com.mapzen.erasermap I/Adreno-EGL: OpenGL ES Shader Compiler Version: E031.24.00.02
```

cc. @blair1618 and @karimnaaji

**Comment by blair1618** [comment]
Can you try the eraser map style in the tangram demo app by itself to determine whether this is internal to the renderer?

The call that causes the crash is internal to the driver, so this may just be a bug in Qualcomm's drivers (again) :\

**Comment by blair1618** [comment]
The error seems to be coming from this bit of code in Android: 

https://github.com/android/platform_frameworks_base/blob/master/libs/hwui/PixelBuffer.cpp#L121

This code is for hardware acceleration of Android UI, which suggests that there may be an issue in the UI code of Eraser Map (specifically routing mode, from Varun's testing).

**Comment by msmollin** [comment]
The LG-D802 appears to be the LG G2, which runs a Qualcomm Snapdragon 800 processor. That same chip is in the Nexus 5, which is @ecgreb's daily driver. I also have one and it doesn't have a problem, so I'm wondering if LG did something specific to their version of Android? I'll see if I can downgrade my N5 to Android 4.4 and do some testing.
