### ISSUE TITLE
Automatically stop nav after arrival (timeout)

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#134]
* **Device name:** Samsung Galaxy S6 edge
* **Android Version:** 5.1.1
* **App build number:** master-481
* **What did you expected to happen?** I arrived at my destination. Turned phone off. Parked, walked into building. Turned my phone back on and it acted like I was still in nav mode.
* **What happened instead?** Nav mode should have ended and I should have been in the basic map browsing app state when the phone turned back on with the app active.
* **Steps to reproduce:** Route to somewhere. Complete the route. Turn phone off. Wait a few minutes. Turn phone back on with Eraser Map app open already or switch back to it.
* **Attach a screenshot** See below.
* **Attach device logs** eh.

If something happened while you were routing, share with us:

* **Where were you?** 273 29th St (San Francisco, California, USA)
* **Routing from origin:** AutoSmog & Oil Changers, San Francisco off Cesar Chavez St.
* **Routing to destination:** 273 29th St (San Francisco, California, USA)

**Comment by nvkelso** [comment]
Seems like it was trying to start a new route from my current location, which was effectively the same as my destination from before?

![screenshot_2015-11-24-15-37-47](https://cloud.githubusercontent.com/assets/853051/11389103/7f3d5550-92f1-11e5-9d8f-4e6f896beb9f.png)

**Comment by souperneon** [comment]
@nvkelso this doesn't happen to me anymore. Can you verify?
