### ISSUE TITLE
Missing route_start and route_end map pins

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#135]
* **Device name:** Samsung Galaxy S6 edge
* **Android Version:** 5.1.1
* **App build number:** master-481
* **What did you expected to happen?** When planning my route from X to Y, I expected to see map pins showing the `route_start` (from X) and `route_end` (to Y) locations.
* **What happened instead?** I only saw the routeline (`route`) and the current location gem (`find_me`). 
* **Steps to reproduce:** Plan a route to somewhere.
* **Attach a screenshot** See below.
* **Attach device logs** eh.

If something happened while you were routing, share with us:

* **Where were you?** AutoSmog & Oil Changers, San Francisco off Cesar Chavez St.
* **Routing from origin:** AutoSmog & Oil Changers, San Francisco off Cesar Chavez St.
* **Routing to destination:** 273 29th St (San Francisco, California, USA)

**Comment by nvkelso** [comment]
These assets were included in the sprite sheet, and styled in the scene file, in yesterday's update – everything else from the update is showing in the app so appears to be an app-level problem (App is probably not setting these ad-hoc layer sources for `route_start` and `route_end`).

![screenshot_2015-11-24-15-28-20](https://cloud.githubusercontent.com/assets/853051/11389180/8027a8ac-92f2-11e5-90fd-fc866881b55a.png)

**Comment by souperneon** [comment]
WHAT HAPPENS NOW:
![](https://lh4.googleusercontent.com/-CejkOIg-zkk/VnA-6FnByjI/AAAAAAAAW98/cB0QFAPwUGs/w671-h1193-no/2015-12-15.jpg)

WHAT SHOULD HAPPEN:
![9](https://cloud.githubusercontent.com/assets/6125224/11816745/e196bbcc-a31f-11e5-9a75-b88952d12a6c.png)


The dark grey pin for start and green pin for destination should appear on this screen. Current location marker can be deprioritized in this view
