### ISSUE TITLE
Current route position arrow is under route path highlight

### ISSUE THREAD

**Issue by dgearhart** [mapzen/eraser-map#138]
* **Device name:** samsung Model: SM-G900V
* **Android Version:** 5.0
* **App build number:** master-481
* **What did you expected to happen?** The current route position arrow to be displayed on top of the route path highlight so user can easily view.
* **What happened instead?** The current route position arrow is under route path highlight and is hard to see - please see the screenshot
* **Steps to reproduce:** Any route
* **Attach a screenshot**
![screenshot_2015-11-25-10-47-07](https://cloud.githubusercontent.com/assets/7515853/11409085/9867dd80-938b-11e5-8d4e-a8cca1b601e2.png)

**Comment by blair1618** [comment]
Relevant issue in tangram-es: https://github.com/tangrams/tangram-es/issues/405

**Comment by tallytalwar** [comment]
https://github.com/tangrams/tangram-es/pull/438, should fix this.

**Comment by tallytalwar** [comment]
This looks good in the build now.
![screenshot_2015-12-17-11-51-19](https://cloud.githubusercontent.com/assets/360641/11875859/bc5c36f2-a4b4-11e5-8dc7-9dc48a426ca4.png)

**Comment by mjcunningham** [comment]
oooOOoooooooooo

**Comment by dgearhart** [comment]
sweet!

**Comment by ecgreb** [comment]
:trophy:
