### ISSUE TITLE
Text to speech goes into bad infinite loop (even when app is force quit)

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#139]
* **Device name:** Samsung Galaxy S6 edge
* **Android Version:** 5.1.1
* **App build number:** master-481
* **What did you expected to happen?** Text to speech should bail when app is force quit. 
* **What happened instead?** The already cued up verbal instructions keep repeating, requiring a hard power down of device.
* **Steps to reproduce:** Plan a route to SF zoo. Park not near where the route told me to end (because it wasn't passable). Walk into zoo. Wonder why phone in pocket is talking after we pay for tickets. Phone is stuck on verbal stutter. 
* **Attach a screenshot** See below.
* **Attach device logs** eh.

If something happened while you were routing, share with us:

* **Where were you?** San Francisco Zoo
* **Routing from origin:** 273 29th St (San Francisco, California, USA)
* **Routing to destination:** San Francisco Zoo

**Comment by nvkelso** [comment]
This happened to several more times on 3 different routes on Friday 27 November 2016.

For example: **Rohnert Park, California** entering a weird parking lot area that wasn't mapped in OSM that was off my current route (we needed to stop to get coffee), and the app really really really wanted us to get back on the highway:

![screenshot_2015-11-27-11-36-08](https://cloud.githubusercontent.com/assets/853051/11493780/0af6520e-97b1-11e5-84a2-fbb68eb041a6.png)

I think it also did this at the Target in Eureka, California (which is more similar to the SF Zoo case first reported). And another time somewhere in the Arcata/Eureka/McKinleyville area.

**Comment by mjcunningham** [comment]
This might be friends with: https://github.com/mapzen/eraser-map/issues/89

**Comment by ecgreb** [comment]
Consolidated into https://github.com/mapzen/eraser-map/issues/213
