### ISSUE TITLE
Search results should show nearby things first

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#141]
* **Device name:** Samsung Galaxy S6 edge
* **Android Version:** 5.1.1
* **App build number:** master-481
* **What did you expected to happen?** I searched for `zoo` and expected to find the San Francisco Zoo to nav to as the top result.
* **What happened instead?** I didn't see the SF Zoo in the first 10 results, so had to fully qualify it as `san francisco zoo` to get that as the top result. We should be seeding search with the current map view so results are more specific. 
* **Steps to reproduce:** Search for `zoo` with current location lat/lng somewhere in SF. 
* **Attach a screenshot** See below.
* **Attach device logs** eh.

If something happened while you were searching, share with us:

* **Where were you?** 273 29th St (San Francisco, California, USA)

**Comment by nvkelso** [comment]
![screenshot_2015-11-25-10-26-24](https://cloud.githubusercontent.com/assets/853051/11412548/0008d442-9393-11e5-8502-deff4e5c27ea.png)
![screenshot_2015-11-25-10-26-10](https://cloud.githubusercontent.com/assets/853051/11412549/00363608-9393-11e5-92b0-37c34756ee3b.png)

**Comment by mjcunningham** [comment]
cc @riordan

**Comment by riordan** [comment]
cc @pelias/owners

We'll look at into it.

**Comment by riordan** [comment]
Tracking on pelias/pelias#183

**Comment by mjcunningham** [comment]
:+1: I'll close this one.
