### ISSUE TITLE
Hard to tell which routing mode I have selected in route picker

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#142]
It took me 5 minutes into my drive to the SF Zoo to realize I got a "bad" route because I had `walking` selected instead of `driving` mode selected in the route picker UX. 

This feels like a regression over the Open app which was more obvious (both with a red bar under the icon, and the badge with the reverse mode glyph as the call to action).

If we do use the black route line, there's also design impact on this route picker screen to keep the colors consistent.

**Comment by nvkelso** [comment]
Eraser Map: 

![screenshot_2015-11-25-16-44-41](https://cloud.githubusercontent.com/assets/853051/11412629/fa096ac4-9393-11e5-8055-85af8f7794af.png)

Open:

![screenshot_2015-11-25-16-44-50](https://cloud.githubusercontent.com/assets/853051/11412628/fa07365a-9393-11e5-9ae8-4fb0638c6ecc.png)

**Comment by souperneon** [comment]
@nvkelso noted. Will find a better solution.
