### ISSUE TITLE
Driving route to SF zoo takes me on no-access road

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#143]
* **Device name:** Samsung Galaxy S6 edge
* **Android Version:** 5.1.1
* **App build number:** master-481
* **What did you expected to happen?** I expected to be taken to the main entrance for the zoo.
* **What happened instead?** I was directed onto a no-access internal zoo road that was nearer to the counterpoint of the zoo landuse AOI, but impassable, and past where the main parking area is. 
* **Steps to reproduce:** Plan a route to SF zoo.
* **Attach a screenshot** See below.
* **Attach device logs** eh.

If something happened while you were routing, share with us:

* **Where were you?** San Francisco Zoo
* **Routing from origin:** 273 29th St (San Francisco, California, USA)
* **Routing to destination:** San Francisco Zoo

**Comment by nvkelso** [comment]
Here's the OSM area: http://www.openstreetmap.org/#map=17/37.73275/-122.50350

It's not clear if the route was expecting me to walk the final distance or not?

**Comment by nvkelso** [comment]
Related: https://github.com/mapzen/eraser-map/issues/140

**Comment by nvkelso** [comment]
![screenshot_2015-11-25-16-44-50](https://cloud.githubusercontent.com/assets/853051/11412741/3d253184-9395-11e5-88dc-a748975b47b5.png)
![screenshot_2015-11-25-16-50-01](https://cloud.githubusercontent.com/assets/853051/11412744/4000a0f0-9395-11e5-9978-50ee4c12eae5.png)
![screenshot_2015-11-25-16-48-28](https://cloud.githubusercontent.com/assets/853051/11412745/4002ed92-9395-11e5-8bf0-e33decf39f32.png)

**Comment by mjcunningham** [comment]
Will track this here along with other parking lot related thoughts: https://github.com/mapzen/eraser-map/issues/151
