### ISSUE TITLE
Disallow creating new route during existing route

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#148]
I often get into situation where I'm engaged in a route (good) and I touch somewhere on the map accidentally and get a screen like the following where the UI prompts me to start a new route to a seemingly random place (bad). This should be disabled. 

Observed 1:

![screenshot_2015-11-27-16-47-55](https://cloud.githubusercontent.com/assets/853051/11492890/c3107d56-97a7-11e5-8592-c86a408899f7.png)

Observed 2:

![screenshot_2015-11-27-10-39-14](https://cloud.githubusercontent.com/assets/853051/11492903/f0bb37aa-97a7-11e5-9de0-be134673b391.png)

Expected (the destination UI at the bottom): 

![screenshot_2015-11-27-12-09-12](https://cloud.githubusercontent.com/assets/853051/11492918/07bdaf5a-97a8-11e5-858f-e739d9c85cd9.png)

**Comment by tallytalwar** [comment]
This might be happening on a long press. 
Long press, reverse geocoding should be disabled in routing mode.

**Comment by nvkelso** [comment]
Another:

![screenshot_2015-11-27-10-30-38](https://cloud.githubusercontent.com/assets/853051/11493051/606f535a-97a9-11e5-99d4-c81f1016c376.png)

**Comment by tallytalwar** [comment]
Similar to https://github.com/mapzen/eraser-map/issues/86. I thought https://github.com/mapzen/eraser-map/pull/127 fixed this issue.

**Comment by ecgreb** [comment]
Confirmed you can initiate reverse geo-code during routing with long press. This should be disabled.
