### ISSUE TITLE
Expired route icons are stuck on screen

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#149]
* **Device name:** Samsung Galaxy S6 edge
* **Android Version:** 5.1.1
* **App build number:** master-481
* **What did you expected to happen?** During navigation I should only see my current location. 
* **What happened instead?** When I zoom out to route overview, I see expired route icons (navigation puck) artwork that are "stuck" on screen.
* **Steps to reproduce:** Navigate from San Francisco to the Target store in Eureka.
* **Attach a screenshot** See below.
* **Attach device logs** eh.

**Comment by nvkelso** [comment]
Here are 4 different screenshots, on two different routes. Happens if the route is paused or if it's active.

In Eureka, Calif. on the way to Target:

![screenshot_2015-11-27-16-07-57](https://cloud.githubusercontent.com/assets/853051/11492995/e01dcb32-97a8-11e5-8ed0-1c9cd0d3db49.png)


In San Francisco headed to Cole Valley (I):
![screenshot_2015-11-27-10-20-17](https://cloud.githubusercontent.com/assets/853051/11492999/e4886f56-97a8-11e5-9b56-78f9cbf36ca1.png)

In San Francisco headed to Cole Valley (II):

![screenshot_2015-11-27-10-15-54](https://cloud.githubusercontent.com/assets/853051/11493005/f2d5ebe2-97a8-11e5-9bbd-b2da11f3caa3.png)

In San Francisco headed to Cole Valley (III):

![screenshot_2015-11-27-10-20-17](https://cloud.githubusercontent.com/assets/853051/11493009/ffdbca50-97a8-11e5-8f3b-310dca8247ad.png)

**Comment by tallytalwar** [comment]
Similar to https://github.com/mapzen/eraser-map/issues/86. I thought https://github.com/mapzen/eraser-map/pull/127 fixed this issue.

**Comment by mjcunningham** [comment]
Being tracked on: https://github.com/mapzen/eraser-map/issues/108
