### ISSUE TITLE
Route icon & map view angle should update more frequently

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#153]
* **Device name:** Samsung Galaxy S6 edge
* **Android Version:** 5.1.1
* **App build number:** master-481
* **What did you expected to happen?** This should be buttery smooth at 60 fps.
* **What happened instead?** I see infrequent route icon (puck) updates, and the camera angle updates at the same or similar (in)frequency. It feels like once every second or two.
* **Steps to reproduce:** Simulate location to SF. Navigate to Eureka, California
* **Attach a screenshot** I should have taken a video.
* **Attach device logs** eh.

If something happened while you were routing, share with us:

* **Where were you?** San Francisco
* **Routing from origin:** San Francisco
* **Routing to destination:** Eureka, California

**Comment by nvkelso** [comment]
Related: https://github.com/mapzen/eraser-map/issues/109

**Comment by ecgreb** [comment]
Currently route icon and map position/rotation update with each GPS location update (1000ms). To make this feel smoother we should start using Tangram interpolation so the transitions are more animated and responsive.

**Comment by blair1618** [comment]
Using "easing" in tangram-es looks like [this](https://github.com/tangrams/tangram-es/blob/master/android/demo/src/com/mapzen/tangram/android/MainActivity.java#L81). For most setters you can just add another argument for a duration (in seconds) and optionally an [ease type](https://github.com/tangrams/tangram-es/blob/master/android/tangram/src/com/mapzen/tangram/MapController.java#L35)

**Comment by nvkelso** [comment]
This is super nice, verified!
