### ISSUE TITLE
Routing has completion issues

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#154]
* **Device name:** Samsung Galaxy S6 edge
* **Android Version:** 5.1.1
* **App build number:** master-481
* **What did you expected to happen?** When I'm near my destination, I should see the final route instruction. 
* **What happened instead?** I only ever see the next to last route maneuver UI cell contents. If I manually swipe over to see the final one, it has a red background.
* **Steps to reproduce:** Simulate location to SF. Search for "eureka california".
* **Attach a screenshot** See below.
* **Attach device logs** eh.

If something happened while you were routing, share with us:

* **Where were you?** Target Eureka, California
* **Routing from origin:** San Francisco
* **Routing to destination:** Target Eureka, California

**Comment by nvkelso** [comment]
This happens on every trip for me, this is just an example.

**Comment by nvkelso** [comment]
![screenshot_2015-11-27-16-11-01](https://cloud.githubusercontent.com/assets/853051/11494052/b3e2ff82-97b3-11e5-888f-44478cdd85da.png)

**Comment by nvkelso** [comment]
Here's another one:

![screenshot_2015-11-27-10-19-03](https://cloud.githubusercontent.com/assets/853051/11494350/85e2399c-97b6-11e5-9baa-aaacd16afa16.png)

**Comment by ecgreb** [comment]
+1
