### ISSUE TITLE
Occasionally the route icon turns into progress indicator

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#155]
* **Device name:** Samsung Galaxy S6 edge
* **Android Version:** 5.1.1
* **App build number:** master-481
* **What did you expected to happen?** I expect to see a current route icon (puck) location, or a recently expired location, or an anticipated puck location if underground and we can guess based on time/speed.
* **What happened instead?** I see a progress indicator and the screen goes dim. 
* **Steps to reproduce:** Plan a route to Eureka Target from San Francisco. During routing I think the GPS got confused? Or something else happened. 
* **Attach a screenshot** See below.
* **Attach device logs** eh.

If something happened while you were routing, share with us:

* **Where were you?** Somewhere north of Santa Rosa, California
* **Routing from origin:** San Francisco
* **Routing to destination:** Target, Eureka, California

**Comment by nvkelso** [comment]
![screenshot_2015-11-27-12-53-57](https://cloud.githubusercontent.com/assets/853051/11494108/19e94642-97b4-11e5-961d-fd0b1bd7635e.png)

**Comment by ecgreb** [comment]
Progress indicator is shown when the route is being recalculated. We should replace current instruction text with "Recalculating..." message to better inform user what is happening.

**Comment by mjcunningham** [comment]
This is a hanging reroute closing.
