### ISSUE TITLE
Occasionally RESUME button covers other UI

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#156]
* **Device name:** Samsung Galaxy S6 edge
* **Android Version:** 5.1.1
* **App build number:** master-481
* **What did you expected to happen?** The resume button should always be offset from other app chrome.
* **What happened instead?** It covered up bottom app chrome.
* **Steps to reproduce:** Plan a route to Eureka Target from San Francisco. Along the way long press somewhere to get a bad in-route route prompt UX.
* **Attach a screenshot** See below.
* **Attach device logs** eh.

If something happened while you were routing, share with us:

* **Where were you?** Somewhere north of San Francisco
* **Routing from origin:** San Francisco
* **Routing to destination:** Target, Eureka, California

**Comment by nvkelso** [comment]
![screenshot_2015-11-27-11-18-30](https://cloud.githubusercontent.com/assets/853051/11494157/8c7f92a6-97b4-11e5-8402-b25bb5c256a6.png)

**Comment by nvkelso** [comment]
Might be related: https://github.com/mapzen/eraser-map/issues/148

**Comment by mjcunningham** [comment]
We are going to overhaul this view. Closing and tracking on new view tickets
