### ISSUE TITLE
Bad destination "address" formatting

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#157]
* **Device name:** Samsung Galaxy S6 edge
* **Android Version:** 5.1.1
* **App build number:** master-481
* **What did you expected to happen?** It should say something more like "Target, Eureka, California"
* **What happened instead?** The route prompt and the route progress cell says "Target, Eureka, CA, Eureka, California".
* **Steps to reproduce:** Plan a route to Eureka Target from San Francisco. There's a [bug](https://github.com/mapzen/eraser-map/issues/152) that doesn't allow searching for that, so search for Eureka, California, Then on the north side of town there's a Target. Long press on that to route there and see the route selection UX prompt.
* **Attach a screenshot** See below.
* **Attach device logs** eh.

If something happened while you were routing, share with us:

* **Where were you?** Somewhere north of San Francisco
* **Routing from origin:** San Francisco
* **Routing to destination:** Target, Eureka, California

**Comment by nvkelso** [comment]
Route status UI:

![screenshot_2015-11-27-11-40-42](https://cloud.githubusercontent.com/assets/853051/11494212/18596edc-97b5-11e5-82b3-4fa0cc51cf2c.png)

Route prompt UI:

![screenshot_2015-11-27-11-35-42](https://cloud.githubusercontent.com/assets/853051/11494222/386d15fc-97b5-11e5-913b-f60ffed13a8b.png)

**Comment by nvkelso** [comment]
In the prompt case, I'd only expect to see:

```
Target
Eureka, California
```

**Comment by ecgreb** [comment]
Fixed by https://github.com/mapzen/eraser-map/pull/144
