### ISSUE TITLE
Not clear how to exit list view (during route & previewing list)

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#158]
* **Device name:** Samsung Galaxy S6 edge
* **Android Version:** 5.1.1
* **App build number:** master-481
* **What did you expected to happen?** There should be a "DONE" button &/or a gesture to dismiss the list view (from active route) and return to the routing experience. From the list preview flow, dismissing is totally broken.
* **What happened instead?** I'm stuck in this list view and don't know how to get back. Eventually I find the "back" Android hardware/software button. I finally figure out I can also gesture down from the TOP part above the list, but not in the list itself. But if I arrived here from the route list preview (from the planning screen), there's no gesture support (they should be equivalent). 
* **Steps to reproduce:** Plan a route to anywhere. Start the route. Drag up from the route status to see the list. ---OR--- Plan a route to anywhere. In the route planning screen press the VIEW LIST button.
* **Attach a screenshot** See below.
* **Attach device logs** eh.

These might be two different issues, split them if that's better for you?

**Comment by nvkelso** [comment]
![screenshot_2015-11-27-10-17-57](https://cloud.githubusercontent.com/assets/853051/11494338/6f3cd8a0-97b6-11e5-8787-5fdb873bde0d.png)

**Comment by ecgreb** [comment]
Full direction list can be dismissed using system back button or with a drag down gesture on the top of the list.

**Comment by ecgreb** [comment]
This screen is going to change when we implement new route mode view designs. Sliding drawer is going away and icon will be provided to toggle between map view and list view.

https://github.com/mapzen/eraser-map/issues/212
