### ISSUE TITLE
Display the "begin street names" prior to the turn and then display the "street names" after the turn

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#159]
* **Device name:** Samsung Galaxy S6 edge
* **Android Version:** 5.1.1
* **App build number:** master-481
* **What did you expected to happen?** CA-1 in San Francisco travels along several named roads. The named roads are the ones signed at intersections. I expect to see the road name (and CA-1) in the routing maneuver text. 
* **What happened instead?** I only see CA-1.
* **Steps to reproduce:** Simulate location to SF near 254 Alma Street. Route to Eureka, California. Take a wrong turn and reconnect with route at Geary Blvd and Park Presidio. Make the turn, get confused at maneuver instructions.
* **Attach a screenshot** See below.
* **Attach device logs** eh.

If something happened while you were routing, share with us:

* **Where were you?** San Francisco
* **Routing from origin:** San Francisco
* **Routing to destination:** Eureka California

**Comment by nvkelso** [comment]
![screenshot_2015-11-27-10-30-38](https://cloud.githubusercontent.com/assets/853051/11494428/2c4e4172-97b7-11e5-9fef-46166767deab.png)

**Comment by nvkelso** [comment]
Without the weird junk at the bottom:

![screenshot_2015-11-27-10-32-07](https://cloud.githubusercontent.com/assets/853051/11494437/3de62512-97b7-11e5-82bd-4b522ef5571e.png)

**Comment by mjcunningham** [comment]
@dgearhart this comes from your end right?

**Comment by dgearhart** [comment]
@mjcunningham the response has "Park Presidio Boulevard" in the "begin street names". Also, the "instruction" and "verbal_pre_transition_instruction" has "Park Presidio Boulevard" - please see below.
The app should display the "begin street names" prior to the turn and then display the "street names" after the turn

REQUEST:
http://valhalla.mapzen.com/route?api_key=YOUR_KEY_HERE&json={%22locations%22:[{%22lat%22:37.762907,%22lon%22:-122.451718,%22type%22:%22break%22},{%22lat%22:37.781437,%22lon%22:-122.457211,%22type%22:%22through%22},{%22lat%22:37.791188,%22lon%22:-122.469818,%22type%22:%22break%22}],%22costing%22:%22auto%22,%22directions_options%22:{%22units%22:%22miles%22}}

RESPONSE snippet:
{
    "end_shape_index": ​98,
    "verbal_pre_transition_instruction": "Turn right onto California 1, Park Presidio Boulevard.",
    "begin_street_names": 
[
    "CA 1",
    "Park Presidio Boulevard"
],
"verbal_transition_alert_instruction": "Turn right onto California 1.",
"length": ​0.759,
"instruction": "Turn right onto CA 1/Park Presidio Boulevard. Continue on CA 1.",
"type": ​10,
"time": ​88,
"verbal_post_transition_instruction": "Continue on California 1 for 8 tenths of a mile.",
"street_names": 
    [
        "CA 1"
    ],
    "begin_shape_index": ​72
},
