### ISSUE TITLE
Search result list button not always cleared (to Settings state)

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#160]
* **Device name:** Samsung Galaxy S6 edge
* **Android Version:** 5.1.1
* **App build number:** master-481
* **What did you expected to happen?** After exiting a route, I expected the three dots button to reappear to access Settings. 
* **What happened instead?** Instead I see the 3 list row Search result button instead. I have to relaunch the app to restore it to the Settings state. If I tap the Search result list button I get a magnifying glass with `""` string and then recent searches listed out. Weird.
* **Steps to reproduce:** Search for somewhere. Route to that somewhere by planning the route and then starting the route. Press the Android hardware/software back button twice to return to route planning, then to exit route planning. 
* **Attach a screenshot** See below.
* **Attach device logs** eh.

If something happened while you were routing, share with us:

* **Where were you?** San Francisco
* **Routing from origin:** San Francisco
* **Routing to destination:** Target Eureka California

**Comment by nvkelso** [comment]
Actual:

![screenshot_2015-11-29-22-06-09](https://cloud.githubusercontent.com/assets/853051/11494716/04360da2-97ba-11e5-838d-0514a430f0f8.png)

Pressing that search result button:

![screenshot_2015-11-29-22-06-12](https://cloud.githubusercontent.com/assets/853051/11494717/0437df9c-97ba-11e5-9a59-4a2a325e1a76.png)

Expected: 

![screenshot_2015-11-29-22-06-32](https://cloud.githubusercontent.com/assets/853051/11494715/0434cbae-97ba-11e5-9816-e670b74a8882.png)

**Comment by ecgreb** [comment]
Fixed by https://github.com/mapzen/eraser-map/pull/147
