### ISSUE TITLE
App stops working when selecting the search bar on build#master-492

### ISSUE THREAD

**Issue by dgearhart** [mapzen/eraser-map#161]
* **Device name:** samsung Model: SM-G900V
* **Android Version:** 5.0
* **App build number:** master-492
* **What did you expected to happen?** When I select the search bar at the top of the app display - I expect the keyboard to appear so I could type in my search request.
* **What happened instead?** The app stopped working
* **Steps to reproduce:** Start app (build#master-492) and select the search bar at the top of the display.

**Comment by msmollin** [comment]
Stack trace from splunk:

https://mint.splunk.com/dashboard/project/b4d64ff6/errors/4492848384

**Comment by ecgreb** [comment]
Did you try uninstalling the current version and re-installing? There was a change in the saved search data format that cause the update to fail.

**Comment by dgearhart** [comment]
@ecgreb it worked after i uninstalled; I have not seen this issue before
