### ISSUE TITLE
Map's max zoom should be 20 (not 18)

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#166]
The WebGL version maxes out at 20, but seems like the Android version only zooms to z18. This is preventing many POIs from displaying (due to collisions, etc).

**Comment by tallytalwar** [comment]
Can we have a tangram-es issue for this?

**Comment by nvkelso** [comment]
WebGL is still max: 20, so we think this is easy in ES to match?

**Comment by blair1618** [comment]
[Voila!](https://github.com/tangrams/tangram-es/commit/621a011ceb608c5d16a57feec042320fffc915fd)

As discussed elsewhere, a better long-term solution will be to implement over-zooming in tangram-es and only fetch tiles up to zoom 18, but for now we'll just fetch new tiles up to zoom 20.
