### ISSUE TITLE
Add debug printout on display for map zoom level

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#167]
It's hard to know what zoom level we're looking at to debug the scene file styling. Not a ship block, but a nice to have. Probably on the Tangram side to enable this, with an app settings toggle?

**Comment by blair1618** [comment]
Will do; I've also wished we had this.

**Comment by tallytalwar** [comment]
API to provide Tangram debugging available here: https://github.com/tangrams/tangram-es/pull/435

@ecgreb Example Usage: https://github.com/tangrams/tangram-es/commit/8713535903d2d746bce4d7acc10f8fc28e3383ba.
I was thinking if we can provide this from the `settings->debugging` view. Same as you have for `mock location` and `mock routing`.

**Comment by tallytalwar** [comment]
tangrams/tangram-es#435 got merged. Available in Tangram `master`.

**Comment by mjcunningham** [comment]
@ecgreb Should we make a new issue to track the client side work for this?

**Comment by mjcunningham** [comment]
Just noticed https://github.com/mapzen/eraser-map/pull/201. Should we archive this one?
