### ISSUE TITLE
Route selection map preview should show entire route

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#172]
* **Device name:** Samsung Galaxy S6 edge
* **Android Version:** 5.1.1
* **App build number:** reproduces on master-518 (originally observed on master-481)
* **What did you expected to happen?** I should see a map of the entire route.
* **What happened instead?** I only see the portion immediately around the destination (the map doesn't refresh to center the entire route line in view once I route to my search result).
* **Steps to reproduce:** Simulate location to Eureka, CA. Search for McKinleyville, Humboldt County, California. Route to the search result. 
* **Attach a screenshot** See below.
* **Attach device logs** eh.

If something happened while you were routing, share with us:

* **Where were you?** Eureka, CA (Target!)
* **Where were going to?** McKinleyville, California
* **Where were leaving from?** Eureka, CA (Target!)

**Comment by nvkelso** [comment]
We didn't have a good looking map for a long time for these types of views, but we do now so let's show it off! :)

**Comment by nvkelso** [comment]
![screenshot_2015-11-27-16-27-52](https://cloud.githubusercontent.com/assets/853051/11620477/2634f686-9c68-11e5-85c2-7b17ce3ddeb3.png)
![screenshot_2015-11-27-16-27-44](https://cloud.githubusercontent.com/assets/853051/11620478/26759d26-9c68-11e5-843e-ee4fc742ff6c.png)

**Comment by souperneon** [comment]
Route line almost never shows up for me in this view. The once or twice it has, it doesn't fit in the view entirely
