### ISSUE TITLE
Call out exit number && road name early before exit

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#173]
* **Device name:** Samsung Galaxy S6 edge
* **Android Version:** 5.1.1
* **App build number:** master-481
* **What did you expected to happen?** I should see both the exit number and the road name well before my exit.
* **What happened instead?** I only 
* **Steps to reproduce:** Simulate location to Eureka, CA. Search for McKinleyville, Humboldt County, California. Route to the search result. Start routing. Near the Murray Road exit I expect to see both take exit 721 and Murray Road. I only saw one of those, and only near the exit. I should have seen them well before the exit.
* **Attach a screenshot** Happened too fast.
* **Attach device logs** eh.

If something happened while you were routing, share with us:

* **Where were you?** Eureka, CA (Target!)
* **Where were going to?** McKinleyville, California
* **Where were leaving from?** Eureka, CA (Target!)

**Comment by ecgreb** [comment]
Currently the app is programmed to announce and display new instructions at 1 mile and 0.25 miles before the maneuver. This does create an edge case of if you are on a leg for less than a mile you won't be notified until you hit the 0.25 mile marker which can be problematic for highways. How long was this leg of the trip?

As for what text is displayed that is coming from the Valhalla response although it is possible we are not displaying the correct field(s) at the correct time.

**Comment by dgearhart** [comment]
The verbal alert gives a short cue. The verbal pre-transition gives more detail
