### ISSUE TITLE
Route preview view list shows SimpleFeature destination

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#174]
* **Device name:** Samsung Galaxy S6 edge
* **Android Version:** 5.1.1
* **App build number:** master-518
* **What did you expected to happen?** I should see my destination in the to/from box above the route maneuver list.
* **What happened instead?** I saw SimpleFeature{id=123} in the destination field instead of my destination street address.
* **Steps to reproduce:** Simulate location to San Francisco. Search for McKinleyville, Humboldt County, California. Route to the search result to preview the route. Tap the View List button.
* **Attach a screenshot** See below.
* **Attach device logs** eh.

**Comment by nvkelso** [comment]
![screenshot_2015-12-06-22-33-26](https://cloud.githubusercontent.com/assets/853051/11620684/056f505c-9c6a-11e5-8bbe-862a207866ab.png)
![screenshot_2015-12-06-22-33-24](https://cloud.githubusercontent.com/assets/853051/11620685/0572d9b6-9c6a-11e5-89d9-0b27980ed18b.png)

**Comment by ecgreb** [comment]
Fixed in #177
