### ISSUE TITLE
Prevent bike and walking routes over max distance

### ISSUE THREAD

**Issue by ecgreb** [mapzen/eraser-map#176]
bike < 300 mi
walk < 150 mi

Routes over max distance for each mode are not supported at this time.

@souperneon what do you think would be the best way to represent this in the UI? Disabled state? Hide icons?

**Comment by msmollin** [comment]
What's doing the prevention? Valhalla?

**Comment by ecgreb** [comment]
Fastest initial implementation would be a hardcoded client-side check.

**Comment by ecgreb** [comment]
Although this does bring up the question are we talking about straight line distance or total route distance for this check? The latter would require a call to the API.

**Comment by mjcunningham** [comment]
What response do we get from Valhalla? I feel like the ideal thing would be to toast a useful error message "Biking over 100 miles is not supported" or something. That way if Valhalla decides to support it the app wont have to do anything.

**Comment by msmollin** [comment]
Agreed with @mjcunningham - either that or some kind of deployable settings file if we wanted to avoid making the network connection in the first place, but normally I tend to err on having less client side cache.

**Comment by souperneon** [comment]
Why aren't we supporting this in the first place?
What @mjcunningham suggests is elegant enough as a message (or we can do something funnier)

**Comment by msmollin** [comment]
<shrugs> I'm told that the current graph that valhalla has implemented for this route types can't negotiate routes longer than these numbers currently. I'd hope that improves in the future but I imagine that's more a Q for the routing team.

**Comment by msmollin** [comment]
In order to implement @mjcunningham's suggestion we'd need sane error messaging back from the valhalla service. @ecgreb do we get something back that we can interpret reliably client-side?
