### ISSUE TITLE
Update icon assets on stylesheet

### ISSUE THREAD

**Issue by souperneon** [mapzen/eraser-map#183]
@nvkelso @sensescape I updated the green and grey a little to up the contrast. See attached the updated icon file.
Also, for the current location gem we need the same transparent white circle behind it like the navigation arrow (updated in the illustrator file)

**Comment by sensescape** [comment]
done

**Comment by nvkelso** [comment]
The current location gem having the transparent white background is on me – the PNG export config we use out of Illustrator needs to be tuned.

**Comment by nvkelso** [comment]
https://github.com/tangrams/eraser-map/issues/24
