### ISSUE TITLE
Tapping compass when view is tilted should untilt map

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#186]
The compass still displays when the map is pointed north but tilted (shoved) so it's more perspective view. That's fine, but tapping the compass icon should "untilt" the view. That finger shove gesture is just funky, and having a single tap button for this will quickly "make the map better again".

**Comment by nvkelso** [comment]
Related: https://github.com/mapzen/eraser-map/issues/182

**Comment by souperneon** [comment]
Mega issue: https://github.com/mapzen/eraser-map/issues/206
