### ISSUE TITLE
Current location (green arrow) icon sometimes flashes like a heartbeat when navigating

### ISSUE THREAD

**Issue by rmglennon** [mapzen/eraser-map#188]
Manufacturer: LGE
Model: Nexus 5X
Release: 6.0
Code name: REL
SDK: 23
Build number: master-535 (note that this is a few builds newer than what I was using, but I don't see any resolved issues since then for this.)

What did you expect to happen?
I expected the arrow to stay a solid color.

What happened instead?
The arrow flashed like a heartbeat, even when I was not moving. It was a little creepy, actually!

Steps to reproduce:
Likely related to this other issue: https://github.com/mapzen/eraser-map/issues/187 (which is a duplicate of https://github.com/mapzen/eraser-map/issues/97)

It was quite noticeable after my route line had problems updating when I chose to take a different route and the route line never updated. As I drove, the green route arrow would flash slowly, about once per second, but there was no black route line under it. It would flash even when I was stopped at a traffic light.

--- 
Update - will test again when this is installed to see if it is actually related. https://github.com/mapzen/eraser-map/pull/185

**Comment by tallytalwar** [comment]
I think this is a known issue (not able to find previously reported issue) and the fix is under review on tangram-es side.

**Comment by tallytalwar** [comment]
Fixed by https://github.com/mapzen/eraser-map/pull/192
