### ISSUE TITLE
No map display while navigating

### ISSUE THREAD

**Issue by zerebubuth** [mapzen/eraser-map#189]
* **Device name:** Samsung Galaxy S3 (GT-I9300)
* **Android Version:** 4.3 (no patch release number shown)
* **App build number:** master-540 (also tested with 0.3.1 with the same result)

* **What did you expected to happen?**  A map to be shown while routing advice was given.
* **What happened instead?**

![screenshot_2015-12-09-16-07-27](https://cloud.githubusercontent.com/assets/271360/11691603/a9f5d7e2-9e93-11e5-8d63-bec304c42cc1.png)

Followed by:

![screenshot_2015-12-09-10-49-51](https://cloud.githubusercontent.com/assets/271360/11691608/b169d5d2-9e93-11e5-8393-dc5735b3a752.png)

The audio guidance worked fine throughout the trip, but the display remained pretty much black.

* **Steps to reproduce:** Allow the app to get a position lock, then route to somewhere (e.g: "Brent Cross Shopping Center"), after pressing the "play" button to advance to the next step, the screen turns mostly black.

* **Where were you?** Approximately here: [51.5801N -0.1307E](http://www.openstreetmap.org/?mlat=51.5801&mlon=-0.1307#map=16/51.5801/-0.1307)
* **Routing from origin:** Same location, [51.5801N -0.1307E](http://www.openstreetmap.org/?mlat=51.5801&mlon=-0.1307#map=16/51.5801/-0.1307)
* **Routing to destination:** Searched for "Brent Cross Shopping Center", approximately [51.57664N -0.22389E](http://www.openstreetmap.org/?mlat=51.57664&mlon=-0.22389#map=17/51.57664/-0.22389)

**Comment by ecgreb** [comment]
Have you seen this bug repeatedly or did it only happen the one time? Also I'm assuming the map was showing before entering routing mode?

So far I have been unable to reproduce.

**Comment by blair1618** [comment]
This smells like a hardware-specific bug to me. We have an S3 at the office, I'll see if I can reproduce this.

**Comment by zerebubuth** [comment]
I've tried a bunch of times with the 0.3.1 release, and I can reliably reproduce this. Connecting it to logcat, all I see is:

```
12-16 12:35:24.850 2357-11732/? E/DatabaseUtils: Writing exception to parcel
12-16 12:35:24.850 2357-11732/? E/DatabaseUtils: java.lang.SecurityException: Permission Denial: get/set setting for user asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL
12-16 12:35:24.850 2357-11732/? E/DatabaseUtils:     at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:13140)
12-16 12:35:24.850 2357-11732/? E/DatabaseUtils:     at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:2038)
12-16 12:35:24.850 2357-11732/? E/DatabaseUtils:     at com.android.providers.settings.SettingsProvider.callFromPackage(SettingsProvider.java:607)
12-16 12:35:24.850 2357-11732/? E/DatabaseUtils:     at android.content.ContentProvider$Transport.call(ContentProvider.java:279)
12-16 12:35:24.850 2357-11732/? E/DatabaseUtils:     at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:273)
12-16 12:35:24.850 2357-11732/? E/DatabaseUtils:     at android.os.Binder.execTransact(Binder.java:388)
12-16 12:35:24.850 2357-11732/? E/DatabaseUtils:     at dalvik.system.NativeStart.run(Native Method)
12-16 12:35:24.850 2357-11732/? W/ActivityManager: Permission Denial: get/set setting for user asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL
```

Which looks unrelated to anything graphics-y, if it's even coming from Eraser Maps at all (could be some background app). I managed to get a GL trace (I think) of when it was transitioning from the destination preview view to the routing view. I'll send that separately. 

I've tried several destinations (Highgate Underground Station, Brent Cross Underground Station, Buckingham Palace, Highgate School, Channing School, Temple Fortune Health Centre), and some of them work and some result in a screen like the screenshots above either at the route preview stage, or when starting to navigate. It's hard to discern any pattern, but I feel like the shorter routes work more often.

Please let me know if there's anything more I can to do help test this issue.

**Comment by ecgreb** [comment]
The stack trace indicates this might be related to permissions. On 4.3 you don't get the WRITE_EXTERNAL_STORAGE permission for free which we use to cache tiles. If this is the case we should be able to reproduce on any device running a version of Android < 4.4.

**Comment by blair1618** [comment]
On our S3 (GT-I9300) over here, which is mysteriously stuck at Android 4.0.4, I can't produce a black screen on routing, but the app reliably crashes shortly after routing starts. There's no mention of permissions in the logcat output. I do, however, get the cryptic
```
I/ActivityManager(  534): Process com.mapzen.erasermap (pid 3714) has died.
```
It approximately coincides with the point when TTS would start in routing, but that may just be coincidence. 

So unfortunately I can't get any further clues about the current issue, but if I can formalize this new incident into an issue I'll do that.
