### ISSUE TITLE
Disabled finger gestures during a long drive/inactivity

### ISSUE THREAD

**Issue by tallytalwar** [mapzen/eraser-map#196]
* Device name: Samsung Galaxy S5
* Android Version: 5.0
* App build number: reproduces on master-569
* SDK: 21

I went on a drive (~60 miles/1.5 hours), and found maybe after about 40 mins that I was not able to perform any gestures (panning, rotation, pinch, etc). However routing was still on and position was being updated constantly.

I was also able to press the `compass` icon and the `resume` icon. But no gestures control.

After another attempt, maybe 20ish minutes, gestures were back and I was able to pan, rotate, pinch, etc.

Route Information:
Start Location: 301 Commons Park S, Stamford, CT 06902
Destination: 350 Knotter Drive, Cheshire, CT

**Comment by mjcunningham** [comment]
@tallytalwar do we think this is still an issue?

**Comment by tallytalwar** [comment]
I was on a longish drive this past weekend and was not able to repro this.
