### ISSUE TITLE
Reroute Instruction looping when on an unmapped street

### ISSUE THREAD

**Issue by tallytalwar** [mapzen/eraser-map#197]
* Device name: Samsung Galaxy S5
* Android Version: 5.0
* App build number: reproduces on master-569
* SDK: 21

Current Location: 670 Mix Avenue, Hamden, CT
http://mapzen.github.io/leaflet-geocoder/#18/41.37161/-72.92729

Destination: 301 Commons Park S, Stamford, CT
alternative Destination: 280 Whitney Avenue, New Haven, CT

Above mentioned location is an apartment complex with some internal roads which are not mapped (as can be seen in the link above).

When I tried to navigate anywhere from this location, navigation went in a loop of the very first instruction, even when I came on the proper route (a mapped street). I had to close the app to stop it.

**Comment by ecgreb** [comment]
Most likely related to #89 and #98.

**Comment by ecgreb** [comment]
Consolidated into https://github.com/mapzen/eraser-map/issues/213
