### ISSUE TITLE
Start and Destination pin icons don't show up in route preview (choose mode) screen

### ISSUE THREAD

**Issue by souperneon** [mapzen/eraser-map#203]
WHAT HAPPENS NOW:
![](https://lh4.googleusercontent.com/-CejkOIg-zkk/VnA-6FnByjI/AAAAAAAAW98/cB0QFAPwUGs/w671-h1193-no/2015-12-15.jpg)

WHAT SHOULD HAPPEN:
![8](https://cloud.githubusercontent.com/assets/6125224/11816567/f9502362-a31e-11e5-8ffd-6a57e0e4420c.png)

The dark grey pin for start and green pin for destination should appear on this screen. Current location marker can be deprioritized in this view

**Comment by ecgreb** [comment]
Duplicated of #135
