### ISSUE TITLE
Current location gem should scale appropriately with zoom level

### ISSUE THREAD

**Issue by souperneon** [mapzen/eraser-map#204]
@ecgreb I can help define this per zoom level if necessary. 
On lower zoom levels (choose mode screen) it looks really really big

![](https://lh4.googleusercontent.com/-CejkOIg-zkk/VnA-6FnByjI/AAAAAAAAW98/cB0QFAPwUGs/w671-h1193-no/2015-12-15.jpg)

**Comment by ecgreb** [comment]
We don't have control over map icon sizes in the app. Can different sizes be specified per zoom level in the stylesheet?

**Comment by tallytalwar** [comment]
Yes, we can provide stops sizes for current location icon in the style sheet, which will make the icon scale accordingly for zoom levels?

Currently we have a fixed size for the current location icon: https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L857

cc. @nvkelso

**Comment by souperneon** [comment]
That would be super sweet if we can do that!
@nvkelso let me know if I can help here

**Comment by souperneon** [comment]
@nvkelso as per our last discussion about this, maybe we should have 2 stops. And define zoom levels that each of those should service. Can we do that in the stylesheet?

**Comment by nvkelso** [comment]
This is a UI icon, I think it should be a constant size – it needs to be instantly recognizable and locatable. 

Looking at a recent build with a zoomed out map at similar zoom (but in SF), I think it's appropriately sized, especially by the time the start and end navigation pins are added in (one overlays the current location gem).
