### ISSUE TITLE
View Direction List doesn't update 

### ISSUE THREAD

**Issue by souperneon** [mapzen/eraser-map#205]
Steps to reproduce:
1. Search for Greenlawn, NY and select from autocomplete
2. Hit 'play' button to choose mode
3. 'Switch' start and end location
4. Tap 'view list' to view driving directions
5. Go back and select 'bike' as the mode
6. "No route found" (@dgearhart @kevinkreiser - not sure why?)
6. Tap 'view list' and it still has the driving directions

![](https://lh4.googleusercontent.com/--vtR55JJTYk/VnBCn_n8H0I/AAAAAAAAW-k/r4uf5n4k5k8/w671-h1193-no/2015-12-15.jpg)

**Comment by mjcunningham** [comment]
Fixed by changing button behavior.
