### ISSUE TITLE
Compass icon behavior

### ISSUE THREAD

**Issue by souperneon** [mapzen/eraser-map#206]
_Edited:_
- Compass icon should not show up on the home screen by default. This is assuming the map is always pointing north when app is loaded
- Compass icon shows up and stays there once the user has rotated the map. Once the icon is tapped (to point north) it fades away _THIS WORKS_
- Compass icon should ALWAYS be visible on the routing screen because the map doesn't stay pointing north at all times

_Old:_
Compass icon shows up on all screens when the user changes the tilt and/or rotation of the default map.
_Exception- On the routing screen, the compass icon is ALWAYS available_

When does the icon show up
1. When user tilts/rotates the view (Home screen, search results screen, choose mode/route preview screen, routing screen)
- Icon fades in
- When user taps the icon, the tilt and rotation is restored to pointing north at the same zoom level the user is at 
- Icon fades out

_Routing screen only_
- The compass icon is always visible and pointing to the appropriate direction user is heading
- Tapping on it once, resets tilt and rotation to point north
- Tapping it again does the same thing restores the tilt and rotation as it were before the user tapped the compass icon

**Comment by sarahlensing** [comment]
This has been resolved.
