### ISSUE TITLE
Map camera jiggles

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#207]
When stopped at a red light I see this a lot, but even a little bit in progress (see video). I don't remember this in earlier builds, this is from master-586.

[gps_jiggle3.mp4.zip](https://github.com/mapzen/android/files/63167/gps_jiggle3.mp4.zip)

**Comment by nvkelso** [comment]
Here's a longer clip:
[gps_jiggle.mp4.zip](https://github.com/mapzen/eraser-map/files/63171/gps_jiggle.mp4.zip)

**Comment by tallytalwar** [comment]
Related: https://github.com/tangrams/tangram-es/issues/466

**Comment by blair1618** [comment]
Fixed: https://github.com/tangrams/tangram-es/pull/467
