### ISSUE TITLE
Tapping search box in master-587 always crashes app

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#208]
Geraldine was experiencing this reliably on her phone Galaxy S6 Edge but different color / carrier) for the last couple weeks of builds, but on my phone I could always search in the same build on my device. 

But now with master-587 I crash 100% of the time when tapping the search box at the top of the app :(

Tapping the top flyout hamburger dots menu to get Settings screen **does** work, though.

**Comment by tallytalwar** [comment]
I think @ecgreb posted this in the Mobile flow:
```
Chuck
Dec 15, 2015 12:12

hey all another breaking change to saved search data was merged yesterday so make sure to uninstall before installing the new build today
```

So if you uninstall the app explicitly and then install it again, it should fix it. It did fix for me.

**Comment by ecgreb** [comment]
@tallytalwar is correct. Uninstalling the current version will fix this issue. We'll have a better process in place for these types of changes post-release.

**Comment by nvkelso** [comment]
I had to uninstall & reinstall twice, but not it works – with less duplicates in the search result list :)
