### ISSUE TITLE
Search bar icons

### ISSUE THREAD

**Issue by ecgreb** [mapzen/eraser-map#210]
Update search icon with new assets. Replace overflow menu with settings icon. Move "Erase History" option into settings menu.

@souperneon can you make a PR with the new toolbar icons?

**Comment by ecgreb** [comment]
![image](https://cloud.githubusercontent.com/assets/464123/11933937/f23757a0-a7cc-11e5-86aa-3202321bad68.png)

**Comment by ecgreb** [comment]
![image](https://cloud.githubusercontent.com/assets/464123/11934040/8eba7972-a7cd-11e5-9ca0-8bb428408f4b.png)

**Comment by souperneon** [comment]
https://github.com/mapzen/eraser-map/pull/217
