### ISSUE TITLE
Style current instruction view in routing mode

### ISSUE THREAD

**Issue by ecgreb** [mapzen/eraser-map#211]
* Update turn icons
* Remove left and right pager control arrows (keeping functionality intact)
* Style distance and street name text
* This issue does not include top bar with total distance and time

(Image 1 - current instruction, Image 2 - previous or next instruction with resume button)

![11a](https://cloud.githubusercontent.com/assets/6125224/11940344/09f5c51a-a7f6-11e5-883a-e70900b7ff28.png)

![image](https://cloud.githubusercontent.com/assets/464123/11878965/a3b95b54-a4c6-11e5-9c4b-a96a786ca039.png)

**Comment by souperneon** [comment]
Additional notes:
- Swiping the current instruction left and right should still work. ONLY HIDE THE ARROWS
-

**Comment by souperneon** [comment]
assets here: https://github.com/mapzen/eraser-map/pull/220 and https://github.com/mapzen/eraser-map/pull/214/files
