### ISSUE TITLE
Move total route distance and time view from bottom to top

### ISSUE THREAD

**Issue by ecgreb** [mapzen/eraser-map#212]
* Replace route footer view with new top bar above directions
* Replace sliding drawer with icon to open list view
* Add drop-down list to view all instructions
* Add exit route "X" icon

![image](https://cloud.githubusercontent.com/assets/464123/11879023/f4cb8ac6-a4c6-11e5-975e-3d92019643d2.png)

![image](https://cloud.githubusercontent.com/assets/464123/11879048/1d33d0e0-a4c7-11e5-9929-9b3941767ab3.png)

**Comment by souperneon** [comment]
Additional UX things:
- Tapping current direction also opens the upcoming list (nice to have)
- List icon acts like a toggle. When the list is open the icon changes to a map
- When the list opens, it only shows upcoming (future) directions and pulling the list down you can see the past directions (it's like the list snaps to the current and upcoming directions)

**Comment by nvkelso** [comment]
+1
