### ISSUE TITLE
Route footer permanently hidden

### ISSUE THREAD

**Issue by ecgreb** [mapzen/eraser-map#215]
* **Device name:** Nexus 5
* **Android Version:** 6.0
* **App build number:** master-592
* **What did you expected to happen?** Route footer appears and map position tracks current location in routing mode.
* **What happened instead?** After successfully completing my first route I searched for a new destination and started a new route. The footer view was permanently hidden and routing mode no longer tracked the route icon.
* **Steps to reproduce:**
1. Search and route to first destination.
2. After completing route use back button to exit routing mode.
3. Search for new destination and begin routing.
4. Route footer is hidden and map position no longer updates automatically.

![image](https://cloud.githubusercontent.com/assets/464123/11940337/03c4501c-a7f6-11e5-9351-3ce1bcc7190d.png)

**Comment by mjcunningham** [comment]
Killing this as this whole view will change.
