### ISSUE TITLE
Different zoom levels for driving/biking/walking

### ISSUE THREAD

**Issue by tallytalwar** [mapzen/eraser-map#225]
Currently we have the same zoom levels for all the 3 navigation options.

Desired Behavior: To have different zoom levels for the 3 options, example, a higher zoom level when in walking navigation mode.

**Comment by ecgreb** [comment]
Related https://github.com/mapzen/eraser-map/issues/169

**Comment by sarahlensing** [comment]
Closing in favor of https://github.com/mapzen/android/issues/402
