### ISSUE TITLE
Enable tapping on search result pins

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#233]
(Was there another issue for this, I don't see it!)

**Comment by mjcunningham** [comment]
@souperneon @sensescape we don't have a notion of an active icon state, correct?

**Comment by tallytalwar** [comment]
By active icon state, do you mean https://github.com/mapzen/eraser-map/issues/133? If so then we have.

**Comment by souperneon** [comment]
@tallytalwar yes it's the same idea. User can swipe left and right in the bottom panel to look at the results or tap individual pins. We are essentially replicating functionality from Open.

**Comment by sensescape** [comment]
Maybe we can also use shaders to adjust the color of the icon on selected state, maybe slightly darken or lighten?

**Comment by souperneon** [comment]
O_O
The grey and green asset should solve for unselected and selected state respectively. I haven't seen that work correctly yet. :(
@sensescape I will never stop you from shaderifying anything :)
