### ISSUE TITLE
Shove gesture never detected on certain Samsung devices

### ISSUE THREAD

**Issue by blair1618** [mapzen/eraser-map#236]
The "two-finger shove" gesture used for tilting is never recognized on certain Samsung devices, including the Galaxy S3, S5, and S6. 

This misbehavior originates in tangram-es and we're working on a fix :\

**Comment by blair1618** [comment]
Fixed: https://github.com/tangrams/tangram-es/commit/1652ca3dcaf48985100fc1f3e3dd1b2931bb0f52

Since we cannot make "shove" and "scale" symmetrically exclusive, it will be possible to start a shove gesture while a scale gesture is in progress. This may be somewhat undesirable behavior, but we should evaluate its impact before investing the time to work around the underlying problem.

**Comment by mjcunningham** [comment]
:+1: lookin good
