### ISSUE TITLE
Add ReserveGeoLoc DataSource

### ISSUE THREAD

**Issue by tallytalwar** [mapzen/eraser-map#243]
Currently reverse geo-location `MapData` uses `search` datasource. Once a new reverseGeoLoc source is available from the style sheet, we can update it to use a new MapData.

Dependent on: https://github.com/tangrams/eraser-map/issues/140

**Comment by nvkelso** [comment]
Stubbed out temp styling expecting source: `reverse_geocode` in https://github.com/tangrams/eraser-map/commit/9f16a72724bfd97b0cc6024b7569fdced133bce6.

**Comment by tallytalwar** [comment]
Nice, I can file a PR for this change today. Thanks
