### ISSUE TITLE
Bring back double tap zoom

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#250]

**Comment by tallytalwar** [comment]
Ah!... I can still do this on the latest build.

**Comment by mjcunningham** [comment]
I got a fresh one this morning and it doesnt seem to work for me.

**Comment by blair1618** [comment]
There might be confusion between two similar gestures here: quickzoom (tap then scale) and double-tap (tap tap). Quickzoom is working for zooming in the current build, but there is currently no response programmed for double-tap. 

It sounds like the desired feature is to zoom the map in by some number of zoom levels towards a point that is double-tapped.

**Comment by tallytalwar** [comment]
Ohh I meant `Quickzoom` is working. Sorry my bad. Thanks @blair1618 for clarifying.

**Comment by mjcunningham** [comment]
@blair1618 that is correct.
