### ISSUE TITLE
ReverseGeocoding messes up previous search result pager view

### ISSUE THREAD

**Issue by tallytalwar** [mapzen/eraser-map#251]
Master Build: 683

1. Search for something, example: "subway"
2. [Works]: Tapping of any search results, correctly centers the view on this and also updates the `SearchResultViewPager` at the bottom.
3. Now do a reverseGeocode by either longPressing or tap on a poi.
4. Now tapping on previous search result pins, does not update the `SearchResultViewPager`, however it does center the map on this tapped search result pin.

**Comment by mjcunningham** [comment]
My first impulse would be to disable reverse in the multi-result view but google has decent implementation. Once you do a reverse you have to hit the back button to get back to the pager view. 

cc @souperneon for thoughts.

**Comment by souperneon** [comment]
I was thinking we keep this open and move it to future, so it's a feature we can flesh out later and have a record of it somewhere
