### ISSUE TITLE
Switching between landscape and portrait view, messed the navigation resume functionality

### ISSUE THREAD

**Issue by tallytalwar** [mapzen/eraser-map#260]
Build: master-688

When switching app between portrait and landscape views, `resume` button stops responding or there is a delayed response when `resume` button is pressed.

**Comment by tallytalwar** [comment]
I think it waits on the next location update, and then moves to the apt position, instead of going to the previous known position.

**Comment by mjcunningham** [comment]
https://github.com/mapzen/eraser-map/issues/275

**Comment by souperneon** [comment]
https://github.com/mapzen/eraser-map/issues/277
