### ISSUE TITLE
Delete or update search cache on installation or update of application if necessary, and notify user

### ISSUE THREAD

**Issue by msmollin** [mapzen/eraser-map#263]
In production we can't expect people to uninstall and reinstall every time there's a data format change for the cache. There's a few ways to approach this as I see it:

- Update the schema of the stored cache
- Delete the cache

In either case, we should be tracking on launch whether or not the new version of the application has been installed, and should prompt the user what's happening.

**Comment by ecgreb** [comment]
Fixed by https://github.com/mapzen/eraser-map/pull/534
