### ISSUE TITLE
Broken roads

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#265]
master-700

In navigation mode, noticing many broken and missing road segments. Zooming in and out reveals them but it seems prevalent in this build

**Comment by tallytalwar** [comment]
@blair1618 can you check this?
Could be because of this: https://github.com/tangrams/tangram-es/pull/487.

Thanks

**Comment by blair1618** [comment]
Yeah that's my bad, I know exactly what happened here - the lines builder
is checking segments against tile edges (only the polygons builder should
care do that).

**Comment by tallytalwar** [comment]
Rebuilding eraser map master build to get this fix from tangram.
