### ISSUE TITLE
Resume button blocks navigation start

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#266]
When you start navigation session, the resume button appears and you need to press it to start

**Comment by souperneon** [comment]
+1 on this bug

**Comment by tallytalwar** [comment]
Can we have repro steps for this?

**Comment by mjcunningham** [comment]
@tallytalwar did @ecgreb talk you through this IRL?

**Comment by tallytalwar** [comment]
Yup, already fixed in #358 :D.

**Comment by mjcunningham** [comment]
:+1:
