### ISSUE TITLE
Disable reverseGeo and poiTapping in route_preview mode.

### ISSUE THREAD

**Issue by tallytalwar** [mapzen/eraser-map#271]

**Comment by kingofirony** [comment]
I don't seem to have this issue. onReverseGeoRequested in MainPresenterImpl would seem to handle this since it confirms the viewstate is default before doing reverse geolocation.

**Comment by tallytalwar** [comment]
2 different ways of reaching route preview:

1. By doing a search and then hitting :arrow_forward: button. This seems to not have the issue, and reverseGeo is disabled!!
2. But if you initiate a route preview via reverseGeo/poiTap you will see this issue.

**Comment by tallytalwar** [comment]
This is also the case in routing mode. I am able to poitap and reverse geocode.
