### ISSUE TITLE
Hitting back in route preview should clear the route

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#276]
Repro:

- Get into route preview
- Back all the way until the app closes
- Re-open the app
- You are trapped

**Comment by tallytalwar** [comment]
I think the steps to repro this are:

1. reverseGeocode and get a location
2. press :arrow_forward: button to go to routing preview
3. reverseGeocode on another location while in routing preview mode
4. try to exit out of routing preview mode

@mjcunningham can you confirm if you did the above sequence?

**Comment by mjcunningham** [comment]
This is something else, you dont need to reverse geocode. 

Just pull up a route preview and try to get out.

**Comment by tallytalwar** [comment]
In that case I can repro this :(.

**Comment by tallytalwar** [comment]
In that case I can not repro this :(.

**Comment by mjcunningham** [comment]
I lied, updated the description for the proper repro.

**Comment by souperneon** [comment]
+1 on this bug. It's definitely broken.

**Comment by tallytalwar** [comment]
@ecgreb I do not think #294 fixes this issue. I can still repro @mjcunningham's instructions in the description of the issue.

**Comment by ecgreb** [comment]
It appears as though fixing this for the reverse geo use case has re-introduced the original issue. Working on it now.
