### ISSUE TITLE
Marker for tapped location should appear immediately

### ISSUE THREAD

**Issue by blair1618** [mapzen/eraser-map#283]
Currently the app waits for the pelias response before placing a marker on the map, which creates a confusing interaction - sometimes I'll think that I mis-tapped on something but actually the app was just waiting for a search response. 

To give feedback for the interaction as quickly as possible, we can place a marker on the map (since we know the location already from tangram), clear the pager (or place a "loading" visual), and then populate the place information whenever the pelias result returns.

**Comment by tallytalwar** [comment]
:+1:
