### ISSUE TITLE
Design cleanup

### ISSUE THREAD

**Issue by ecgreb** [mapzen/eraser-map#284]
* ~~#FFF search bar color~~
* ~~Autocomplete icons (pin and clock)~~
* ~~Style autocomplete list view~~
* ~~Start nav icon~~
* Search pager bounce?
* Interpolate from one result to another on swipe (#344)
* Search results full list toggle (#209)
* Route preview assets
* Reoute preview view list: current location icon and double bar
* ~~Routing move current location arrow lower~~
* ~~Smaller view list and cancel icons in routing mode~~
* Dangling route preview next instruction
* Style resume button
* Icon pressed states
* Can we use right and left destination icons? (#154)
* Mute toggle button above compass. Move compass down.
* Tap current instruction to open list view in routing mode.

**Comment by mjcunningham** [comment]
Closing, this is all in separate tickets now.
