### ISSUE TITLE
Routing Notification Ghosting

### ISSUE THREAD

**Issue by tallytalwar** [mapzen/eraser-map#290]
BUild: master-784

Scrolling notifications, masks/ghosts off part of the routing notification.

Refer to screen shots:

![screenshot_2016-01-30-13-33-31](https://cloud.githubusercontent.com/assets/360641/12721577/8d306c52-c8ce-11e5-9f27-69f2b9e3b638.png)
![screenshot_2016-01-30-13-33-35](https://cloud.githubusercontent.com/assets/360641/12721581/8fd0d988-c8ce-11e5-916f-f860ac524aa9.png)
![screenshot_2016-01-30-13-33-43](https://cloud.githubusercontent.com/assets/360641/12721584/930aea44-c8ce-11e5-8ea3-8b7c53b25f49.png)

**Comment by mjcunningham** [comment]
@ecgreb do unscrollable notifications exist in android?

**Comment by mjcunningham** [comment]
closing and tracking here https://github.com/mapzen/eraser-map/issues/280

**Comment by tallytalwar** [comment]
This also happens with google maps for me.
