### ISSUE TITLE
Routing notification shown when not routing and vice-versa

### ISSUE THREAD

**Issue by tallytalwar** [mapzen/eraser-map#291]
Build: master-784

In some instances, routing notification disappears when still in routing, and in other instances routing notification is still visible when not in routing.

Refer to screenshots and notice the notification bar at the top:
![screenshot_2016-01-30-13-34-17](https://cloud.githubusercontent.com/assets/360641/12721870/e807c066-c8cf-11e5-83e6-e959c0a5fa30.png)

![screenshot_2016-01-30-13-34-31](https://cloud.githubusercontent.com/assets/360641/12721875/f285bcf0-c8cf-11e5-87e3-dafcdf989f4b.png)

![screenshot_2016-01-30-14-13-48](https://cloud.githubusercontent.com/assets/360641/12721900/09e1d5fa-c8d0-11e5-8f6a-67ed192d235d.png)

**Comment by mjcunningham** [comment]
closing and tracking here https://github.com/mapzen/eraser-map/issues/280
