### ISSUE TITLE
Swiping to next maneuver should not update the highlight of the current position in the direction list

### ISSUE THREAD

**Issue by tallytalwar** [mapzen/eraser-map#292]
Build: master-784

In reference to work done for "Route mode view updates Part 2": https://github.com/mapzen/eraser-map/pull/289

Repro:
1. Start a navigation
2. Tap on list view (notice your current position/highlighted position)
3. Back on routing view
4. swipe to next maneuver(s).
5. Go back to direction list and notice the highlighted position.

**Comment by mjcunningham** [comment]
I think this behavior is correct because it is highlighting where your current view is. 

cc @souperneon for thoughts here.

**Comment by souperneon** [comment]
This is a big :) @ecgreb and I talked about it. Two options- we either fix it to keep the highlight on the current active maneuver (not the one you are swiping ahead or back) or we silence this feature before launch. It's super confusing as it is

**Comment by mjcunningham** [comment]
Currently you swipe ahead into a step w a grey background, then when you open the list you see that same step highlighted in the same grey. It sends a consistent signal that the list is reflecting the current state of the view. 

If we fix the behavior we should tweak the UI of the current maneuver in the list view a bit.

**Comment by souperneon** [comment]
The grey highlight in the list was something that @ecgreb implemented to show whats possible. That's not the final design :) I can put a comp here to fix that.

**Comment by mjcunningham** [comment]
:+1:

**Comment by souperneon** [comment]
I believe this is fixed @ecgreb @sarahlensing ?

**Comment by tallytalwar** [comment]
I will keep an eye for this, during this weekend drive(s).

**Comment by tallytalwar** [comment]
I still saw this happen, however, it seems highlight is updated to the correct position on a next maneuver trigger!

**Comment by sarahlensing** [comment]
This has been de-prioritized, lets open a new issue if it is still a problem in the future.
