### ISSUE TITLE
Bring back swipe up (or down) to get to direction list while routing.

### ISSUE THREAD

**Issue by tallytalwar** [mapzen/eraser-map#293]
Build: master-784

In reference to work done for "Route mode view updates Part 2": #289 

I kinda like the old sweeping approach to get to the direction lists, instead of the current implementation of tapping the list button.

**Comment by souperneon** [comment]
@tallytalwar an enhancement yet to come is tapping the current direction to open up the list. Agreed that the list icon is not super obvious right away
