### ISSUE TITLE
"No route found" messes up the View State

### ISSUE THREAD

**Issue by tallytalwar** [mapzen/eraser-map#298]
Trying to a route to a place for which "no route is found", sets the view state to `ROUTE_PREVIEW`, but it should actually back up and set the view state to previous state, `SEARCH_RESULTS`!

**Comment by nvkelso** [comment]
+1, I also experience this.

**Comment by ecgreb** [comment]
Related to #287

**Comment by tallytalwar** [comment]
What should happen:
When a route is not found, then stay in `ROUTE_PREVIEW` mode, but do not draw any route line! However show start and end pins.
