### ISSUE TITLE
X out of search should show map, not recents

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#321]
Similar work around search as just completed for routing...

In master-842 and all recent builds, when I search for something everything works. But when I want to get out of search result mode, I expect tapping on the X in the search bar kills all searching. Instead it brings up a recent search list. I don't expect to see that, instead I only want to see the map.

**Comment by tallytalwar** [comment]
@nvkelso you looking for this: https://github.com/mapzen/eraser-map/pull/317

**Comment by mjcunningham** [comment]
Closing this one as we're chatting about it in https://github.com/mapzen/eraser-map/pull/317

**Comment by nvkelso** [comment]
This really sucks, reopening.

**Comment by nvkelso** [comment]
Same thing with navigation. Cancel the route, then press the hardware back button, then press it again. Not obvious, and not quick.

**Comment by sensescape** [comment]
I have to close the app to get out of search and routing mode every time. Not obvious, and feel stuck when I can't get out of search or routing

**Comment by sarahlensing** [comment]
Closing. This has been resolved in recent builds.
