### ISSUE TITLE
Start and end pins don't clear after exiting navigation

### ISSUE THREAD

**Issue by souperneon** [mapzen/eraser-map#322]
1. search for a place
2. start navigation
3. tap x to cancel
4. Route notification still persists in the drawer
5. Exit navigation from the drawer
6. Go back to the app and hit locate me. Start and end pins are still on the map

![](https://lh6.googleusercontent.com/-vhVsg68yO9A/VrTIdAWy-JI/AAAAAAAAXSU/KNRYUOSKHm0/w671-h1193-no/2016-02-05.jpg)

**Comment by mjcunningham** [comment]
I've seen some odd map behavior starting late yesterday. I couldn't consistently repro any of it but I could occasionally get into states with this, double current location, or no tiles at all.

**Comment by mjcunningham** [comment]
Tracking here: https://github.com/mapzen/eraser-map/issues/452
