### ISSUE TITLE
Double location gem on screen

### ISSUE THREAD

**Issue by souperneon** [mapzen/eraser-map#324]
@tallytalwar says @blair1618 is working on this. Meanwhile I'm finding a way to reproduce :)

![](https://lh6.googleusercontent.com/-jk4tZHtyWMU/VrTIcbyCtiI/AAAAAAAAXSQ/afyuDCntjfs/w671-h1193-no/2016-02-05.jpg)

**Comment by souperneon** [comment]
This hasn't happened to me recently @tallytalwar @blair1618 Should we close and wait to see if anyone else reports?

**Comment by tallytalwar** [comment]
The new approach for rendering markers on map is still on our todo list. Its however not one of the priority items for android-sdk release for tangram-es.

But since we are not able to repro this, its fine to close this. (This is another similar one: #477)

**Comment by mjcunningham** [comment]
Lets close this one.
