### ISSUE TITLE
Search Bar right aligned on Tablets

### ISSUE THREAD

**Issue by msmollin** [mapzen/eraser-map#330]
Device name: Asus Nexus 7 (2013)
Android Version: 6.0.1
App build number: Release 0.4
SDK: 23

The search bar is right aligned on tablets, whereas it should probably be left aligned and fill the whole space like Google Maps.

![screenshot_20160207-090047](https://cloud.githubusercontent.com/assets/1163880/12873848/2092db62-cd96-11e5-8d0d-e2fe57fcc3ef.png)

**Comment by ecgreb** [comment]
Fixed in master
https://github.com/mapzen/eraser-map/pull/317
