### ISSUE TITLE
Long Press Pin not showing when when pressed exactly where geocoded

### ISSUE THREAD

**Issue by msmollin** [mapzen/eraser-map#331]
Device name: Asus Nexus 7 (2013)
Android Version: 6.0.1
App build number: Release 0.4
SDK: 23

Long pressing in or near the correct location for the pin drop regularly does not show the pin. Eventually I got it to show up (and then could no longer reproduce the issue) but then reproduced it for other POIs. The pin would show up if I long pressed any distance away from where the pin should have landed. 

![screenshot_20160207-090307](https://cloud.githubusercontent.com/assets/1163880/12873877/ac6e94b4-cd96-11e5-9eb3-3abe6d2ef4fc.png)
![screenshot_20160207-090328](https://cloud.githubusercontent.com/assets/1163880/12873879/b0f777e4-cd96-11e5-8108-c9a410e0ca14.png)

**Comment by souperneon** [comment]
I thought there was an issue for this? @mjcunningham ?
We had decided at one point that if Search cannot return a result we will just call it "Dropped Pin" in the panel and use the lat/long to route there.  This to me is the second half of the reverse geocoding feature. Though search and autocomplete results have gotten a lot better recently, sometimes just dropping a pin middle of nowhere is necessary (especially coz that is the use case that is nothing in Search for it anyways)

**Comment by ecgreb** [comment]
Fix in progress. Tracking here https://github.com/mapzen/eraser-map/issues/524
