### ISSUE TITLE
Map routing icon not displaying at start of route

### ISSUE THREAD

**Issue by msmollin** [mapzen/eraser-map#332]
Device name: Asus Nexus 7 (2013)
Android Version: 6.0.1
App build number: Release 0.4
SDK: 23

It shows up once you move a bit (including reverse, like when I was backing out of my driveway). I did make sure to allow the Nexus 7 to "warm up" the GPS before routing, so we had good satellite lock.

![screenshot_20160207-103350](https://cloud.githubusercontent.com/assets/1163880/12873895/fa1a2908-cd96-11e5-815f-354485566f3a.png)

![screenshot_20160207-105323](https://cloud.githubusercontent.com/assets/1163880/12873898/231c8314-cd97-11e5-9bc2-7179033a46ad.png)

**Comment by ecgreb** [comment]
Fixed in master
https://github.com/mapzen/eraser-map/pull/325
