### ISSUE TITLE
Eraser Map should limit reverse geocode & search results at least to current country, if not more

### ISSUE THREAD

**Issue by msmollin** [mapzen/eraser-map#335]
Pelias provides a number of filters for reducing search results to be more geographically relevant. When searching for my house which isn't in OSM, I receive results for Vermont, and ultimately wound up accidentally routing to Australia at one point. 

Eraser Map should be able to limit these results using these filters. Thoughts? Are we sending up the location point to Pelias as part of the autocomplete and search payload? Even when entering the zip code (which I was under the impression pelias would use for limiting) I was still receiving these results. Maybe @dianashk / @riordan could expound on this? 

![screenshot_20160207-115154](https://cloud.githubusercontent.com/assets/1163880/12874025/de9cc9b2-cd99-11e5-92a3-c0e85901247f.png)

**Comment by souperneon** [comment]
This is a tough one! If I may…
On mobile it's less likely that user is searching for things that are not routable i.e they are just looking. Mobile seems to be more for taking action. But, I know I have searched for things in India while in conversation with someone. I'd be curious what the search team's thoughts are? @riordan ?

**Comment by dianashk** [comment]
The latest updates (still on dev only) to autocomplete correct this behaviour and aim to surface local things before far away things. It was a bug before. Using the strict filters will prevent users from routing to anything further away than your "deemed-far-enough" distance. It will also prevent the type of activity @souperneon described, where you want to browse a far-away place, probably to settle an argument!

**Comment by ecgreb** [comment]
This should be improved with recent updates to Pelias. I don't think we should be placing any hard limits on search in the app. I'm sure it will continue to improve over time.

If there is a specific issue with address parsing (zip code for example) we should open an issue on Pelias for that.
