### ISSUE TITLE
Add audio ducking capability

### ISSUE THREAD

**Issue by dgearhart** [mapzen/eraser-map#336]
* **Device name:** samsung Model: SM-G900V
* **Android Version:** 5.0
* **App build number:** master-792
* **What did you expected to happen?** When using my phone for listening to music and navigation for a trip - I expect that the music volume is lowered when a navigation command is given and then the music volume returned to same level after the guidance command. This is the audio ducking capability that other nav apps implement.
* **What happened instead?** The music volume remained constant and the navigation command could not be heard.
* **Steps to reproduce:** Play music on phone while using eraser map in nav mode.

**Comment by msmollin** [comment]
![image](https://cloud.githubusercontent.com/assets/1163880/12929458/ccb9907e-cf40-11e5-9fb0-bf391a06972b.jpg)

**Comment by dgearhart** [comment]
@msmollin perfect
