### ISSUE TITLE
Dynamic zoom at transition

### ISSUE THREAD

**Issue by dgearhart** [mapzen/eraser-map#339]
* **Device name:** samsung Model: SM-G900V
* **Android Version:** 5.0
* **App build number:** master-792
* **What did you expected to happen?** Dynamic zoom at transition based on length of maneuver. Have the current zoom level when at a transition point but when the user enters a long maneuver (such as on a highway) then have the app zoom out to give the user more context of surroundings.
* **What happened instead?** Static zoom - seems too zoomed in for long aneuvers
* **Steps to reproduce:** A route with long maneuvers (> 2 miles long)

**Comment by tallytalwar** [comment]
:+1: , I also feel zoom 18 is probably too zoomed in for long drives.

**Comment by mjcunningham** [comment]
@dgearhart Interesting, this is something we did by current speed in Open but that was always a little weird. How would it work for the end of the long maneuver? I feel like a few miles before an exit it should zoom back in.

**Comment by dgearhart** [comment]
@mjcunningham yes - probably timing with the verbal cues at the end of long maneuver - zooming back in so user can see specific details near transition
