### ISSUE TITLE
Disable touch gestures on mapView when performing gestures on route status at the very top.

### ISSUE THREAD

**Issue by tallytalwar** [mapzen/eraser-map#342]
Build: master-859

Or in other words "route status" bar should grab all gestures happening on it, and not pass it to mapView (tangram).

![screenshot_2016-02-08-14-41-03](https://cloud.githubusercontent.com/assets/360641/12896986/ed66452a-ce72-11e5-9f9d-0703b2bc772e.png)

**Comment by souperneon** [comment]
@mjcunningham this seems pretty important. We should fix it
