### ISSUE TITLE
Add mute button to routing mode

### ISSUE THREAD

**Issue by ecgreb** [mapzen/eraser-map#345]
![image](https://cloud.githubusercontent.com/assets/464123/12899306/a611bc5c-ce7e-11e5-8826-ac8be497322f.png)

**Comment by ecgreb** [comment]
Assets here https://github.com/mapzen/eraser-map/pull/219

**Comment by ecgreb** [comment]
Compass should be displayed below mute button.

**Comment by souperneon** [comment]
There are two states for the asset. The press state we are using is the default android scaling circle contained in that square button
