### ISSUE TITLE
Route disappears in route preview

### ISSUE THREAD

**Issue by tallytalwar** [mapzen/eraser-map#367]
Build: master-894

Repro:
- Start a route to say "Burbank, CA"
- Switch from driving to walking (no route found, and erases the route, which is perfect)
- now switch back to driving mode, route is not redrawn.

**Comment by souperneon** [comment]
I had the same thing happen to me when i was switching between modes in India

**Comment by mjcunningham** [comment]
@tallytalwar Can you still repro this? I jsut tried it to New Orleans and it seems to work.

**Comment by tallytalwar** [comment]
Still can repro this issue.
Just tried the repro steps I have in the initial comment.

**Comment by mjcunningham** [comment]
Hmmm it works for me but the route takes a while. Maybe it's timing out sometimes? Are you on WIFi?

**Comment by tallytalwar** [comment]
Yup WiFi.

**Comment by tallytalwar** [comment]
Wait wait ... it worked for me now. Yes it took some time. (Maybe I was not waiting long enough and exiting the view).

**Comment by mjcunningham** [comment]
OK, I'll close this and open something else for a visual hint that the route is taking a while.
