### ISSUE TITLE
Enable tracking on current location button tap

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#372]
Many mapping apps enable "tracking" when the current location button is tapped (and indicate this by keeping the tapped "active" state of the button on), but we do not. 

Tracking keeps the current location gem centered on screen and updates the map display as the customer's location changes (often during walking or driving). 

Currently when the "show current location" button is tapped in `master-907`, it centers the view at a set zoom only (even if the current location is in the current map view it resets the zoom instead of panning).

Instead if the current map view zoom is greater than the default "current location button" zoom, it should keep the current map view zoom and pan to the current location.

Related:

* https://github.com/mapzen/eraser-map/issues/109
* https://github.com/mapzen/eraser-map/issues/230

**Comment by nvkelso** [comment]
Current behavior. When locate me button tapped, the map zooms to a default zoom and pans to the current GPS location. 

![current_location_default](https://cloud.githubusercontent.com/assets/853051/13061794/761a7bd2-d3f7-11e5-993e-80d2e5fefaba.png)

That's not super detailed for walking around, so I zoom in. If I zoom in on current location, then tracking should stay enabled.

![current_location_zoomed_in](https://cloud.githubusercontent.com/assets/853051/13061885/edf62ab6-d3f7-11e5-832b-1c008ce68cb4.png)

When I move to a new location down the road from when I first enabled tracking,  the map should move with me at that zoomed in view.

![new_location_expected](https://cloud.githubusercontent.com/assets/853051/13061795/761d876e-d3f7-11e5-9718-6f9873924f47.png)

Instead I have to manually locate myself by pressing the button, and it's zoomed out. 

![new_location_default](https://cloud.githubusercontent.com/assets/853051/13061796/761edd8a-d3f7-11e5-9070-b6dc670d3afe.png)

**Comment by souperneon** [comment]
This is done. There will be another ticket for tracking and keeping the dot in the center of the screen
