### ISSUE TITLE
Data attribution needs to be more than OSM

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#378]
We use other data besides OpenStreetMap that requires attribution. There's too many to include on the map itself, it's probably better to include this in the settings area. It could even be a link out to a HTML page somewhere (like Apple does).

* https://github.com/pelias/pelias-doc/blob/master/data-sources.md
* https://github.com/mapzen/vector-datasource/blob/master/docs/attribution.md

The fuller list should be something more like:

```
© OpenStreetMap contributors, Who's On First, Quattroshapes, 
OpenAddresses, Geonames, Natural Earth, and openstreetmapdata.com
```

But needs to include links back to most the project's individual license / about pages to be in compliance.

**Comment by mjcunningham** [comment]
Cool, but what should go on the map?

 There was a long discussion over here but it seems like the OSM requirement is that it has to be on the map. https://github.com/mapzen/eraser-map/issues/117

**Comment by mjcunningham** [comment]
cc @bcamper for thoughts. 

Maybe "Map Data © OSM +" ? That seems kinda weird.

**Comment by mjcunningham** [comment]
Closing this and tracking here: https://github.com/mapzen/blog/issues/827
