### ISSUE TITLE
Add correct links to settings menu

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#380]
- [ ] Privacy
- [ ] Terms
- [ ] Data sources
- [ ] Contact 
- [ ] Learn more?

**Comment by mjcunningham** [comment]
Data sources work tracked here: https://github.com/mapzen/blog/issues/827

**Comment by souperneon** [comment]
Is this in addition to the stuff that is already in the settings menu?

**Comment by mjcunningham** [comment]
Si
