### ISSUE TITLE
High res icon

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#383]
512 x 512
32-bit PNG (with alpha)

**Comment by souperneon** [comment]
![em_appicon_512](https://cloud.githubusercontent.com/assets/6125224/13125794/6c402202-d595-11e5-9966-5881c6ddf1c5.png)
![em_appicon_512a](https://cloud.githubusercontent.com/assets/6125224/13125795/6c41977c-d595-11e5-81c5-13f5c96652d2.png)

**Comment by souperneon** [comment]
like that?

**Comment by mjcunningham** [comment]
It's what they want in the app store interface.

@ecgreb this is just for displaying in the app store right?

**Comment by ecgreb** [comment]
Right. For the store we should probably use the one without a drop shadow.

**Comment by mjcunningham** [comment]
Done
