### ISSUE TITLE
North South routes get cut off.

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#386]
![screenshot_2016-02-18-18-07-37](https://cloud.githubusercontent.com/assets/307758/13161380/45eb14aa-d66b-11e5-86fa-933c53d53076.png)

**Comment by blair1618** [comment]
I think this is my bad - the route is scaled to fit within the map view, but the calculation doesn't have any information about the other views that might cover parts of the map. The first solution that comes to mind is to fit the route into a square in the middle of the screen whose side length is the screen's smallest dimension. I'll take a swing at it.

**Comment by mjcunningham** [comment]
Would that work for landscape?

**Comment by mjcunningham** [comment]
Ah, nevermind I get it. Give it a shot.
