### ISSUE TITLE
Tilt navigation camera to 55°

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#399]
It'd be nice to see a little more detail (several blocks, not a couple blocks) during navigation. This also brings us into alignment with most other navigation apps (which have a longer view).

Camera tilt is around 48° now, **going to 55° looks better**. 

To test this, I used Tangram debug options in a recent build.

**Comment by tallytalwar** [comment]
I think other apps are also at a lower zoom level... We are at 18z.

**Comment by mjcunningham** [comment]
@nvkelso any thoughts on the zoom? we can do it all in one swoop.

**Comment by blair1618** [comment]
Since https://github.com/mapzen/eraser-map/pull/404 will also impact zoom during navigation, we may not want to modify too many variables at once here.
