### ISSUE TITLE
On screen rotation, voice prompts during nav abruptly stop

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#408]
* **Device name:** Samsung Galaxy S6 edge
* **Android Version:** 5.1.1
* **App build number:** master-988
* **What did you expected to happen?** Voice prompts during navigation should take me all the way to my destination.
* **What happened instead?** The moment I rotate my phone to horizontal from vertical, the voice prompt will cut off mid-word and never resume for the duration of the trip. Toggling the mute button has no effect. But stopping the route and restarting it will restore it.
* **Steps to reproduce:** Route to somewhere. Start navigating. After the first couple voice prompts, rotate your phone from vertical to horizontal. No more voice prompts after that.
* **Attach a screenshot** n/a
* **Attach device logs** n/a

If something happened while you were routing, share with us:

* **Where were you?** Near San Jose and I-280 in SF
* **Routing from origin:** 273A 29th St SF CA 94131
* **Routing to destination:** San Francisco State University

I've replicated this across several drives, using the master-97x series and master-98x series.

**Comment by dgearhart** [comment]
Happened to me several times
