### ISSUE TITLE
Horizontal route planning view is broken

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#410]
- **Device name:** Samsung Galaxy S6 edge
- **Android Version:** 5.1.1
- **App build number:** master-988
- **What did you expected to happen?** I expected to see a route preview.
- **What happened instead?** I only saw UI chrome, no map.
- **Steps to reproduce:** Tilt the route planning screen from vertical to horizontal.
- **Attach a screenshot**
- **Attach device logs**

Options:
1. Redesign the routing screen for horizontal orientation.
2. Limit route planning to vertical orientation only (but still allow horizontal once navigation has been started).

My preference is option 2.

**Comment by nvkelso** [comment]
![screenshot_2016-02-24-21-28-23](https://cloud.githubusercontent.com/assets/853051/13310816/47504040-db3e-11e5-967b-43a3c6e8da3b.png)

![screenshot_2016-02-24-21-28-18](https://cloud.githubusercontent.com/assets/853051/13310815/47340bf0-db3e-11e5-972a-3125633b5e4b.png)

**Comment by mjcunningham** [comment]
cc @blair1618 I'm guessing this has something to do with your recent work

**Comment by blair1618** [comment]
@mjcunningham Mmmm not exactly, I don't think there's any way we could fit a usable route preview into the space available between UI elements in the horizontal orientation here. I'm with @nvkelso that we should just disallow switching to a horizontal orientation during route preview.

**Comment by souperneon** [comment]
I am ok with not allowing horizontal till we finish making design updates for this view. I believe we had a trello ticket with comps in it which got lost

**Comment by souperneon** [comment]
Let's disable horizontal view for choose mode

**Comment by ecgreb** [comment]
Its not possible to disable rotation and a per-view basis. The proper fix here is to update the layout for route preview landscape mode.

This is the only route preview design ticket I found in the Trello archives but it does not contain landscape mockups.

https://trello.com/c/C1VV7iAE/825-choose-mode

**Comment by sarahlensing** [comment]
We have made improvements to this UI. Lets open a new ticket for any issues with the new design
