### ISSUE TITLE
Call to start navigation is confusing with mode picker

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#412]
The call to action around **Start Navigation** during route planning should be more obvious. 

The placement of the **Start Navigation** element on the bottom makes sense, but it's association with the travel **mode switcher** (car, bike, walk), which takes up a larger amount of space and is probably less used than "Start", confuses the purpose of the bottom button area. Most other navigation apps place the mode switcher up with the route TO, FROM, VIA (mode) above the map.

* **Device name:** Samsung Galaxy S6 edge
* **Android Version:** 5.1.1
* **App build number:** master-988

![screenshot_2016-02-24-21-28-18](https://cloud.githubusercontent.com/assets/853051/13310929/22847abe-db3f-11e5-8f96-1a2a27aa5d76.png)

**Comment by nvkelso** [comment]
Something more like this?

![route_planning_screen](https://cloud.githubusercontent.com/assets/853051/13324296/dd17cd98-db91-11e5-8543-7be62cca3676.png)

**Comment by souperneon** [comment]
You are right that _most_ apps do it that way. I'd like to hear from external beta testers or watch people use. Keeping the mode close to the time/distance and start if to combine decision making things in one place. I personally think that the distance and mode and start button seem disjointed in other apps. Let's wait and listen :)

**Comment by souperneon** [comment]
@nvkelso in the current version they look more like buttons. Does that help?

I am still going to tweak the choose mode buttons. They look too close together

**Comment by mjcunningham** [comment]
I believe @nvkelso told me IRL he liked the new buttons. 

Closing.
