### ISSUE TITLE
Current location is off screen in driving mode

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#423]
Flip btwn portrait and landscape. App will put your current location out of view.

**Comment by dgearhart** [comment]
off screen for me too

![screenshot_2016-02-29-07-51-46](https://cloud.githubusercontent.com/assets/7515853/13396698/11939806-dec4-11e5-829e-8ff2c6721136.png)

![screenshot_2016-02-29-08-19-17](https://cloud.githubusercontent.com/assets/7515853/13396705/1b27b398-dec4-11e5-8a75-c553a0357b62.png)

![screenshot_2016-02-29-08-19-40](https://cloud.githubusercontent.com/assets/7515853/13396712/2239ad44-dec4-11e5-98c0-59059476a17b.png)
