### ISSUE TITLE
Disable locate-me/current-location/find-me in route preview

### ISSUE THREAD

**Issue by tallytalwar** [mapzen/eraser-map#425]
* **Device name:** Samsung Galaxy S5
* **Android Version:** 5.0
* **App build number:** master-1048
* **What did you expected to happen?** Not see locate me icon in route-preview.
* **What happened instead?** In a normal route-preview, "locate-me" icon is occluded by the route preview ui, but when no route is found, "locate-me" icon is visible (partially) underneath the UI.
* **Steps to reproduce:** Navigate to a location which is not routable.
* **Attach a screenshot**
![screenshot_2016-02-29-10-15-48](https://cloud.githubusercontent.com/assets/360641/13398821/24db95bc-dece-11e5-8567-da7f505396b2.png)

**Comment by ecgreb** [comment]
After testing this out I think we should be **disabling** rather than **hiding** the view route and start route buttons. That would fix this issue since the locate button would be fully covered up by the choose mode view (as before).

**Comment by tallytalwar** [comment]
:+1:

**Comment by sarahlensing** [comment]
![screenshot_2016-02-29-13-43-59](https://cloud.githubusercontent.com/assets/494323/13405654/87687640-deed-11e5-9e09-c758651a8ba4.png)
