### ISSUE TITLE
Hide "resume" button in route list view

### ISSUE THREAD

**Issue by tallytalwar** [mapzen/eraser-map#427]
* **Device name:** Samsung Galaxy S5
* **Android Version:** 5.0
* **App build number:** master-1048
* **What did you expected to happen?** "resume" button be hidden when I go to route list view (and again visible when I exit the route list view to enter routing/navigating view)
* **What happened instead?** "resume" button persists in route list view.
* **Steps to reproduce:** Start a route, pan around to make resume button visible, then enter the route list view.
* **Attach a screenshot**
![screenshot_2016-02-29-10-31-33](https://cloud.githubusercontent.com/assets/360641/13399215/2a5a76b4-ded0-11e5-860c-b213e69afd0d.png)

**Comment by souperneon** [comment]
I guess there are two ways to make this bug happen. Thanks for marking it @tallytalwar
