### ISSUE TITLE
add DNT header to all API requests

### ISSUE THREAD

**Issue by baldur** [mapzen/eraser-map#428]
This is how we know to drop the logs from Eraser map requests

**Comment by ecgreb** [comment]
Example use:

`curl -H "DNT=1" http://vector.mapzen.com/x.vtm`

We can add this header to Pelias and Valhalla requests made from the app no problem.

@blair1618 we will need some assistance from Tangram to add this header to tiles requests. Maybe add a facility to the [`HttpHandler`](https://github.com/tangrams/tangram-es/blob/master/android/tangram/src/com/mapzen/tangram/HttpHandler.java) to set additional headers?

**Comment by blair1618** [comment]
OkHTTP has a rather simple [interface](http://square.github.io/okhttp/3.x/okhttp/okhttp3/Request.Builder.html#addHeader-java.lang.String-java.lang.String-) for adding headers to HTTP requests. We can make this available by just changing the access type of `okRequestBuilder` in `HttpHandler` from `private` to `protected` - then you could add a header to the request builder in an overridden constructor, e.g.
```java
new HttpHandler() {
    @Override
    public HttpHandler() {
        super();
        okRequestBuilder.addHeader(headerName, headerValue);
    }
}
```
