### ISSUE TITLE
Switching between list an map exits search

### ISSUE THREAD

**Issue by ecgreb** [mapzen/eraser-map#432]
Steps to reproduce:

1. Enter pizza in search text box and click search button on soft keyboard.
2. Click on view list action icon to enter search results list view.
3. Click on map action icon to return to map view.

Instead of showing current search results on the map search is exited and query text is cleared.

**Comment by sarahlensing** [comment]
Closed by: https://github.com/pelias/pelias-android-sdk/pull/37
