### ISSUE TITLE
Zoom out more in routing mode

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#444]
Let's push the zoom out a little more, screens attached. We should also adjust the long maneuver zoom out accordingly. 

Current zoom:
![screenshot_2016-03-02-11-34-24](https://cloud.githubusercontent.com/assets/307758/13467369/f218b872-e06b-11e5-8237-590e95c13f82.png)

Proposed zoom: (so you can see Park Ave from a route starting at the office)
![screenshot_2016-03-02-11-35-02](https://cloud.githubusercontent.com/assets/307758/13467375/fa3c2674-e06b-11e5-8e52-1eabadfbc258.png)

**Comment by tallytalwar** [comment]
:+1:
