### ISSUE TITLE
Are we sending reroute requests before we are done receiving them?

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#450]
During the road test we noticed the app being overly chatty while rerouting when it was about to start a maneuver. It seemed like several sets of instructions were getting backed up and then coming out in succession. A proposed theory was we sending reroute requests before we are done receiving them. This ticket is to investigate that theory.

**Comment by dgearhart** [comment]
I also heard duplicated call outs when there was not a reroute. Sometimes it repeats the same command - seems like it did not realize that the command was already called out
