### ISSUE TITLE
Route start/ end pins are occasionally not cleared off the map after a route finishes.

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#452]

**Comment by sarahlensing** [comment]
having trouble repro'ing this

**Comment by tallytalwar** [comment]
Might have been fixed by https://github.com/mapzen/eraser-map/pull/487

**Comment by sarahlensing** [comment]
Thats what I'm thinking too.

I also tried to find a situation where we showed the pins without clearing them and couldnt

**Comment by ecgreb** [comment]
Closing for now and we can reopen if we see more instances of this issue.
