### ISSUE TITLE
Remove verbal alert from 'Merge maneuver' when not sent from service

### ISSUE THREAD

**Issue by dgearhart** [mapzen/eraser-map#460]
* **Device name:** samsung Model: SM-G900V
* **Android Version:** 5.0
* **App build number:** master-1228
* **What did you expected to happen?** That no verbal alert instruction will be given for 'Merge maneuvers' on short ramps (< 1.5 km)
* **What happened instead?** The service was updated on 3/7 to not send the 'Merge maneuver' verbal alert instruction on short ramps - however, the app is calling out: "In a 1/4 mile" with no distance
* **Steps to reproduce:** Any merge maneuver with prior short ramp

**Comment by dgearhart** [comment]
Just to clarify - the issue was to remove the Merge verbal alert instruction when not returned from the service. The merge verbal pre-transition instruction should still be called out. Does that make sense?

**Comment by dgearhart** [comment]
@sarahlensing ^^

**Comment by sarahlensing** [comment]
@dgearhart (or @ecgreb  ?) how do i know when it is not returned from the service? from what ive been able to see, i cant find anywhere where we are adding a merge verbal alert

**Comment by ecgreb** [comment]
In the app we we prepend some distance text to the verbal alert. For example: "In a quarter mile...".

When Valhalla does not return a verbal alert for short maneuvers, we should not announce the distance text. Basically we need to skip the verbal alert only if its empty in the Valhalla response.

**Comment by sarahlensing** [comment]
ohh! this is crystal clear now. thanks!
