### ISSUE TITLE
Route line too thick and causing weirdness on high zooms

### ISSUE THREAD

**Issue by souperneon** [mapzen/eraser-map#464]
* **Device name:** 
Samsung Galaxy S6 edge
* **Android Version:** 
5.1.1
* **App build number:**
master-1236
* **What did you expected to happen?** 
Route line should be a proper line
* **What happened instead?**
It had weird shapes
* **Steps to reproduce:**
search for a short route which has the choose mode screen at a high zoom level
* **Attach a screenshot**
![](https://lh4.googleusercontent.com/-6GLlISYwRZU/VuBHS7wtBKI/AAAAAAAAABw/0rgim1QZ-PM/w671-h1193-no/2016-03-09.jpg)
* **Attach device logs**

**Comment by ecgreb** [comment]
Route line thickness is a function of the stylesheet. If still present please open an issue here https://github.com/tangrams/bubble-wrap
