### ISSUE TITLE
 Start Navigation and View List button styling

### ISSUE THREAD

**Issue by souperneon** [mapzen/eraser-map#468]
Ideally:
![screen shot 2016-03-09 at 5 36 54 pm](https://cloud.githubusercontent.com/assets/6125224/13653092/afe21220-e61d-11e5-9631-846671eeddbe.png)

If not, then this:
![screen shot 2016-03-09 at 5 37 49 pm](https://cloud.githubusercontent.com/assets/6125224/13653108/b90502fe-e61d-11e5-8033-818c530d5fb2.png)

**Comment by mjcunningham** [comment]
Fixed
