### ISSUE TITLE
Swiping ahead and then back to current instruction doesn't update map and nav arrow position

### ISSUE THREAD

**Issue by souperneon** [mapzen/eraser-map#473]
* **Device name:** 
* **Android Version:** 
* **App build number:**
Beta build from Google Play on March 10th
* **What did you expected to happen?** 
Swipe ahead to look at future instructions in the top panel and swipe back to current instruction restores the nav arrow to where I am on the road
* **What happened instead?**
The map position did not adjust and seemed to be in a random spot. Had to hit the 'resume' button to get back
* **Steps to reproduce:**
While driving, swipe the instructions forward
Swipe back to current instruction
Check map position and nav arrow 
* **Attach a screenshot**
* **Attach device logs**

If something happened while you were routing, share with us:

* **Where were you?**
* **Routing from origin:**
* **Routing to destination:**

If something happened while you were searching, share with us:

* **Where were you?**

**Comment by sarahlensing** [comment]
This was fixed by this commit: https://github.com/mapzen/eraser-map/commit/39c097898f5dd7f08412deb27bd904f8a870258b
