### ISSUE TITLE
Old routing pins left on map

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#477]

**Comment by mjcunningham** [comment]
![screenshot_2016-03-11-11-05-41](https://cloud.githubusercontent.com/assets/307758/13707782/55da82a0-e779-11e5-8a44-e7aed53bcf46.png)

**Comment by tallytalwar** [comment]
Will good to have repro instructions for this.

**Comment by mjcunningham** [comment]
@tallytalwar I was able to get it into a state where it would never clear the pins a few times but I cant repro it now...

I'll leave this open and keep trying to figure it out.

**Comment by tallytalwar** [comment]
I think I might have a repro on this: 

1. Search for anywhere
2. Go to route preview
3. switch from portrait to landscape or vice-versa
4. exit back to default view
5.wallah!! you will see you routing pins :D

**Comment by mjcunningham** [comment]
:+1:
