### ISSUE TITLE
typing numbers brings up weird autocomplete results

### ISSUE THREAD

**Issue by souperneon** [mapzen/eraser-map#479]
![](https://lh4.googleusercontent.com/-vj4r1WruisE/VuLtWGALLRI/AAAAAAAAXZ0/p1MIUc8DUBk/w622-h1106-no/2016-03-11.jpg)

* **Device name:** 
* **Android Version:** 
* **App build number:**
Beta Google Play store build

If something happened while you were searching, share with us:
Started typing a number into the search bar and started giving weird autocomplete results
* **Where were you?**
In the NY office

@dianashk have you guys seen this one before?

**Comment by tallytalwar** [comment]
On similar lines suggested search results when searching for our office address "30 W 26", first result comes up as "30 West 26th Street, Merced, CA", and second result as "30 West 26th Street, Manhattan, NY".

**Comment by dianashk** [comment]
Haven't seen the behavior pointed out by @souperneon. Will investigate. We've seen the Merced result creep up to the top and will triage it in the near future. Thanks.

**Comment by mjcunningham** [comment]
Thanks @dianashk!  If it seems like a real thing link your issue here and we'll close this one.

**Comment by rmglennon** [comment]
Some characters don't display for me at, but I assume this is still the long-standing encoding problem with certain source data?

For example, in San Francisco, starting to type Daly (for Daly City, the town just to the south...as you all know from my other search submissions :wink:), I see boxes for special characters in the autocomplete list and in the destination if I tap one as the result.

![image](https://cloud.githubusercontent.com/assets/4380498/13797198/ffc11228-eac8-11e5-9ce9-72cd34ef6907.png)

**Comment by ecgreb** [comment]
Closing in favor of https://github.com/pelias/pelias/issues/280
