### ISSUE TITLE
Take speed into account for location updates

### ISSUE THREAD

**Issue by sarahlensing** [mapzen/eraser-map#482]
- **Device name:** 
  Galaxy S6 Edge
- **Android Version:** 
  5.1.1
- **App build number:**
  0.7-SNAPSHOT
- **What did you expected to happen?** 
  My location icon to update frequently enough to reflect my actual location. Perhaps threshold we use to report location change should take speed into account?
- **What happened instead?**
  Location updates when navigating to a destination by walking did not update my current location frequently and it felt like the current location indicator was "wrong". It would often be a half a block behind where I actually was
- **Steps to reproduce:**
  Enter destination. Select walking. Start Navigation. See that current location pin does not update as regularly as you would expect.

**Comment by mjcunningham** [comment]
What is the location frequency now? Is it doing something different in walking vs driving?

**Comment by ecgreb** [comment]
All location updates are at 1 second intervals in routing mode. This could also be the result of a bad gps signal. @sarahlensing are you still seeing this issue?

**Comment by sarahlensing** [comment]
Closing in favor of https://github.com/mapzen/on-the-road_android/issues/119
