### ISSUE TITLE
Confusing discrepancy between maneuver in top panel and direction list

### ISSUE THREAD

**Issue by souperneon** [mapzen/eraser-map#483]
* **Device name:** 
Samsung Galaxy s6 edge
* **Android Version:** 
4.1.1
* **App build number:**
beta google play store build
* **What did you expected to happen?** 
Expected to see the same maneuver that just happened in the list after seeing it in the top panel while driving
* **What happened instead?**
There was a difference and it was confusing (See screenshot)

* **Attach a screenshot**
![](https://lh4.googleusercontent.com/-eXnm3e9zx0M/VuMqghRyaeI/AAAAAAAAXaQ/Vda8Ei13UZQxHchDB_SDO5bsZcO_v0OzA/w622-h1106-no/2016-03-11.jpg)

![](https://lh4.googleusercontent.com/-fT5MTcnfL_U/VuMqji0jEBI/AAAAAAAAXaY/w835NdrP0AYSozf5yedxQrxW4Wi6FsIeA/w622-h1106-no/2016-03-11.jpg)

* **Attach device logs**
bah

If something happened while you were routing, share with us:

* **Where were you?**
driving north on I95
* **Routing from origin:**
Whitestone Bridge
* **Routing to destination:**
17 Swing Dr, Berkeley MA

**Comment by ecgreb** [comment]
It is the same maneuver. Only the instruction is shortened to just distance and road name in the map view to preserve space. Full text is displayed in the list view.

Also once the maneuver is complete (merge in this case) the turn icon is replaced with a straight arrow in the navigation view to signal "continue on".
