### ISSUE TITLE
Frozen state when exiting routing (stopped at a rest stop)

### ISSUE THREAD

**Issue by souperneon** [mapzen/eraser-map#485]
* **Device name:** 
Samsung Galaxy s6 edge
* **Android Version:** 
4.1.1
* **App build number:**
beta google play store build
* **What did you expected to happen?** 
Pulled up at a rest stop while driving from Whitestone Bridge,NY to Berkeley, MA. Hit device back button to stop routing (coz app was rerouting a bunch). Expected to just go back to choose mode screen
* **What happened instead?**
App froze in a an in-between routing and search results state.
When we started driving, routing started back up again by itself! GHOST!!
* **Steps to reproduce:**
1. Route Whitestone Bridge,NY to Berkeley, MA
2. Pull up at a rest stop at I-95 Northbound, Milford, CT 06460
3. Hit device back button to exit routing more
4. Screenshot showing what happened

* **Attach a screenshot**

![](https://lh4.googleusercontent.com/-HHx5uGTWyno/VubbJjpy6OI/AAAAAAAAXbU/OZH7igYCPfIYzclNMSCP4U-j54bc-0aNw/w671-h1193-no/2016-03-14.jpg)

* **Attach device logs**

If something happened while you were routing, share with us:

* **Where were you?**
Milford, CT
* **Routing from origin:**
Whitestone Bridge, NY
* **Routing to destination:**
Berkeley, MA

**Comment by ecgreb** [comment]
Unable to reproduce in recent builds. Please reopen if you run into this again.
