### ISSUE TITLE
Version 0.6 can lose connection to search/ routing

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#486]
People have reported that in build 0.6 search/ routing will occasionally break until the app is killed and restarted. @heffergm had it happen to him and he was able to see that no key was being sent for search requests.

**Comment by heffergm** [comment]
Example: 

`.../!..~GET /v1/autocomplete?api_key=&focus.point.lat=40.7446039&focus.point.lon=-73.9901832&text=FINDME HTTP/1.1`

**Comment by sarahlensing** [comment]
@heffergm What device was this on?

**Comment by mjcunningham** [comment]
@ecgreb I suspect this has something to do with the build issues you were running into. We don't see this in dev builds.

**Comment by heffergm** [comment]
@sarahlensing galaxy s6 edge, android 5.1.1

**Comment by ecgreb** [comment]
If decoding the encrypted keys is failing that should be in the device logs.

**Comment by ecgreb** [comment]
@mjcunningham @heffergm can you verify if this is still reproducible in the latest release build.

http://android.mapzen.com/erasermap-releases/eraser-map-0.6.1.apk

**Comment by mjcunningham** [comment]
I can't repro it anymore. Any luck @heffergm ?

**Comment by heffergm** [comment]
It's always been random for me so I can't say it's definitely give, but it
hasn't yet happened again.

Il Mer 16 Mar 2016 10:24 AM Mike Cunningham <notifications@github.com> ha
scritto:

> I can't repro it anymore. Any luck @heffergm <https://github.com/heffergm>
> ?
>
> —
> You are receiving this because you were mentioned.
>
> Reply to this email directly or view it on GitHub
> <https://github.com/mapzen/eraser-map/issues/486#issuecomment-197353019>
>
-- 

- Grant

**Comment by ecgreb** [comment]
Ok I am gonna close for now but feel free to reopen if this starts popping up again.

Most likely was related to the errors from re-decoding the production API keys which @sarahlensing added logic to the app to only do this once and @blair1618 fixed the encryption library so even if we do it twice it should not be an issue.
