### ISSUE TITLE
Resume button shows up in routing list view

### ISSUE THREAD

**Issue by souperneon** [mapzen/eraser-map#499]
* **Device name:** 
samsung galaxy s6 edge
* **Android Version:** 
4.1.1
* **App build number:**
master-1311
* **What did you expected to happen?** 
Resume button to be hidden
* **What happened instead?**
button overlapped with list
* **Steps to reproduce:**
- start a route
- page forward in the top panel
- hit the list icon 
- resume button is there
* **Attach a screenshot**

![](https://lh6.googleusercontent.com/-UyrvF4kJfCM/VuhsySuQIYI/AAAAAAAAXbw/lmXlAaXwRdUpQTqsrgR4oU7tx9dFIXiKg/w671-h1193-no/2016-03-15.jpg)

* **Attach device logs**

**Comment by tallytalwar** [comment]
Dup of https://github.com/mapzen/eraser-map/issues/427

**Comment by mjcunningham** [comment]
Dupe, closing.
