### ISSUE TITLE
Beta sign up form should use input type email

### ISSUE THREAD

**Issue by timwis** [mapzen/eraser-map#506]
Just signed up for the beta on my phone and noticed the email field is of `type="text"` instead of `email`. The latter tells phones to show the `@` symbol on the keyboard, not to capitalize the first letter, etc.

https://www.erasermap.com

I'd submit a pull request but couldn't find where the source for the site is.

Forgive me but the issue template is clearly not intended for this sort of issue so I've removed it.

**Comment by mjcunningham** [comment]
Thanks Tim!
