### ISSUE TITLE
Reports of long pressing not reverse geocoding.

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#514]
Can't consistently repro. Keeping this issue here to collect feedback from the field.

**Comment by sarahlensing** [comment]
I can see something weird that might be this issue...

I'm centered in Hilltown, PA and long press on the map but the geocoded location that comes back is not exactly where my finger was...maybe for reverse geocodes that return results that are "far" from the lat/lng we request, we should just show the lat/lng instead of the reverse geo place?

Is this what you see?

**Comment by chrisdebian** [comment]
Hi, Sarah.

I'm centred near Bath in Somerset, UK, and I can confirm that on the odd occasion that a long press does something, the pin/ pointer usually appears in the locale, but not exactly where I'd expect it. I just assumed this was a fat finger/ screen sensitivity issue.

Not sure whether that helps.

Cheers,

Chris.

**Comment by mjcunningham** [comment]
Thanks @chrisdebian! 

@sarahlensing do we have any logic client side there now? Or are we just sending a lat long and displaying what we get back?

**Comment by mjcunningham** [comment]
Related: https://github.com/mapzen/eraser-map/issues/150

**Comment by sarahlensing** [comment]
@chrisdebian Yes, thank you for confirming.

@mjcunningham AFAIK no, we don't have any client side logic, we get the lat/lng where the user presses and display what we get back. I didnt notice this until using reverse geo in a rural area, its very pronounced

**Comment by tallytalwar** [comment]
We do have the lat/long of the screen location being longpressed, which is when sent to Pelias for a ReverseGeo Callback. We can maybe draw the pin at this location irrespective of the feature being returned from Pelias.

**Comment by mjcunningham** [comment]
Closing in favor of: https://github.com/mapzen/eraser-map/issues/524
