### ISSUE TITLE
Car routing Pop-Up Misrepresents Roundabout

### ISSUE THREAD

**Issue by chrisdebian** [mapzen/eraser-map#518]
* **Device name:** 
Nexus 5X
* **Android Version:** 
6.0.1
* **App build number:**
0.7.4-rc1
* **What did you expected to happen?** 
Pop-up message should suggest that I drive the correct way round the roundabout.
* **What happened instead?**
The pop-up suggested I go the wrong way round the roundabout, as if I drove on the left hand side of the road. The actual routing was correct, just the notification pop-up wasn't.
* **Steps to reproduce:**
Travel another route, involving a roundabout.

**Comment by tallytalwar** [comment]
Relates to https://github.com/mapzen/eraser-map/issues/426

**Comment by chrisdebian** [comment]
Thank you.
