### ISSUE TITLE
Map stops updating position

### ISSUE THREAD

**Issue by zerebubuth** [mapzen/eraser-map#521]
* **Device name:** Nexus 4
* **Android Version:** 5.1.1
* **App build number:** Not sure - it's the beta version from Google Play, but doesn't seem to display a build number on start-up, or in any of the menus.
* **What did you expected to happen?** When I drive, the map position remains centered on my car.
* **What happened instead?** The current location symbol moved, but the map stayed the same.

If something happened while you were routing, share with us:

* **Where were you?** Approximately here [51.57234, -0.10597](http://www.openstreetmap.org/?mlat=51.57234&mlon=-0.10597#map=18/51.57234/-0.10597)
* **Routing from origin:** Approximately [51.5686, -0.1107](http://www.openstreetmap.org/?mlat=51.5686&mlon=-0.1107#map=16/51.5686/-0.1107).
* **Routing to destination:** Here [51.5637, -0.0854](http://www.openstreetmap.org/?mlat=51.5637&mlon=-0.0854#map=16/51.5637/-0.0854).

![screenshot_2016-03-13-13-50-48](https://cloud.githubusercontent.com/assets/271360/13945828/4a646110-f008-11e5-8b6b-8a6bb0bebcd6.png)

**Comment by ecgreb** [comment]
There is definitely a bug here that occurs from time to time at the start of a route. Workaround is to pan the map so the resume button appears then click it.

**Comment by ecgreb** [comment]
Its been a while since we were able to reproduce. This may have been solved when migrating to the Mapzen Android SDK. Please re-open if its still happening.
