### ISSUE TITLE
User submitted crash

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#525]
rooted 4.4.4 android S5 (verizon)

Logtrace is here: https://gist.github.com/skorasaurus/d0dbf0e0e2d33cc46dfb

Thanks @skorasaurus!

**Comment by tallytalwar** [comment]
Looks similar to https://github.com/mapzen/eraser-map/issues/515

**Comment by ecgreb** [comment]
I believe this is currently fixed in master. Will update here when this build is live in the beta channel.

https://github.com/mapzen/eraser-map/commit/6cd27aa7f529d03c634cff0c2bd8f2ecadd716b2

**Comment by ecgreb** [comment]
@skorasaurus app version 0.7.6 is now available in the beta channel. Please let us know if this fixes the issue on your device.
