### ISSUE TITLE
Broken UI on an S3 running cyanogenmod11

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#531]
See screenshots. 

![screenshot_2016-03-25-08-37-05](https://cloud.githubusercontent.com/assets/307758/14079117/48fea52c-f4c9-11e5-9ed5-14e46e453b0d.png)
![screenshot_2016-03-25-08-49-03](https://cloud.githubusercontent.com/assets/307758/14079118/4a65f8fc-f4c9-11e5-807e-c4d10e116ead.png)

**Comment by sarahlensing** [comment]
Closing because cyanogenmod is no more :)
