### ISSUE TITLE
Keep current location in center of the screen as you move

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#536]
Currently, you can dive off the screen.

**Comment by tallytalwar** [comment]
One thing to test out in this will be to not to center the current location when the map has been touched, as in panned/pinched/tilted!

**Comment by tallytalwar** [comment]
Just to document what I was thinking about this.

Its exactly like the "resume" button functionality in routing mode. 

- By default routing icon sticks at the defined position
- When map is touched (panned, pinched, tilted, etc)
  - resume button shows up and map is not adjusted to keep routing icon in its place.
- On pressing resume button, routing goes back to default handling, which is to adjust the map position so as to keep routing icon in its place.

Analogously,
- By default "current location" marker sticks at the defined position (which is the center of the map).
- When map is touched (panned, pinched, tilted, etc)
  - map is not adjusted to keep "current location" marker in its place. 
- On pressing the "findMe" icon, it goes back to the default behavior, which is to adjust the map position so as to keep "current location" marker in its place.
