### ISSUE TITLE
Delayed street name update on Search Server

### ISSUE THREAD

**Issue by caioiglesias** [mapzen/eraser-map#542]
- **Device name:** Galaxy S6 Edge Plus
- **Android Version:** 5.1.1
- **App build number:** 0.7.6
- **What did you expected to happen?** Find the correct street
- **What happened instead?** It suggests an old wrong name, but when routing through the street it shows the correct street name.
- **Steps to reproduce:** Search for Guaramomis, and get Guaramonis in São Paulo, SP, Brazil
- **Where were you?**
- **Routing from origin:** Guaramomis 👍 
- **Routing to destination:** Guaramonis 👎 

The correct street name is Guaramomis, instead of Guaramonis (with a "N"). I fixed this on openstreemap [a month ago](https://www.openstreetmap.org/changeset/37390402). The search server is not updated, but the routing server delivers the correct name for the destination. I have a hunch that this is a [Pelias](https://github.com/pelias/pelias) issue instead.

![screenshot_2016-04-07-14-31-44](https://cloud.githubusercontent.com/assets/41685/14361253/7368c694-fcd0-11e5-970a-902622fb9621.png)

**Comment by mjcunningham** [comment]
This is such a great bug report and you may have hit the nail on the head. 

Adding some people from our routing/ search teams. 

@dianashk @dnesbitt61 do we think thats the culprit?

**Comment by dnesbitt61** [comment]
Routing will substitute whatever name is given for the destination location in the final maneuver - so the incorrect name must have been passed in from Eraser Map / search.

**Comment by caioiglesias** [comment]
Now that the pins are dropping closer to their location on this new version I dropped one there.
You can see the street name on the map vs the name that came back from the geocoder.

![screenshot april 13 2016 01 51](https://cloud.githubusercontent.com/assets/41685/14486256/413b671a-0132-11e6-8911-b874c80b0d5d.png)

**Comment by sarahlensing** [comment]
Closing due inactivity. Lets open an issue in Pelias if this is still an issue.
