### ISSUE TITLE
Search by coordinates, support geo:lat,lon URI

### ISSUE THREAD

**Issue by roman-yepishev** [mapzen/eraser-map#544]
* **Device name:** Nexus 5
* **Android Version:** 6.0.1
* **App build number:** 0.8.0
* **What did you expected to happen?** Using a geo:42.34486,-71.08275 link lists Eraser Map as an option, entering "42.34486 -71.08275" leading to a search.
* **What happened instead?** Eraser Map is not in handlers for geo: link, search for coordinates tries to parse the number into an address - 423/44 Miriova in Czech Republic.
* **Steps to reproduce:** Use [geo:42.34486,-71.08275](geo:42.34486,-71.08275) link or enter coordinates into a search field.

If something happened while you were searching, share with us:

* **Where were you?** USA, Boston, MA

**Comment by mjcunningham** [comment]
Thanks for the suggestion! I'll close this issue and track the work here: https://github.com/mapzen/eraser-map/issues/545
