### ISSUE TITLE
Should support turn restrictions

### ISSUE THREAD

**Issue by roman-yepishev** [mapzen/eraser-map#549]
Eraser Map does not seem to support turn restrictions as of v0.8.0

Example intersection: [42.4977955, -83.4172415](https://www.openstreetmap.org/#map=17/42.4977955/-83.4172415)

JOSM screenshot showing restrictions:
![josm-restrictions](https://cloud.githubusercontent.com/assets/601685/14741100/f709fb3e-0861-11e6-84ba-96a7b14c19be.jpg)

Eraser Map disregarding those:
![erasermap-turn](https://cloud.githubusercontent.com/assets/601685/14741801/e8baa65a-0866-11e6-9334-62fa43a877b2.png)

**Comment by ecgreb** [comment]
Thanks for the report @roman-yepishev! I'm passing this along to our routing service team.

**Comment by ecgreb** [comment]
Are you sure the app was in driving mode? Could it have been set to walking directions?

Looks like this test produces the correct route when mode is set to car.

http://www.openstreetmap.org/directions?engine=mapzen_car&route=42.49788%2C-83.41091%3B42.49578%2C-83.41710#map=17/42.49683/-83.41514

**Comment by roman-yepishev** [comment]
Here's the full screenshot:
![erasermap-turn](https://cloud.githubusercontent.com/assets/601685/14752331/bcbdf21a-089c-11e6-9310-ed5442a7d210.png)

And I am able to reproduce it with http://www.openstreetmap.org/directions?engine=mapzen_car&route=42.4974%2C-83.3545%3B42.4862%2C-83.4212#map=17/42.49682/-83.41577

**Comment by dnesbitt61** [comment]
I believe this is fixed in our latest Mapzen Turn-by-Turn release. Thanks for reporting this bug.

**Comment by dgearhart** [comment]
Agreed, looks like typical Michigan Left now
![screenshot from 2016-04-29 11 04 21](https://cloud.githubusercontent.com/assets/7515853/14920204/563914bc-0dfa-11e6-8e2b-ee4bdf7e3392.png)

**Comment by mjcunningham** [comment]
Thanks everyone!
