### ISSUE TITLE
ReverseGeo pins are not drawn and more

### ISSUE THREAD

**Issue by tallytalwar** [mapzen/eraser-map#554]
* **Device name:** Samsung Galax
* **Android Version:** 5.0
* **App build number:** 0.9.1

1. When doing a poi tap I would expect the name of the tapped poi to be shown at the footer ui, but no footer was displaced.
  1. Current location: 30 W 26th Street, NY 10010
  2. Try tapping on any POI Icon.

2. When I reverseGeo (do a long press) after doing a poi tap, I would have expected the pin to update to the new reverseGeo location, but the pin was updated.
  1. Current location: 30 W 26th Steet, NY 10010
  2. Tap on any poi icon
  3. Do a reverseGeocode (long press) on any location other the the tapped poi in (2).

3. After doing a reverseGeo code and getting a pin drop with the name in the footer, try doing an explicit search, map switches to the searched place with the correct pin drop but the footer now shows "Dropped Pin", instead of showing the name of the explicitly searched place from Pelias.
  1. Current location: 30 W 26th Street, NY 10010
  2. Do a reverseGeo by long pressing and get a pin on the map
  3. Go and search for another place, I did "301 Commons Park S, Stamford, CT 06902"
  4. Now you will notice that the mapped moved to the searched place, but the footer UI has "Dropped Pin" instead of "Postmark Apt" which was previously being displaced (as its the feature name returned from Pelias).

**Comment by tallytalwar** [comment]
Nice, small fix and yes related to the tiles update :D

**Comment by tallytalwar** [comment]
I still see some weirdness in the "dropped pin" behavior.

Repro:

1. search for "301 commons park S, stamford"
2. you get a named pin (good)
![screenshot_2016-05-11-12-58-34](https://cloud.githubusercontent.com/assets/360641/15189396/713c8d8e-1778-11e6-80c3-e43552082e7b.png)

3. hit back
4. reversegeocode on a location which will definite give you a "dropped pin". You can try the same area I tried! (good) 
![screenshot_2016-05-11-12-58-08](https://cloud.githubusercontent.com/assets/360641/15189407/863563dc-1778-11e6-9e41-58aa9a234938.png)

5. without hitting return, search again for "301 commons park s" from the previous searched.
6. you will not see a named pin now, but a "dropped pin" name will appear. (bad)
![screenshot_2016-05-11-12-58-14](https://cloud.githubusercontent.com/assets/360641/15189421/99526028-1778-11e6-9233-9ef8516134f3.png)

**Comment by ecgreb** [comment]
Re-opening. @sarahlensing does https://github.com/mapzen/eraser-map/pull/563 solve this additional issue?

**Comment by sarahlensing** [comment]
@ecgreb yes it does, i updated the ticket to reflect so
