### ISSUE TITLE
Shows an area as a building on high zoom levels

### ISSUE THREAD

**Issue by roman-yepishev** [mapzen/eraser-map#564]
* **Device name:** Nexus 5
* **Android Version:** 6.0.1
* **App build number:** 0.9.1 (Google Play Beta)
* **What did you expected to happen?** A parking lot with lanes
* **What happened instead?** A building on high zoom levels, a parking lot at small zoom levels
* **Steps to reproduce:** Navigate to  http://www.openstreetmap.org/way/321659438 ([geo:42.53624,-83.44728?z=18](geo:42.53624,-83.44728?z=18)
* **Attach a screenshot** 

![building-parking](https://cloud.githubusercontent.com/assets/601685/15270521/ad87fb46-19f0-11e6-8ff9-c50d8c57175f.png)

**Comment by ecgreb** [comment]
Thanks for the report. Are you seeing this issue with other parking lots or just this one?

cc @nvkelso

**Comment by roman-yepishev** [comment]
Since I filed that issue I found a golf course that behaves the same way - http://www.openstreetmap.org/relation/3547898

![golf-building](https://cloud.githubusercontent.com/assets/601685/15291537/773717c2-1b4c-11e6-8bb5-e888e8fa7a46.png)

**Comment by blair1618** [comment]
This appears to be an issue in the tile data. Looking at a tile containing the golf course at zoom 15 (http://vector.mapzen.com/osm/all/15/8791/12104.json) and zoom 16 (http://vector.mapzen.com/osm/all/16/17583/24208.json) it's apparent that the golf course is present in the "buildings" layer starting at  zoom 16 (it's the first feature in the buildings layer). The bubble-wrap style renders polygons in the "buildings" layer with some default, non-zero height, and that's what we see here.  

cc @nvkelso

**Comment by nvkelso** [comment]
Fix for this is on `dev`, should be in `production` this week.

**Comment by nvkelso** [comment]
Fix has been verified and is live on `prod`.

<img width="712" alt="screen shot 2016-05-23 at 15 32 46" src="https://cloud.githubusercontent.com/assets/853051/15486600/cece9dde-20fb-11e6-952a-ac47d3454ecc.png">

<img width="545" alt="screen shot 2016-05-23 at 15 32 33" src="https://cloud.githubusercontent.com/assets/853051/15486591/c07ee036-20fb-11e6-9502-b5e9e5ba81fc.png">
