### ISSUE TITLE
Both route lines shown after reroute

### ISSUE THREAD

**Issue by ecgreb** [mapzen/eraser-map#582]
After rerouting the original route line (originating near Westwick) was not cleared from the map.

![image](https://cloud.githubusercontent.com/assets/464123/15442420/0a419762-1eaf-11e6-9fbc-d07ec08ec049.png)

**Comment by sarahlensing** [comment]
@ecgreb I'm unable to repro this at the moment, could you verify its happening on master still?

**Comment by mjcunningham** [comment]
Closing this, we can re-open it if we see it in this version of tangram.
