### ISSUE TITLE
Allows ground-level POV in navigation mode.

### ISSUE THREAD

**Issue by roman-yepishev** [mapzen/eraser-map#590]
- **Device name:** Nexus 5
- **Android Version:** 6.0.1
- **App build number:** 0.9.2 (GitHub release)
- **What did you expected to happen?** Camera is not allowed to land on the map
- **What happened instead?** I was able to get very close to the ground (not underground though), the map converged to an invisible line and only the feature names were visible.
- **Steps to reproduce:**
  1. Restart Eraser Map (sometimes after the glitch can't be reproduced when application was already running for some time)
  2. Select a point on the map, request navigation in Bicycle mode, lower the camera as much as possible.
  3. Start navigation
  4. Lower the map even more
  5. Get a first-person POV. Get disappointed that buildings are empty inside.
- **Attach a screenshot**
  ![game-mode](https://cloud.githubusercontent.com/assets/601685/15488718/29a2d2a4-2127-11e6-81da-1ee154240f90.png)

**Comment by ecgreb** [comment]
This is an interesting one for sure! So far I have been unable to reproduce on my device (Nextbit Robin 6.0.1). @blair1618 @tallytalwar have you seen this? Do we have explicit limits to tilt angle in Tangram?

**Comment by blair1618** [comment]
Dude that's wild. I'll try it out myself but to answer your questions 1) I've never seen this before and 2) there are no built-in limits to tilt angle. There is however, a built-in limit to zoom level, which should prevent the camera from getting this close to the ground, so that's odd.

**Comment by blair1618** [comment]
Ah right, ok, so the zoom level does stop at the intended limit but tilting all the way to 90 degrees will cause the camera to sit parallel to the ground, as shown. 

This state is not unrecoverable, but it isn't ideal either. I don't know how I feel about built-in limits to tilting, I can imagine cases where one would want to tilt almost or fully to a horizontal view. It would be sensible, however, for tangram to provide a way for client applications to limit the tilt angle.

**Comment by roman-yepishev** [comment]
How does it prevent tilting to such angle in regular browsing mode? I was able to reproduce it only by switching transport in navigation, otherwise the angle seems to be limited by something.

**Comment by sarahlensing** [comment]
@matteblair Is there a tangram ticket we can link to to allow limiting the tilt angle?
