### ISSUE TITLE
Check "kind" before showing POI name

### ISSUE THREAD

**Issue by sarahlensing** [mapzen/eraser-map#606]
Traffic light shows "PATH"...use "kind" in the tile properties to know not to use the name from a reverse result of "layer":"venue". Instead use a "layer":"address" result

![screenshot_20160531-171828](https://cloud.githubusercontent.com/assets/494323/15690968/2b6a9f8a-2754-11e6-8611-d4949e98327d.png)

https://search.mapzen.com/v1/reverse?point.lat=40.746237840644184&point.lon=-73.99051741686864&api_key=search-BcgTWes

**Comment by ecgreb** [comment]
I'm not sure if it makes sense for users to be able to click a traffic signal to reverse geocode and route in the same way as other POIs (restaurants, transit stations, etc).

I'm thinking for some kinds of POIs (like traffic signals) we should just ignore the click.

**Comment by sarahlensing** [comment]
I believe this has been resolved by stylesheet interactivity updates.
