### ISSUE TITLE
When a route is selected, prefetch tiles for route

### ISSUE THREAD

**Issue by riordan** [mapzen/eraser-map#61]
I spent the weekend driving around an area with poor cell coverage testing Erasermap. Led to some interesting issues. 

Biggest amongst these is that while I'd start driving with coverage (albeit limited), I'd quickly enter an area that had none and my route line would be all the navigation assistance I would have.

Is there any plan to set up a means to pre-fetch all tiles a route will pass through once it's selected?

**Comment by riordan** [comment]
Also #60 should be a huge help with the experience I had.

**Comment by tallytalwar** [comment]
I think this is on the tangram side for prefetching of tiles in the route.

We can discuss this in the meeting tomorrow for more details.

**Comment by riordan** [comment]
Awesome!

**Comment by blair1618** [comment]
If anyone has an opportunity to test this scenario in a commercial mapping app, that would certainly help us decide on a roadmap for something like this (e.g. start routing somewhere with gmaps and then go into a subway and see if the tiles along your route are loaded).

**Comment by nvkelso** [comment]
Apple does not do map tile pre-fetches along the route, Google kinda does (it's change a lot the last 12 months).

**Comment by sarahlensing** [comment]
Will investigate this as part of https://github.com/mapzen/android/issues/328
