### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#624]
'''
06-09 11:22:50.452 30214-30271/com.mapzen.erasermap A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 30271 (Thread-12011)
06-09 11:22:50.512 3054-3054/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-09 11:22:50.512 3054-3054/? A/DEBUG: Build fingerprint: 'samsung/zerolteuc/zerolteatt:6.0.1/MMB29K/G925AUCU3CPD6:user/release-keys'
06-09 11:22:50.512 3054-3054/? A/DEBUG: Revision: '10'
06-09 11:22:50.512 3054-3054/? A/DEBUG: ABI: 'arm64'
06-09 11:22:50.512 3054-3054/? A/DEBUG: pid: 30214, tid: 30271, name: Thread-12011  >>> com.mapzen.erasermap <<<
06-09 11:22:50.512 3054-3054/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
06-09 11:22:50.522 3054-3054/? A/DEBUG:     x0   0000000000000000  x1   000000000000763f  x2   0000000000000006  x3   0000000000000000
06-09 11:22:50.522 3054-3054/? A/DEBUG:     x4   0000000000000000  x5   0000000000000001  x6   0000000000000000  x7   0000000000000000
06-09 11:22:50.522 3054-3054/? A/DEBUG:     x8   0000000000000083  x9   000000000000763f  x10  0000007fb0a3d774  x11  0000000000004000
06-09 11:22:50.522 3054-3054/? A/DEBUG:     x12  0000000000004001  x13  0000000000000000  x14  0000000000000001  x15  00000000ffffffff
06-09 11:22:50.522 3054-3054/? A/DEBUG:     x16  0000007fb0a2f568  x17  0000007fb09c2338  x18  0000000000000059  x19  0000007f94997500
06-09 11:22:50.522 3054-3054/? A/DEBUG:     x20  0000007f94997440  x21  0000000000000000  x22  0000000000000006  x23  434c4e47432b2b00
06-09 11:22:50.522 3054-3054/? A/DEBUG:     x24  0000007f92736200  x25  0000007f94fc8d30  x26  0000007f94f5b0b0  x27  0000007f5e72c5b0
06-09 11:22:50.522 3054-3054/? A/DEBUG:     x28  0000007f5100c801  x29  0000007f94996a50  x30  0000007fb09bfad4
06-09 11:22:50.522 3054-3054/? A/DEBUG:     sp   0000007f94996a50  pc   0000007fb09c2340  pstate 0000000020000000
06-09 11:22:50.532 3054-3054/? A/DEBUG: backtrace:
06-09 11:22:50.532 3054-3054/? A/DEBUG:     #00 pc 0000000000069340  /system/lib64/libc.so (tgkill+8)
06-09 11:22:50.532 3054-3054/? A/DEBUG:     #01 pc 0000000000066ad0  /system/lib64/libc.so (pthread_kill+68)
06-09 11:22:50.532 3054-3054/? A/DEBUG:     #02 pc 0000000000023910  /system/lib64/libc.so (raise+28)
06-09 11:22:50.532 3054-3054/? A/DEBUG:     #03 pc 000000000001e240  /system/lib64/libc.so (abort+60)
06-09 11:22:50.532 3054-3054/? A/DEBUG:     #04 pc 0000000000092fec  /data/app/com.mapzen.erasermap-1/lib/arm64/libc++_shared.so (abort_message+140)
06-09 11:22:50.532 3054-3054/? A/DEBUG:     #05 pc 0000000000093164  /data/app/com.mapzen.erasermap-1/lib/arm64/libc++_shared.so (_ZL25default_terminate_handlerv+268)
06-09 11:22:50.532 3054-3054/? A/DEBUG:     #06 pc 00000000000be1d4  /data/app/com.mapzen.erasermap-1/lib/arm64/libc++_shared.so (_ZSt11__terminatePFvvE+12)
06-09 11:22:50.532 3054-3054/? A/DEBUG:     #07 pc 00000000000bd87c  /data/app/com.mapzen.erasermap-1/lib/arm64/libc++_shared.so (__cxa_throw+204)
06-09 11:22:50.532 3054-3054/? A/DEBUG:     #08 pc 000000000016c2d8  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (_ZNK7Tangram7matcherclERKNS_6Filter8EqualityE+204)
06-09 11:22:50.532 3054-3054/? A/DEBUG:     #09 pc 000000000016be60  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (_ZN6mapbox4util7variantIJN7Tangram9none_typeENS2_6Filter11OperatorAllENS4_12OperatorNoneENS4_11OperatorAnyENS4_11EqualitySetENS4_8EqualityENS4_5RangeENS4_9ExistenceENS4_8FunctionEEE5visitINS2_7matcherESD_EEDTclsr6detail10dispatcherIT_T0_NS0_6detail21result_of_unary_visitISG_S3_vE4typeES3_S5_S6_S7_S8_S9_SA_SB_SC_EE11apply_constfp_fp0_EERKSH_SG_+268)
06-09 11:22:50.532 3054-3054/? A/DEBUG:     #10 pc 000000000016a3fc  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (_ZN7Tangram16DrawRuleMergeSet5matchERKNS_7FeatureERKNS_10SceneLayerERNS_12StyleContextE+316)
06-09 11:22:50.532 3054-3054/? A/DEBUG:     #11 pc 000000000016a758  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (_ZN7Tangram16DrawRuleMergeSet5applyERKNS_7FeatureERKNS_10SceneLayerERNS_12StyleContextERNS_11TileBuilderE+48)
06-09 11:22:50.532 3054-3054/? A/DEBUG:     #12 pc 000000000013c648  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (_ZN7Tangram11TileBuilder5buildENS_6TileIDERKNS_8TileDataERKNS_10DataSourceE+684)
06-09 11:22:50.532 3054-3054/? A/DEBUG:     #13 pc 00000000000c43f8  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (_ZN7Tangram10TileWorker3runEPNS0_6WorkerE+1140)
06-09 11:22:50.532 3054-3054/? A/DEBUG:     #14 pc 00000000000c4fa0  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (_ZNSt3__114__thread_proxyINS_5tupleIJMN7Tangram10TileWorkerEFvPNS3_6WorkerEEPS3_S5_EEEEEPvSA_+124)
06-09 11:22:50.532 3054-3054/? A/DEBUG:     #15 pc 0000000000065f20  /system/lib64/libc.so (_ZL15__pthread_startPv+52)
06-09 11:22:50.532 3054-3054/? A/DEBUG:     #16 pc 000000000001edec  /system/lib64/libc.so (__start_thread+16)
06-09 11:22:50.992 3054-3054/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_02
06-09 11:22:50.992 3054-3054/? E/DEBUG: AM write failed: Broken pipe
                                        
                                        [ 06-09 11:22:50.992  3054: 3054 E/         ]
                                        ro.product_ship = true
                                        
                                        [ 06-09 11:22:50.992  3054: 3054 E/         ]
                                        ro.debug_level = 0x4f4c
                                        
                                        [ 06-09 11:22:50.992  3054: 3054 E/         ]
                                        sys.mobilecare.preload = false
06-09 11:22:51.002 6196-6196/? E/audit: type=1701 msg=audit(1465485770.992:620): auid=4294967295 uid=10246 gid=10246 ses=4294967295 subj=u:r:untrusted_app:s0:c512,c768 pid=30271 comm="Thread-12011" reason="memory violation" sig=6
06-09 11:22:51.122 3036-3036/? E/lowmemorykiller: Error writing /proc/30214/oom_score_adj; errno=22
06-09 11:22:51.172 3517-4177/? E/InputDispatcher: channel ~ Channel is unrecoverably broken and will be disposed!
'''

**Comment by ecgreb** [comment]
Looks like a Tangram jawn. I'm going to update the SDK and app to Tangram 0.3.1 today and that should make things more stable on this front.

**Comment by blair1618** [comment]
Yep, this might be resolved by a fix in tangram 0.3.1, or it might not! Concurrency issues are fun like that.

**Comment by ecgreb** [comment]
Eraser Map snapshots are now using Tangram 0.3.1. Closing for now but let's reopen if we see this crash again.
