### ISSUE TITLE
Crash on 1590

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#629]
```
06-09 16:53:25.921 3054-3054/? A/DEBUG: backtrace:
06-09 16:53:25.921 3054-3054/? A/DEBUG:     #00 pc 0000000000069340  /system/lib64/libc.so (tgkill+8)
06-09 16:53:25.921 3054-3054/? A/DEBUG:     #01 pc 0000000000066ad0  /system/lib64/libc.so (pthread_kill+68)
06-09 16:53:25.921 3054-3054/? A/DEBUG:     #02 pc 0000000000023910  /system/lib64/libc.so (raise+28)
06-09 16:53:25.921 3054-3054/? A/DEBUG:     #03 pc 000000000001e240  /system/lib64/libc.so (abort+60)
06-09 16:53:25.921 3054-3054/? A/DEBUG:     #04 pc 000000000031fc84  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (abort_message+140)
06-09 16:53:25.921 3054-3054/? A/DEBUG:     #05 pc 000000000031fd94  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (_ZL25default_terminate_handlerv+268)
06-09 16:53:25.921 3054-3054/? A/DEBUG:     #06 pc 000000000031d29c  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (_ZSt11__terminatePFvvE+12)
06-09 16:53:25.921 3054-3054/? A/DEBUG:     #07 pc 000000000031c944  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (__cxa_throw+204)
06-09 16:53:25.921 3054-3054/? A/DEBUG:     #08 pc 000000000031d3bc  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (_Znwm+92)
06-09 16:53:25.921 3054-3054/? A/DEBUG:     #09 pc 000000000015a590  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (_ZN6mapbox6detail6EarcutItEclINSt3__16vectorINS5_IN3glm5tvec3IfLNS6_9precisionE0EEENS4_9allocatorIS9_EEEENSA_ISC_EEEEEEvRKT_+236)
06-09 16:53:25.921 3054-3054/? A/DEBUG:     #10 pc 000000000015a084  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (_ZN7Tangram8Builders12buildPolygonERKNSt3__16vectorINS2_IN3glm5tvec3IfLNS3_9precisionE0EEENS1_9allocatorIS6_EEEENS7_IS9_EEEEfRNS_14PolygonBuilderE+208)
06-09 16:53:25.921 3054-3054/? A/DEBUG:     #11 pc 0000000000146edc  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (_ZN7Tangram19PolygonStyleBuilderINS_18PolygonVertexNoUVsEE10addPolygonERKNSt3__16vectorINS4_IN3glm5tvec3IfLNS5_9precisionE0EEENS3_9allocatorIS8_EEEENS9_ISB_EEEERKNS_10PropertiesERKNS_8DrawRuleE+152)
06-09 16:53:25.921 3054-3054/? A/DEBUG:     #12 pc 000000000014fda8  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (_ZN7Tangram12StyleBuilder10addFeatureERKNS_7FeatureERKNS_8DrawRuleE+172)
06-09 16:53:25.921 3054-3054/? A/DEBUG:     #13 pc 000000000018b53c  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (_ZN7Tangram16DrawRuleMergeSet5applyERKNS_7FeatureERKNS_10SceneLayerERNS_12StyleContextERNS_11TileBuilderE+2232)
06-09 16:53:25.921 3054-3054/? A/DEBUG:     #14 pc 00000000001590f4  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (_ZN7Tangram11TileBuilder5buildENS_6TileIDERKNS_8TileDataERKNS_10DataSourceE+684)
06-09 16:53:25.921 3054-3054/? A/DEBUG:     #15 pc 00000000000db68c  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (_ZN7Tangram8TileTask7processERNS_11TileBuilderE+84)
06-09 16:53:25.921 3054-3054/? A/DEBUG:     #16 pc 00000000000dbf44  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (_ZN7Tangram10TileWorker3runEPNS0_6WorkerE+1092)
06-09 16:53:25.921 3054-3054/? A/DEBUG:     #17 pc 00000000000dca6c  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (_ZNSt3__114__thread_proxyINS_5tupleIJMN7Tangram10TileWorkerEFvPNS3_6WorkerEEPS3_S5_EEEEEPvSA_+124)
06-09 16:53:25.921 3054-3054/? A/DEBUG:     #18 pc 0000000000065f20  /system/lib64/libc.so (_ZL15__pthread_startPv+52)
06-09 16:53:25.921 3054-3054/? A/DEBUG:     #19 pc 000000000001edec  /system/lib64/libc.so (__start_thread+16)
06-09 16:53:26.071 3517-5278/? E/Sensors: Pressure old sensor_state 32785, new sensor_state : 32817 en : 1
06-09 16:53:26.091 3517-4133/? E/Sensors: Sensor : Meta event
06-09 16:53:26.311 3054-3054/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_04
06-09 16:53:26.311 3054-3054/? E/DEBUG: AM write failed: Broken pipe
                                        
                                        [ 06-09 16:53:26.311  3054: 3054 E/         ]
                                        ro.product_ship = true
                                        
                                        [ 06-09 16:53:26.311  3054: 3054 E/         ]
                                        ro.debug_level = 0x4f4c
                                        
                                        [ 06-09 16:53:26.311  3054: 3054 E/         ]
                                        sys.mobilecare.preload = false
06-09 16:53:26.311 6196-6196/? E/audit: type=1701 msg=audit(1465505606.311:914): auid=4294967295 uid=10247 gid=10247 ses=4294967295 subj=u:r:untrusted_app:s0:c512,c768 pid=28772 comm="Thread-11823" reason="memory violation" sig=6
06-09 16:53:26.361 3036-3036/? E/lowmemorykiller: Error writing /proc/28699/oom_score_adj; errno=22
06-09 16:53:27.021 3517-4938/? E/Sensors: Pressure old sensor_state 131105, new sensor_state : 131073 en : 0
06-09 16:53:28.371 28476-28476/? E/MTPRx: MS triggered
06-09 16:53:28.621 6022-6034/? E/DatabaseUtils: Writing exception to parcel
                                                java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/fs_id from pid=23117, uid=10159 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
                                                    at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:646)
                                                    at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:493)
                                                    at android.content.ContentProvider$Transport.query(ContentProvider.java:218)
                                                    at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
                                                    at android.os.Binder.execTransact(Binder.java:453)
06-09 16:53:28.681 28488-28488/? E/CMHService: [#CMH#] onCreate() 
06-09 16:53:28.681 28488-28804/? E/Controller: [#CMH#] Update failed CV: mime_type=null clusterDayId=-1 _size=0 title=.temp clusterId=-1 is_secretbox=0 is_drm=false date_modified=1465505599where:uri = ? args:[content://media/external/file/18]
```

**Comment by blair1618** [comment]
Yep that's from tangram somewhere. What was the app doing when this happened?

**Comment by mjcunningham** [comment]
06-09 17:04:18.731 31806-31806/com.mapzen.erasermap A/libc: Fatal signal 7 (SIGBUS), code 1, fault addr 0x4c in tid 31806 (apzen.erasermap)
06-09 17:04:18.781 3054-3054/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-09 17:04:18.781 3054-3054/? A/DEBUG: Build fingerprint: 'samsung/zerolteuc/zerolteatt:6.0.1/MMB29K/G925AUCU3CPD6:user/release-keys'
06-09 17:04:18.781 3054-3054/? A/DEBUG: Revision: '10'
06-09 17:04:18.781 3054-3054/? A/DEBUG: ABI: 'arm64'
06-09 17:04:18.791 3054-3054/? A/DEBUG: pid: 31806, tid: 31806, name: apzen.erasermap  >>> com.mapzen.erasermap <<<
06-09 17:04:18.791 3054-3054/? A/DEBUG: signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0x4c
06-09 17:04:18.821 3054-3054/? A/DEBUG:     x0   0000000000000044  x1   0000007fb0a2f000  x2   0000000000000025  x3   0000007fb0a2f000
06-09 17:04:18.821 3054-3054/? A/DEBUG:     x4   0000000000000000  x5   0000000000000046  x6   0000000000000047  x7   0000000000000010
06-09 17:04:18.821 3054-3054/? A/DEBUG:     x8   000000000000004c  x9   0000007f9578ec88  x10  0000000000000006  x11  0000007facfc24a0
06-09 17:04:18.821 3054-3054/? A/DEBUG:     x12  0000000000000007  x13  0000000000004fff  x14  000000000000003c  x15  fffffffffffff000
06-09 17:04:18.821 3054-3054/? A/DEBUG:     x16  0000007f95796330  x17  0000007f954bd6b0  x18  0000000000004000  x19  0000000000000044
06-09 17:04:18.821 3054-3054/? A/DEBUG:     x20  0000007f7ea87af0  x21  0000007f986f54b8  x22  0000007f806922c0  x23  0000007f6aa0b3c8
06-09 17:04:18.821 3054-3054/? A/DEBUG:     x24  0000000000000000  x25  00000000713c17a8  x26  0000000000000000  x27  0000000012c8b640
06-09 17:04:18.821 3054-3054/? A/DEBUG:     x28  0000280800007c3e  x29  0000007fe592dae0  x30  0000007f95438d10
06-09 17:04:18.821 3054-3054/? A/DEBUG:     sp   0000007fe592dad0  pc   0000007f9564d5cc  pstate 0000000020000000
06-09 17:04:18.851 3054-3054/? A/DEBUG: backtrace:
06-09 17:04:18.851 3054-3054/? A/DEBUG:     #00 pc 00000000003165cc  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (_ZNSt3__119__shared_weak_count16__release_sharedEv+20)
06-09 17:04:18.851 3054-3054/? A/DEBUG:     #01 pc 0000000000101d0c  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (_ZN7Tangram9TextLabelD0Ev+16)
06-09 17:04:18.851 3054-3054/? A/DEBUG:     #02 pc 00000000000fbf9c  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (_ZN7Tangram8LabelSetD1Ev+80)
06-09 17:04:18.851 3054-3054/? A/DEBUG:     #03 pc 00000000001019d4  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (_ZN7Tangram10TextLabelsD0Ev+16)
06-09 17:04:18.851 3054-3054/? A/DEBUG:     #04 pc 00000000000d49dc  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (_ZN7Tangram4TileD1Ev+148)
06-09 17:04:18.851 3054-3054/? A/DEBUG:     #05 pc 00000000003165f0  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (_ZNSt3__119__shared_weak_count16__release_sharedEv+56)
06-09 17:04:18.851 3054-3054/? A/DEBUG:     #06 pc 00000000000d5660  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (_ZN7Tangram9TileCache5clearEv+152)
06-09 17:04:18.851 3054-3054/? A/DEBUG:     #07 pc 00000000000d5bd4  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (_ZN7Tangram11TileManager12clearTileSetEi+112)
06-09 17:04:18.851 3054-3054/? A/DEBUG:     #08 pc 00000000000d2ac4  /data/app/com.mapzen.erasermap-1/lib/arm64/libtangram.so (_ZN7Tangram15clearDataSourceERNS_10DataSourceEbb+68)
06-09 17:04:18.851 3054-3054/? A/DEBUG:     #09 pc 0000000000bd5a50  /data/app/com.mapzen.erasermap-1/oat/arm64/base.odex (offset 0x7f5000) (void com.mapzen.tangram.MapController.nativeClearDataSource(long)+148)
06-09 17:04:18.851 3054-3054/? A/DEBUG:     #10 pc 0000000000bd7d98  /data/app/com.mapzen.erasermap-1/oat/arm64/base.odex (offset 0x7f5000) (com.mapzen.tangram.MapData com.mapzen.tangram.MapData.clear()+92)
06-09 17:04:18.851 3054-3054/? A/DEBUG:     #11 pc 0000000000ff2418  /data/app/com.mapzen.erasermap-1/oat/arm64/base.odex (offset 0x7f5000) (void com.mapzen.android.OverlayManager.updateCurrentLocationMapData(android.location.Location)+76)
06-09 17:04:18.851 3054-3054/? A/DEBUG:     #12 pc 0000000000ff2298  /data/app/com.mapzen.erasermap-1/oat/arm64/base.odex (offset 0x7f5000) (void com.mapzen.android.OverlayManager.showLastKnownLocation()+172)
06-09 17:04:18.851 3054-3054/? A/DEBUG:     #13 pc 0000000000ff1490  /data/app/com.mapzen.erasermap-1/oat/arm64/base.odex (offset 0x7f5000) (void com.mapzen.android.OverlayManager.centerMap()+68)
06-09 17:04:18.851 3054-3054/? A/DEBUG:     #14 pc 0000000000ff1070  /data/app/com.mapzen.erasermap-1/oat/arm64/base.odex (offset 0x7f5000) (void com.mapzen.android.OverlayManager.access$200(com.mapzen.android.OverlayManager)+68)
06-09 17:04:18.851 3054-3054/? A/DEBUG:     #15 pc 0000000000b8a1dc  /data/app/com.mapzen.erasermap-1/oat/arm64/base.odex (offset 0x7f5000) (void com.mapzen.android.OverlayManager$2.onClick(android.view.View)+208)
06-09 17:04:18.851 3054-3054/? A/DEBUG:     #16 pc 00000000046c931c  /system/framework/arm64/boot.oat (offset 0x2f25000)
06-09 17:04:19.281 3054-3054/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_05
06-09 17:04:19.281 3054-3054/? E/DEBUG: AM write failed: Broken pipe
                                        
                                        [ 06-09 17:04:19.281  3054: 3054 E/         ]
                                        ro.product_ship = true
                                        
                                        [ 06-09 17:04:19.281  3054: 3054 E/         ]
                                        ro.debug_level = 0x4f4c
                                        
                                        [ 06-09 17:04:19.281  3054: 3054 E/         ]
                                        sys.mobilecare.preload = false
06-09 17:04:19.281 6196-6196/? E/audit: type=1701 msg=audit(1465506259.281:919): auid=4294967295 uid=10248 gid=10248 ses=4294967295 subj=u:r:untrusted_app:s0:c512,c768 pid=31806 comm="apzen.erasermap" reason="memory violation" sig=7

**Comment by mjcunningham** [comment]
06-09 17:15:00.631 32742-302/com.mapzen.erasermap A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x81 in tid 302 (mali-mem-purge)
06-09 17:15:00.711 3054-3054/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-09 17:15:00.711 3054-3054/? A/DEBUG: Build fingerprint: 'samsung/zerolteuc/zerolteatt:6.0.1/MMB29K/G925AUCU3CPD6:user/release-keys'
06-09 17:15:00.711 3054-3054/? A/DEBUG: Revision: '10'
06-09 17:15:00.711 3054-3054/? A/DEBUG: ABI: 'arm64'
06-09 17:15:00.711 3054-3054/? A/DEBUG: pid: 32742, tid: 302, name: mali-mem-purge  >>> com.mapzen.erasermap <<<
06-09 17:15:00.711 3054-3054/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x81
06-09 17:15:00.731 3517-4589/? E/CSLegacyTypeTracker: add() : Adding agent NetworkAgentInfo{ ni{[type: MOBILE[LTE] - MOBILE_IMS, state: CONNECTED/CONNECTED, reason: connected, extra: ims, roaming: false, failover: false, isAvailable: true]}  network{503}  lp{{InterfaceName: rmnet1 LinkAddresses: [2600:380:8df5:37e5:d1aa:bd6d:898a:d0e8/64,]  Routes: [::/0 -> fe80::2 rmnet1,] DnsAddresses: [] Domains: null MTU: 0 TcpBufferSizes: 1048576,3145728,4194304,524288,1572864,2097152}}  nc{[ Transports: CELLULAR Capabilities: IMS&TRUSTED&NOT_VPN&VALIDATED LinkUpBandwidth>=51200Kbps LinkDnBandwidth>=102400Kbps Specifier: <1>]}  Score{50}  everValidated{true}  lastValidated{true}  created{true} lingering{false} explicitlySelected{false} acceptUnvalidated{false} everCaptivePortalDetected{false} lastCaptivePortalDetected{false} } for legacy network type 11
06-09 17:15:00.781 3054-3054/? A/DEBUG:     x0   0000000000000069  x1   0000007f86a3a6c8  x2   0000000000000000  x3   0000007f56b573e8
06-09 17:15:00.781 3054-3054/? A/DEBUG:     x4   0000000000008000  x5   0000007f86a3a6c8  x6   0000007f986abab8  x7   0000007fb09fe000
06-09 17:15:00.781 3054-3054/? A/DEBUG:     x8   0000007fb09fe140  x9   0000000000017a20  x10  000000000674c4a0  x11  000000000674c500
06-09 17:15:00.781 3054-3054/? A/DEBUG:     x12  0000000000000000  x13  0000007fb0a3d000  x14  0000000000000000  x15  0000007fb0a2f000
06-09 17:15:00.781 3054-3054/? A/DEBUG:     x16  0000007fb0a40eb0  x17  0000007fb0a2f000  x18  0000007fb0a40f50  x19  0000007f86a3a6c8
06-09 17:15:00.781 3054-3054/? A/DEBUG:     x20  0000007f56b573c8  x21  0000000000000051  x22  0000007f9869e000  x23  0000007f986a22a0
06-09 17:15:00.781 3054-3054/? A/DEBUG:     x24  0000007f986a24c4  x25  0000007f9869e2c8  x26  0000007f986a24c1  x27  0000000000000001
06-09 17:15:00.781 3054-3054/? A/DEBUG:     x28  0000000000001000  x29  0000007fa67ba410  x30  0000007f9712eeac
06-09 17:15:00.781 3054-3054/? A/DEBUG:     sp   0000007fa67ba360  pc   0000007f9712edf8  pstate 0000000020000000
06-09 17:15:00.791 3054-3054/? A/DEBUG: backtrace:
06-09 17:15:00.791 3054-3054/? A/DEBUG:     #00 pc 000000000043adf8  /system/vendor/lib64/egl/libGLES_mali.so
06-09 17:15:00.791 3054-3054/? A/DEBUG:     #01 pc 000000000043aea8  /system/vendor/lib64/egl/libGLES_mali.so
06-09 17:15:00.791 3054-3054/? A/DEBUG:     #02 pc 000000000043ba30  /system/vendor/lib64/egl/libGLES_mali.so
06-09 17:15:00.791 3054-3054/? A/DEBUG:     #03 pc 000000000043bd74  /system/vendor/lib64/egl/libGLES_mali.so
06-09 17:15:00.791 3054-3054/? A/DEBUG:     #04 pc 0000000000065f20  /system/lib64/libc.so (_ZL15__pthread_startPv+52)
06-09 17:15:00.791 3054-3054/? A/DEBUG:     #05 pc 000000000001edec  /system/lib64/libc.so (__start_thread+16)
06-09 17:15:01.211 3517-4589/? E/CSLegacyTypeTracker: add() : Adding agent NetworkAgentInfo{ ni{[type: MOBILE[LTE] - MOBILE_IMS, state: CONNECTED/CONNECTED, reason: connected, extra: ims, roaming: false, failover: false, isAvailable: true]}  network{503}  lp{{InterfaceName: rmnet1 LinkAddresses: [2600:380:8df5:37e5:d1aa:bd6d:898a:d0e8/64,]  Routes: [::/0 -> fe80::2 rmnet1,] DnsAddresses: [] Domains: null MTU: 0 TcpBufferSizes: 1048576,3145728,4194304,524288,1572864,2097152}}  nc{[ Transports: CELLULAR Capabilities: IMS&TRUSTED&NOT_VPN&VALIDATED LinkUpBandwidth>=51200Kbps LinkDnBandwidth>=102400Kbps Specifier: <1>]}  Score{50}  everValidated{true}  lastValidated{true}  created{true} lingering{false} explicitlySelected{false} acceptUnvalidated{false} everCaptivePortalDetected{false} lastCaptivePortalDetected{false} } for legacy network type 11
06-09 17:15:01.331 3054-3054/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_07
06-09 17:15:01.331 3054-3054/? E/DEBUG: AM write failed: Broken pipe
                                        
                                        [ 06-09 17:15:01.331  3054: 3054 E/         ]
                                        ro.product_ship = true
                                        
                                        [ 06-09 17:15:01.331  3054: 3054 E/         ]
                                        ro.debug_level = 0x4f4c
                                        
                                        [ 06-09 17:15:01.331  3054: 3054 E/         ]
                                        sys.mobilecare.preload = false
06-09 17:15:01.331 6196-6196/? E/audit: type=1701 msg=audit(1465506901.331:921): auid=4294967295 uid=10248 gid=10248 ses=4294967295 subj=u:r:untrusted_app:s0:c512,c768 pid=302 comm="mali-mem-purge" reason="memory violation" sig=11
06-09 17:15:01.371 3036-3036/? E/lowmemorykiller: Error writing /proc/32742/oom_score_adj; errno=22
06-09 17:15:01.451 3517-4177/? E/InputDispatcher: channel ~ Channel is unrecoverably broken and will be disposed!
06-09 17:15:01.611 3517-5141/? E/Watchdog: !@Sync 697 [06-09 21:15:01.617]
06-09 17:15:02.111 3517-4571/? E/Sensors: Pressure old sensor_state 131105, new sensor_state : 131073 en : 0
06-09 17:15:02.501 637-637/? E/Zygote: v2
06-09 17:15:02.511 637-637/? E/Zygote: accessInfo : 0
06-09 17:15:02.651 637-637/com.mapzen.erasermap E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.mapzen.erasermap, PID: 637
                                                                  java.lang.RuntimeException: Unable to start service com.mapzen.erasermap.service.NotificationService@aa3b667 with null: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter intent
                                                                      at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4080)
                                                                      at android.app.ActivityThread.access$2400(ActivityThread.java:222)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1898)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:158)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                   Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter intent
                                                                      at com.mapzen.erasermap.service.NotificationService.onStartCommand(NotificationService.kt)
                                                                      at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4063)
                                                                      at android.app.ActivityThread.access$2400(ActivityThread.java:222) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1898) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:158) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:7229) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
06-09 17:15:02.661 3517-651/? E/android.os.Debug: ro.product_ship = true
