### ISSUE TITLE
Route line goes away on start navigation

### ISSUE THREAD

**Issue by ecgreb** [mapzen/eraser-map#633]

**Comment by tallytalwar** [comment]
This is a tangram issue. Should be fixed with next release.

**Comment by sarahlensing** [comment]
I've verified that rolling back to tangram 0.2.2 resolves this. We will wait for the next release as @tallytalwar suggests.

**Comment by tallytalwar** [comment]
Tangram `0.3.2` is available on maven now: http://search.maven.org/#artifactdetails%7Ccom.mapzen.tangram%7Ctangram%7C0.3.2%7Caar
