### ISSUE TITLE
Hanging first instruction

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#636]
Occasionally I when i start a route it hangs here, moving the screen and hitting resume fixes it. Master 1609

![screenshot_20160615-164531](https://cloud.githubusercontent.com/assets/307758/16096846/d5050ace-3318-11e6-91e8-0e12387d82ec.png)

**Comment by ecgreb** [comment]
Looks like the camera is not updated either. Duplicate of https://github.com/mapzen/eraser-map/issues/602?

**Comment by mjcunningham** [comment]
I don't think its a dupe becuase sometimes it'll start the route even if the camera is wrong.
