### ISSUE TITLE
Icons for multi-modal maneuvers

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#640]
kTransit = 30;
kTransitTransfer = 31;
kTransitRemainOn = 32;
kTransitConnectionStart = 33;
kTransitConnectionTransfer = 34;
kTransitConnectionDestination = 35;
kPostTransitConnectionDestination = 36;

**Comment by ecgreb** [comment]
@souperneon what do you think about adding normal maneuver icons to the app for each of these types as our first pass on the transit route preview?

For example:

`ic_route_30.png`
`ic_route_30_lg.png`

https://github.com/mapzen/eraser-map/tree/master/app/src/main/res/drawable

This way we can start testing our transit implementation with the existing list view design. Then once this is complete we can start work on the redesigned list view for multi-modal.
