### ISSUE TITLE
Change secondary button to say "View Directions" instead of "View List"

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#641]

**Comment by souperneon** [comment]
@mjcunningham pointed out that "View List" doesn't make sense without having the context of the "Start Navigation". For consistency, let's change the button everywhere to say "View Directions"

**Comment by ecgreb** [comment]
@souperneon in order to do this we need to resize the two buttons to be the same width when both are showing to accommodate the longer text. Let me know if this looks ok.

https://github.com/mapzen/eraser-map/pull/643#issuecomment-227245679
