### ISSUE TITLE
Updated multi-modal route preview design

### ISSUE THREAD

**Issue by ecgreb** [mapzen/eraser-map#656]
Implement improved multi-modal route preview design.

**Comment by ecgreb** [comment]
@souperneon here is the main ticket for updated transit routing designs. Feel free to attach mockups here. New assets can be attached here or submitted in a PR. Thanks!

**Comment by souperneon** [comment]
![em_multimodal1](https://cloud.githubusercontent.com/assets/6125224/16342659/59247f6c-3a01-11e6-962e-a8f7e92fbf3c.png)
![em_multimodal2](https://cloud.githubusercontent.com/assets/6125224/16342658/5921e59a-3a01-11e6-9b86-a7b0395496f9.png)

**Comment by souperneon** [comment]
![em_multimodal3](https://cloud.githubusercontent.com/assets/6125224/16342811/f4d061c4-3a01-11e6-8ff8-135c62b58471.png)

**Comment by blair1618** [comment]
You'll be happy to know that the "dasharray" syntax for lines will be supported in the next release of tangram-es, so those route lines for walking segments can be dashed just like they are in the preview. Should the walking segments in the preview view be blue as well?

**Comment by souperneon** [comment]
yasssssss! they should be :)
Thanks @blair1618!
