### ISSUE TITLE
Incorrect region text when tapping on city

### ISSUE THREAD

**Issue by ecgreb** [mapzen/eraser-map#672]
When the map is zoomed out tapping on a city shows inconsistent results for region text leading to sometimes comical results. See examples below.

### I didn't realize Philly was part of NJ now.

![image](https://cloud.githubusercontent.com/assets/464123/16738260/ee04d5e6-4762-11e6-81ea-bac6de8485bb.png)

### If Philly is part of NJ then of course Trenton is part of NY.

![image](https://cloud.githubusercontent.com/assets/464123/16738280/0a31d804-4763-11e6-9f0a-8b72f66df3a4.png)

### Why just coordinates here? I think we can do better. Also no city labels on the map?

![image](https://cloud.githubusercontent.com/assets/464123/16738267/f67065d8-4762-11e6-8bf6-1aac05b44740.png)

### And the best one yet submitted by one of our users... display bug or political satire?

![image](https://cloud.githubusercontent.com/assets/464123/16738299/1e8dd046-4763-11e6-8498-8d773bd241c4.png)

**Comment by sarahlensing** [comment]
This appears to be a bug within tangram's `coordinatesAtScreenPosition` method. For the screenshot below, we get `x=605.75397`, `y=781.50696` from the `featurePickListener`. Then before issuing a `/reverse` request EM uses `coordinatesAtScreenPosition` to get a lat/lng. This returns `43.921186228202686`, `-77.05746435342736` which is in PEI

![screenshot_20160714-145740](https://cloud.githubusercontent.com/assets/494323/16856048/75492718-49d5-11e6-9770-1e7ad6a4862d.png)

**Comment by blair1618** [comment]
Unable to reproduce in the tangram-es android demo using the bubble-wrap scene file. Can you show me where these methods are being called in EM?

**Comment by sarahlensing** [comment]
Here is the `FeaturePickListener`: https://github.com/mapzen/eraser-map/blob/master/app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt#L286

And here is where we grab the coordinates/issue the request: https://github.com/mapzen/eraser-map/blob/master/app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt#L764

**Comment by tallytalwar** [comment]
Sometimes I see a country name and sometimes latlon. Where in the code is this information populated and where it is determined to show lat/lon vs a country name?

**Comment by tallytalwar** [comment]
Ahh! Could this be the issue? https://github.com/mapzen/eraser-map/blob/master/app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt#L300

Instead of `presenter.onReverseGeoRequested(poiTapPoint?.get(0)?.toFloat(),
poiTapPoint?.get(0)?.toFloat())` this should be `presenter.onReverseGeoRequested(poiTapPoint?.get(0)?.toFloat(),
poiTapPoint?.get(1)?.toFloat())`

I tried it and it fixes the issue. Cairo is back in Egypt for me :D

**Comment by tallytalwar** [comment]
Maybe a good candidate for a test case where a certain known `x/y` returns a known `a/b` combination.

**Comment by sarahlensing** [comment]
Aha! Good catch @tallytalwar. Updated and added a test case for this
