### ISSUE TITLE
Tangram crash

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#693]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/shamu/shamu:6.0.1/MOB30O/2920157:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 14900, tid: 14922, name: GLThread 1957  >>> com.mapzen.erasermap <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x6c545c08
    r0 6c545c08  r1 cc188800  r2 00001fd4  r3 eeb2d800
    r4 97f05b88  r5 a04920e0  r6 00000018  r7 00000000
    r8 00000002  r9 97e48100  sl aeeb2d80  fp 6c545c08
    ip 97f05b88  sp 9c78b148  lr a9399e65  pc a9399e66  cpsr 800f0030

backtrace:
    #00 pc 0012be66  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN20EsxVertexArrayObject18UpdateInternalVbosEPK17EsxDrawDescriptorjPK16EsxAttributeDesc+229)
    #01 pc 00160a49  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN20A4xVertexArrayObject11CalcVfdRegsEPK17EsxDrawDescriptorP10A4xVfdRegsi+880)
    #02 pc 00166325  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN10A4xContext16ValidateVfdStateEPK17EsxDrawDescriptori+52)
    #03 pc 00170727  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN10A4xContext13ValidateStateEPK17EsxDrawDescriptor+1194)
    #04 pc 00170c8f  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN10A4xContext18HwValidateGfxStateEPK17EsxDrawDescriptor+6)
    #05 pc 000e7333  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN10EsxContext16ValidateGfxStateEPK17EsxDrawDescriptor+470)
    #06 pc 000dc865  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN10EsxContext21DrawElementsInstancedE11EsxPrimTypej10EsxPixTypePKvj+432)
    #07 pc 000c6ed3  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN10EsxContext14GlDrawElementsEjijPKv+54)
    #08 pc 000bd481  /system/vendor/lib/egl/libGLESv2_adreno.so (glDrawElements+44)
    #09 pc 00114d03  /data/app/com.mapzen.erasermap-1/lib/arm/libtangram.so (_ZN7Tangram8MeshBase4drawERNS_13ShaderProgramE+374)
    #10 pc 0010141b  /data/app/com.mapzen.erasermap-1/lib/arm/libtangram.so (_ZN7Tangram5Style4drawERKNS_4TileE+802)
    #11 pc 000a2241  /data/app/com.mapzen.erasermap-1/lib/arm/libtangram.so (_ZN7Tangram6renderEv+372)
    #12 pc 009f592b  /data/app/com.mapzen.erasermap-1/oat/arm/base.odex (offset 0x815000)

**Comment by mjcunningham** [comment]
cc @blair1618 @tallytalwar

**Comment by blair1618** [comment]
Oh Adreno. This might be a driver bug that we'll need to work around :\

Can we get the other log output from Tangram preceding the crash?

**Comment by blair1618** [comment]
The crash looks to be specifically from a VAO operation, so to narrow down or hotfix the problem we could build tangram with VAOs disabled and see if we can reproduce the crash.

**Comment by ecgreb** [comment]
Closing in favor of https://github.com/mapzen/eraser-map/issues/707.
