### ISSUE TITLE
Add style switcher to settings

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#700]
In the Android SDK demo app there is a map switcher widget with choices for 3 house styles. 

It would be nice to add that switcher to the Eraser Map app to enable easier field testing of those styles to find bugs & other optimizations. And it should support all the official house styles, including Walkabout.

Could either be an internal debug only setting, or public setting (my preference).

**Comment by ecgreb** [comment]
I like it. Walkabout should also be bundled into the SDK for others to use as well, right?

**Comment by bleege** [comment]
PR #803 has been submitted to resolve this feature.

**Comment by sarahlensing** [comment]
This work is complete
