### ISSUE TITLE
Camera pan on navigation start

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#703]
As soon as you start navigation mode the camera pan for several seconds until it gets to your current location. It should start at your current location.

**Comment by ecgreb** [comment]
I kind of like that the map pans/zooms to the start of the route when you enter navigation mode as a visual transition of sorts. The animation duration should only be 1 second and no longer.

https://github.com/mapzen/eraser-map/blob/master/app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt#L301-L302

This behavior is also consistent with another popular mapping application on Android ;)

**Comment by sarahlensing** [comment]
Closing due inactivity
