### ISSUE TITLE
MapData objects disappear/reappear unexpectedly

### ISSUE THREAD

**Issue by sarahlensing** [mapzen/eraser-map#705]
Search pins, route start/end pins, and the navigation icon all disappear unexpectedly. 

In the video you can see that the search result pin is initially not shown (it reappears at the end of the video when backing out of route preview). Then, in the route preview view, toggling between route modes shows how the start/end pins are shown/hidden. Lastly, the navigation arrow is not shown (though what I usually see is that it is shown/hidden when backing out of and going back into navigation mode)

https://www.dropbox.com/s/547eybu9qgu9ryb/2016_07_25_11_29_04.mp4?dl=0

**Comment by tallytalwar** [comment]
We have an issue for this, since we were able to reproduce it on our desktop implementations: https://github.com/tangrams/tangram-es/issues/843

**Comment by ecgreb** [comment]
Linking to https://github.com/mapzen/eraser-map/issues/707 since it may be related.
