### ISSUE TITLE
Add application state global to scene file

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#710]
To support more interesting map styling, I propose adding the following set of Tangram global properties:

**`ux_application_state`**
- `browse`
- `feature_selection`
- `search`
- `route_selection`
- `route_navigation`
- `route_preview` (not yet implemented, could be used for Transit)

For instance, if the stylesheet knows we're in `route_navigation` application state then we can set all the text sizes to be larger, and reduce icon clutter on the map.

**Comment by sarahlensing** [comment]
https://github.com/mapzen/android/issues/372
