### ISSUE TITLE
Add route costing model global to scene file

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#711]
Paired with a new `application_state` Tangram scene file global that Eraser Map would set (proposed in https://github.com/mapzen/eraser-map/issues/710), let's also add a new global property for **Route costing model**:

**`ux_route_costing_model`**
- `auto` (x)
- `bicycle` (x)
- `multimodal` (x)
- `pedestrian` (x)
- `auto_shorter`
- `bus`

(x) supported in Eraser Map

See also:
- https://mapzen.com/documentation/turn-by-turn/api-reference/#costing-models

**Comment by nvkelso** [comment]
Related: map style switcher in https://github.com/mapzen/eraser-map/issues/700.

**Comment by sarahlensing** [comment]
Closing in favor of https://github.com/mapzen/eraser-map/issues/820
