### ISSUE TITLE
Coarse Location -> Accurate Location transition does not re-center map

### ISSUE THREAD

**Issue by msmollin** [mapzen/eraser-map#715]
- **Device name:** 
  Nexus 5
- **Android Version:** 
  4.4.4
- **App build number:**
  Master-1736
- **What did you expected to happen?**
  The map originally had me placed somewhere up the street I'm assuming due to coarse location accuracy. It then updated to place me at my house, at which point it should have re-centered my location.
- **What happened instead?**
  The blue dot just disappeared off the screen, and I wasn't exactly sure what had happened until I tried pressing the re-center button.
- **Steps to reproduce:**
  It takes some work to reproduce as you have to force the transition from inaccurate -> accurate location. Normally fresh booting the device in some place that cant easily see the sky (like my basement) and then loading EM, then moving upstairs to where the device can get GPS lock works.

**Comment by sarahlensing** [comment]
Location tracking has been implemented
