### ISSUE TITLE
No labels on POIs with icons on any zoom level

### ISSUE THREAD

**Issue by roman-yepishev** [mapzen/eraser-map#721]
- **Device name:** Nexus 5
- **Android Version:** 6.0.1
- **App build number:** 0.12
- **What did you expected to happen?** Labels near POIs
- **What happened instead?** No labels near POIs on any zoom level
- **Steps to reproduce:**
  - Browse the map
  - Observe that only the features without an icon get the labels

![tmp_2719-screenshot_20160809-215919-1269677728](https://cloud.githubusercontent.com/assets/601685/17539600/652d64ea-5e7d-11e6-80ac-9b1e8bc225cd.png)

**Comment by hjanetzek** [comment]
Thanks for reporting! Should be fixed in current eraser-map builds. (Or when using with the latest tangram-es)

**Comment by hjanetzek** [comment]
Hmm, not yet working in master-1743 build..

**Comment by hjanetzek** [comment]
I could reproduce this with android-0.4.1 tangram-es demo app and bubble-wrap 0.3. Switching to bubble-wrap 0.4 or globals-icons-localized-labels branch makes POI text work again.

**Comment by sarahlensing** [comment]
Resolved
