### ISSUE TITLE
Position arrow not updating in routing mode.

### ISSUE THREAD

**Issue by zerebubuth** [mapzen/eraser-map#724]
- **Device name:** Nexus 4
- **Android Version:**  5.1.1
- **App build number:** 0.12.0
- **What did you expected to happen?** When driving, I expected the position arrow to follow my current position, with the map and instructions updating too. 
- **What happened instead?** The map position stayed fixed but the point roundel continued to update, showing the current position, until it moved off-screen. The current position could be restored by dragging the map and hitting the "resume" button, but would not update. Generating a new route resulted in the same behaviour.
- **Steps to reproduce:** Create a route, enter routing mode, move a significant distance away.
- **Attach a screenshot**

![screenshot_2016-09-05-11-34-15](https://cloud.githubusercontent.com/assets/271360/18282333/99dd3080-7458-11e6-916f-116558d8d1bd.png)
- **Attach device logs**

Sorry - by the time I had got home, logcat had filled up with other things.

If something happened while you were routing, share with us:
- **Where were you?** Near http://www.openstreetmap.org/?mlat=51.58170&mlon=-0.12654#map=19/51.58170/-0.12654
- **Routing from origin:** 51.58138,-0.12764
- **Routing to destination:** 51.58039,-0.12405

**Comment by zerebubuth** [comment]
I managed to reproduce this, and 
[logcat.txt](https://github.com/mapzen/eraser-map/files/478434/logcat.txt) seems to be the relevant lines from logcat. Steps to reproduce were: Start a route, move from the start position, rotate the device - that seemed to work on at least two occasions. Not sure if the "provider doesn't exist" or "leaked ServiceConnection" is relevant?

**Comment by sarahlensing** [comment]
This has been resolved
