### ISSUE TITLE
New User Messaging When Location Off

### ISSUE THREAD

**Issue by heidihysell** [mapzen/eraser-map#726]
Device name: Galaxy S6 Edge
Android Version: 5.1.1 
App build number: dev 
What did you expected to happen? When searching for a location I would be able to click the navigation button and it would bring up directions. 
What happened instead? I clicked on the navigation and the navigation pane disappeared. 
Steps to reproduce: Turn location services off. Download the app. Open the app. Search for a location. Click the nav icon.
Attach a screenshot
Attach device logs

** it appears that this happens when the user has location tracking disabled - would be great to let the user know that they need location services turned on, but maybe give them a link to read more on what you all are tracking and how

If something happened while you were routing, share with us:

Where were you?
Routing from origin:
Routing to destination:

If something happened while you were searching, share with us:

Where were you?

**Comment by ecgreb** [comment]
Thanks for the detailed report. I agree we could do better with messaging here and offer a possible resolution.

@sarahlensing seems like we could use the Settings API in Lost 2.0 to help resolve this situation.

**Comment by sarahlensing** [comment]
@ecgreb definitely!
