### ISSUE TITLE
Kotlin imports...

### ISSUE THREAD

**Issue by ecgreb** [mapzen/eraser-map#736]
...are kind of a mess right now. Fortunately we now have the ability to set import order and rules in the code style settings for Kotlin.

Kotlin import rules should be updated to match Java (correct order + blank lines) and pushed to https://github.com/mapzen/java-code-styles. Imports should be organized in all .kt files.

**Comment by sarahlensing** [comment]
👍 👍 👍

**Comment by sarahlensing** [comment]
Closing as there isnt anything to update regarding this, we've got all the kotlin settings available configured.
