### ISSUE TITLE
Routing mode broken on configuration change

### ISSUE THREAD

**Issue by ecgreb** [mapzen/eraser-map#744]
* **Device name:** 
Nextbit Robin
* **Android Version:** 
6.0.1
* **App build number:**
0.13-SNAPSHOT
* **What did you expected to happen?** 
Navigation mode should properly resume after config change
* **What happened instead?**
Routing mode stopped completely after rotation. Pager does not advance. Route icon does not move. No verbal instructions.
* **Steps to reproduce:**
Go for a drive and rotate the device

**Comment by tallytalwar** [comment]
https://github.com/mapzen/eraser-map/issues/724 seams related. @zerebubuth seems to have some headway with the logs.

**Comment by tallytalwar** [comment]
I always have device rotation off on my device, and I was able to reproducible this almost on every navigation. Do not have any particular repro though.
