### ISSUE TITLE
Find me button should reset tilt

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#761]

**Comment by ecgreb** [comment]
@mjcunningham the find me button is now part of the current location layer in the Mapzen SDK. Should this be the default behavior for the find me button out of the box?

**Comment by mjcunningham** [comment]
@ecgreb Yeah I think it should reset anything the user has done to the view.

**Comment by ecgreb** [comment]
probably not rotation though right, that is reserved for tapping on the compass widget?

**Comment by mjcunningham** [comment]
Correct, sorry should have been more specific. "Find me" should do tilt and zoom and "compass" should do orientation.
