### ISSUE TITLE
Map pins cover map marker / POIs

### ISSUE THREAD

**Issue by msmollin** [mapzen/eraser-map#762]
- **Device name:** 
  Nexus 5
- **Android Version:** 
  4.4.4
- **App build number:**
  master-1795
- **What did you expected to happen?** 
  When I tapped on a map marker, a pin would appear with the pin tip on the marker.
- **What happened instead?**
  The pin basically covers the marker.
- **Attach a screenshot**
  ![screenshot_2016-10-28-16-25-59](https://cloud.githubusercontent.com/assets/1163880/19822107/c9c0bd94-9d2f-11e6-9db9-2245c78192d0.png)

**Comment by tallytalwar** [comment]
This could be because of wrong anchor set in the style sheet or anchoring is broken on current master of tangram-es. @blair1618 I think we saw something similar on tizen (when we were testing sticker vs maker work).

**Comment by karimnaaji** [comment]
It's none of that, the marker in that case does not know to which other label it is linked to, parenting is broken because the parenting only exists at stylesheet creation. It seems to be more a problem of how our markers system would let markers link to already existing label features.

**Comment by tallytalwar** [comment]
Interesting this used to work before though. 
Some logic did change on core label code which is causing this to happen.

**Comment by karimnaaji** [comment]
Ok so there is a regression on that side, I thought this was coming from a misusage of unified point/text style. 
https://github.com/tangrams/tangram-es/pull/1046

**Comment by msmollin** [comment]
Fixed in master-1811
