### ISSUE TITLE
Reorient Camera button is always visible on routing preview which causes layout issues in horizontal orientation on smaller screen devices

### ISSUE THREAD

**Issue by msmollin** [mapzen/eraser-map#764]
- **Device name:** 
  Nexus 5
- **Android Version:** 
  4.4.4
- **App build number:**
  master-1795
- **Steps to Reproduce:**
- Route to a location.
- Rotate the device to horizontal orientation. 

There's a number of issues here which can be seen in the attached screen shot. 1 is the camera reorientation button is constantly visible even though I haven't reoriented the camera. This cause the "find me" button to get hidden and causes UI weirdness.

Second is the layout for routing preview on smaller screen devices is not terribly functional due to how large the font and iconography are.

![screenshot_2016-10-28-16-28-56](https://cloud.githubusercontent.com/assets/1163880/19822417/558b7b42-9d31-11e6-9590-ee86161e4f67.png)

**Comment by ecgreb** [comment]
This screen needs a redesign badly but for this release we should at a minimum make sure the buttons don't overlap. Even if this means the compass or the current location button.

We can also adjust margins and padding in landscape to make the header and footer a bit more compact.
