### ISSUE TITLE
Tapping on search bar after rotation while routing preview is up leaves route line artifacts

### ISSUE THREAD

**Issue by msmollin** [mapzen/eraser-map#765]
- **Device name:** 
  Nexus 5
- **Android Version:** 
  4.4.4
- **App build number:**
  master-1795
- **What did you expected to happen?** 
  The search bar not to be available just rotating the device while in routing preview
- **What happened instead?**
  I can tap on the search screen and search for a new place. This dumps me out of the routing preview flow and seems to orphan drawn poly lines on the map, and leaves a weird gray pin as well over your current location.
- **Steps to reproduce:**
- Route to a destination. 
- Rotate the device.
- Notice the search bar is available for a few seconds, and tap into it to search.
- **Attach a screenshot**
  It's hard to grab a screen shot mid test, but here's the ultimate outcome of the above process.
  ![screenshot_2016-10-28-16-30-31](https://cloud.githubusercontent.com/assets/1163880/19822511/dad702f8-9d31-11e6-8530-cb996140b5dd.png)

**Comment by ecgreb** [comment]
Wow nice catch. The action bar only shows for about a second for me before animating off the screen but when I tap it I get the exact same behavior described.
