### ISSUE TITLE
Add ability to reorient the map to North without changing the extent

### ISSUE THREAD

**Issue by rmglennon** [mapzen/eraser-map#78]
When zooming with multitouch, it's really easy (maybe too easy) to rotate the map. If you tap the compass rose in the bottom corner, the map reorients, but it also zooms back to the default home location and extent. It would be really handy to have a way to keep your current extent, but remove the rotation that is often added accidentally.

See snips from this chat:
Mike
we should also make it less easy to rotate the map when zooming
Rhonda
yep. there's a related issue for that:  Issue #68: Don't allow map rotation when zoomed (0,1,2,3,4,5) by nvkelso in mapzen/eraser-map on GitHub
Ekta
yeah Nathaniel and I made that issue last week
I talked to Varun about it and he said he will get to it
but adding a compass at all times is a VERY NICE TO HAVE
I have the design and asset ready… just have to build it ;)
Matt
We have all the capabilities we'd need for this; you can query or set the rotation of the tangram map view and add a button-like compass (like the "find me" button)
It will also help when we add smooth animations for view transitions (which will happen!)

**Comment by bcamper** [comment]
Should be handled by the app until we build view animation into Tangram
(which we plan to do).

**Comment by ecgreb** [comment]
This would be easy to do in the app.

@souperneon can you design an icon and placement for a find North button?

**Comment by souperneon** [comment]
@ecgreb will do!
