### ISSUE TITLE
Search pin animation is jumpy

### ISSUE THREAD

**Issue by ecgreb** [mapzen/eraser-map#790]
* **Device name:** Nextbit Robin
* **Android Version:** Android 6.0.1
* **App build number:** master-1843
* **What did you expected to happen?** Single tap on search pin should produce smooth animation from the current location to the selected pin.
* **What happened instead?** Map first jumps to another location then animates from the new location to the selected pin.
* **Steps to reproduce:** Perform search that produces multiple results in close proximity. Tap on pins.

**Comment by ecgreb** [comment]
Also we should probably not reset the zoom level when a search result pin is tapped (just set position with easing). If you zoom out to see more pins over a larger area the effect is very abrupt.

**Comment by sarahlensing** [comment]
Won't fix

...we don't support artisanal hardware ;)
