### ISSUE TITLE
Add indication of current position

### ISSUE THREAD

**Issue by rmglennon** [mapzen/eraser-map#80]
I'd like the ability to know where I am currently with some kind of "dot" indicator. I can click the compass rose to reset the map location, but that takes me to a zoomed out extent.

This is important for routing. If I have panned to another area and then search for a place to route to, it's not clear whether the app will be routing from the current extent of the map or my actual current position.

Nexus 5, Android 6.0. Tested on 10/29/2015

**Comment by tallytalwar** [comment]
This is present in the app. Currently broken due to some recent API changes in tangram-es.
I am currently working on updating this.

**Comment by ecgreb** [comment]
Most likely related to https://github.com/mapzen/eraser-map/issues/84
