### ISSUE TITLE
Missing Interchange Data

### ISSUE THREAD

**Issue by msmollin** [mapzen/eraser-map#806]
* **Device name:** 
Nexus 5
* **Android Version:** 
4.4.4
* **App build number:**
eraser-map-0.13.1
* **What did you expected to happen?** 
The other mapping apps routed me over the new EZ-Pass slip-ramp that opened about 2 months ago but has been under construction for years.
* **What happened instead?**
EM seems to be missing this data.

* **Attach a screenshot**
![screenshot_2016-12-20-07-26-57](https://cloud.githubusercontent.com/assets/1163880/21357269/9195d728-c6a2-11e6-868d-684fca35c939.png)

* **Where were you?**
Souderton, PA
* **Routing from origin:**
103 Hunters Way, Souderton, PA 18964
* **Routing to destination:**
800 Sloan Ave, Trenton NJ

**Comment by tallytalwar** [comment]
OSM needs this data: http://www.openstreetmap.org/#map=19/40.24971/-75.34721

**Comment by msmollin** [comment]
Yeah I knew that going in. I'm taking this an an exercise of "How do we handle data related issues" :)

**Comment by tallytalwar** [comment]
Have something in the app description: Users if you see any missing data, please edit OSM map :P. JK or maybe not!
