### ISSUE TITLE
Random Reroutes during routing

### ISSUE THREAD

**Issue by msmollin** [mapzen/eraser-map#809]
* **Device name:** 
Nexus 5
* **Android Version:** 
4.4.4
* **App build number:**
eraser-map-0.13.1
* **What did you expected to happen?** 
Routing to continue normally.
* **What happened instead?**
I had a number of random restarts of routing while routing. This could be related to #807 if we get a location from LOST that OTR thinks it needs to do a re-route, but one of the cases it didn't seem that way.
* **Steps to reproduce:**
Begin an extended route and wait? Sorry hard to say beyond that. 
* **Attach a screenshot**
![screenshot_2016-12-20-07-57-16](https://cloud.githubusercontent.com/assets/1163880/21358077/939c4c52-c6a5-11e6-901d-b755298151b7.png)
![screenshot_2016-12-20-08-00-58](https://cloud.githubusercontent.com/assets/1163880/21358082/974f6a5a-c6a5-11e6-9959-4149fbe2df43.png)
![screenshot_2016-12-20-08-09-59](https://cloud.githubusercontent.com/assets/1163880/21358088/9ae101c4-c6a5-11e6-923b-3d7f7e2c4884.png)

* **Where were you?**
Souderton, PA
* **Routing from origin:**
103 Hunters Way, Souderton, PA 18964
* **Routing to destination:**
800 Sloan Ave, Trenton NJ

**Comment by sarahlensing** [comment]
Closing in favor of #807
