### ISSUE TITLE
Add ability to mute route narration sounds

### ISSUE THREAD

**Issue by rmglennon** [mapzen/eraser-map#81]
It would be nice to have a setting that enables me to mute the voice guidance when routing. 

If you're in a quiet location, like an office or theatre and you want to look at a route, the unexpected voice narration could cause invoke stares from others around you.

To reproduce:
1. Search or tap to choose a location as a destination.
2. Choose the mode and tap Start navigation.
3. Voice guidance starts. 

Nexus 5, Android 6.0, tested on 10/29/2015.

**Comment by ecgreb** [comment]
This is definitely on our list for v1. Stay tuned!

**Comment by souperneon** [comment]
![11](https://cloud.githubusercontent.com/assets/6125224/11965809/3649ec2a-a8c5-11e5-8d1b-77b73fe65c4c.png)
 Atatched is a possible placement for the volume on/off icon. For v1, it can just me mute-unmute but in the future we can do stuff like "softer, louder' etc. that apps these days allow

**Comment by mjcunningham** [comment]
duplicate.
