### ISSUE TITLE
route maneuver icons hard to see (top ui chrome)

### ISSUE THREAD

**Issue by dgearhart** [mapzen/eraser-map#84]
* **Device name:** Samsung Galaxy S5
* **Android Version:** 5.0
* **App build number:** N/A
* **What did you expected to happen?** To easily see maneuver directional icon and current route position icon while driving
* **What happened instead?** Not able to easily view - the current route position sometimes would disappear
* **Steps to reproduce:** Any route

**Comment by ecgreb** [comment]
We think this is an issue on the Tangram side possibly related to https://github.com/tangrams/tangram-es/pull/341 and/or recent stylesheet updates.

Thanks @dgearhart for the report.

**Comment by dgearhart** [comment]
@ecgreb to clarify - I was also referring to the maneuver icons at the top of the app display

**Comment by nvkelso** [comment]
I'm running into this as well. Compared with the Open app, the glyphs used in Eraser Map to render the arrows are much thinner / small and aren't legible.

**Comment by mjcunningham** [comment]
@souperneon are these assets somewhere?

**Comment by souperneon** [comment]
@mjcunningham they can be :) I wanted the design of that screen to come together a little bit so I can gauge line thickness etc. better for the assets so I don't have to recreated them many many times. I can add a working version somewhere though if that helps!

**Comment by mjcunningham** [comment]
Closing this and tracking along w the UI work here: https://github.com/mapzen/eraser-map/issues/211
