### ISSUE TITLE
some search labels contain blank sections

### ISSUE THREAD

**Issue by missinglink** [mapzen/eraser-map#85]
search labels can have 1-3 comma delimited segments which seems to cause a minor rendering bug in some edge cases, as below:

where possible labels are returned in the format `{name}, {local}, {regional}`, but in some cases where the data is not available or not applicable then there may be less than 3 segments.

```
search: "Canada"
label: "Canada"
rendered: "Canada, ,"
```
```
search: "Redwo"
label: "Redwood County, MN"
rendered: "Redwood County, MN, , Minnesota"
```

![screenshot](http://missinglink.embed.s3.amazonaws.com/eraser-ss.png)

**Comment by ecgreb** [comment]
This logic lives in Pelias Android SDK. Created a new issue to track there.

https://github.com/mapzen/pelias-android-sdk/issues/13

**Comment by ecgreb** [comment]
Resolved by https://github.com/mapzen/pelias-android-sdk/pull/15
