### ISSUE TITLE
Wrong location from recent searches

### ISSUE THREAD

**Issue by tallytalwar** [mapzen/eraser-map#87]
Phone: Samsung Galaxy S5
Android Version: 5.0

I selected a location from my recent searches (the very first one in the screen shot), but the app fetches some other location instead of the selected location. Was able to reproduce this with another locations.

* Recent Searches:
![recentsearches](https://cloud.githubusercontent.com/assets/360641/10864177/77889dfe-7fbb-11e5-816f-47889d34590e.png)

* Wrong Location fetched
![wronglocation](https://cloud.githubusercontent.com/assets/360641/10864181/86cfaaa0-7fbb-11e5-88f8-ef4011aa0fdc.png)

**Comment by dgearhart** [comment]
Agreed - this happened to me as well. It would be nice to keep our recent selections so we could select again.

**Comment by souperneon** [comment]
I got the same one as well
![2015-11-02](https://cloud.githubusercontent.com/assets/6125224/10894076/593e86b8-817a-11e5-99d8-83b4a5396046.png)
