### ISSUE TITLE
Update route list view while in route (active cell)

### ISSUE THREAD

**Issue by tallytalwar** [mapzen/eraser-map#88]
Phone: Samsung Galaxy S5
Android Version: 5.0

First of all I like that even in this early version we have the option of checking the route list while in route/navigation mode. Second thing I really like is that its a transparent view, and the underneath map/route is visible.

It would be good to position the route list view to the current already traveled position rather than showing the route list from the very beginning of the route.

In the screen shot below, I was on middle of a route on I-95 North bound, and when I opened route list, it started from the very beginning (from my apartment). I usually use route list in navigation to see whats coming next.

![routelist](https://cloud.githubusercontent.com/assets/360641/10864253/a0694856-7fbe-11e5-8ad5-2df02957c8b7.png)

**Comment by souperneon** [comment]
@tallytalwar agreed. I had the same experience. We didn't have this capability in Open either.
it's the combination of highlighting which direction you are on/removing past directions and updating the counter of distance to match your most current location.
We'll get there :)

**Comment by tallytalwar** [comment]
We are getting there :D.

As a first step, instead of updating the list, maybe it would make sense to highlight the section of the route user is are currently on. This gives the user the entire route list, along with the information of where she/he is and whats coming next, without actually modifying the list.

**Comment by souperneon** [comment]
agreed. I think that's what we will do. :)
