### ISSUE TITLE
Excessive instructions when off-route

### ISSUE THREAD

**Issue by dgearhart** [mapzen/eraser-map#89]
* **Device name:** Samsung Galaxy S5
* **Android Version:** 5.0
* **App build number:** N/A
* **What did you expected to happen?** When getting of the route to drop off passenger at park-n-ride - I expected the typical re-route instructions from my off route location.
* **What happened instead?** The app was giving excessive instructions and then started repeating the same instruction until I got close to the PA 283 West on ramp
* **Steps to reproduce:** Run a highway route, take an exit in the middle of the highway route, and then get back on the original route.
* **Attach a screenshot**
![screenshot from 2015-11-02 11 05 05](https://cloud.githubusercontent.com/assets/7515853/10886968/92c06f1e-8152-11e5-9474-4eae8520db32.png)

* **Where were you?** Park-n- ride off of Hershey Road, PA 743 North (40.183258,-76.600310)
* **Routing from origin:** Lancaster, PA
* **Routing to destination:** Harrisburg, PA

**Comment by gknisely** [comment]
I experienced the same issue.  Same phone and versions.  40.04248, -76.29947 to 39.9654, -76.1837.  I had to detour off route to South Ann Street (40.03873, -76.29503) and started getting tons of narrative call outs.

**Comment by ecgreb** [comment]
Consolidated into https://github.com/mapzen/eraser-map/issues/213
