### ISSUE TITLE
Route highlight did not update on re-route

### ISSUE THREAD

**Issue by dgearhart** [mapzen/eraser-map#97]
* **Device name:** samsung Model: SM-G900V
* **Android Version:** 5.0
* **App build number:** master-420
* **What did you expected to happen?** That when taking different path that the route will recalculate and display properly on the map
* **What happened instead?** The route was recalculated however the route highlight on the map was never updated. Also, sometimes there were several current location pins displayed on the map. Please see screenshots
* **Steps to reproduce:** Run a route, take a different path and notice the route highlight and current position icon is not correct on the map
* **Attach a screenshot**
![screenshot_2015-11-03-16-24-16](https://cloud.githubusercontent.com/assets/7515853/10939294/8bd58fae-82ce-11e5-939e-6c074d41e197.png)
![screenshot_2015-11-03-16-26-35](https://cloud.githubusercontent.com/assets/7515853/10939297/8bd8c99e-82ce-11e5-8e4f-5e278b46e1ab.png)
![screenshot_2015-11-03-16-57-16](https://cloud.githubusercontent.com/assets/7515853/10939295/8bd6b87a-82ce-11e5-94d8-6456bd13f14f.png)
![screenshot_2015-11-03-16-58-31](https://cloud.githubusercontent.com/assets/7515853/10939296/8bd83006-82ce-11e5-97d6-d29a772b3fc9.png)

**Comment by nvkelso** [comment]
+1

**Comment by nvkelso** [comment]
+1000 I keep getting this on shorter routes when I would take a slightly different street or on longer trips when I need to take a break from driving.
