### ISSUE TITLE
Start instruction repeated constantly

### ISSUE THREAD

**Issue by dgearhart** [mapzen/eraser-map#98]
* **Device name:** samsung Model: SM-G900V
* **Android Version:** 5.0
* **App build number:** master-420
* **What did you expected to happen?** When starting route in a parking lot that the route will adjust as I near the connecting road
* **What happened instead?** The app constantly repeated the start maneuver even when I was not moving - it continued repeating the start maneuver until I was on a connecting road.
* **Steps to reproduce:** Run a route from the middle of a parking lot; screenshot has lat/lon in the url
* **Attach a screenshot**
![screenshot from 2015-11-04 08 59 31](https://cloud.githubusercontent.com/assets/7515853/10939875/aa694c22-82d2-11e5-964e-555ccd1080e3.png)

**Comment by ecgreb** [comment]
Wow that is annoying :trollface:

**Comment by ecgreb** [comment]
Consolidated into https://github.com/mapzen/eraser-map/issues/213
