### ISSUE TITLE
Double tap drag to zoom also triggers reverse geocode

### ISSUE THREAD

**Issue by ecgreb** [mapzen/eraser-map#99]
Double tap drag also gets interpreted as long press gesture.

**Comment by tallytalwar** [comment]
Yup, we have a card for this on tangram-es, to make longpress (generic motion event) and double tap drag zooming mutually exclusive.

**Comment by nvkelso** [comment]
Related: https://github.com/mapzen/eraser-map/issues/148

**Comment by tallytalwar** [comment]
#232 Fixes this.
